AMPFunctionsA.cpp File Reference
#include `spectral.h`
Functions
double Psia (int I, int i, double z)
double DPsia (int I, int i, double z)
double Psib (int I, int J, int i, int j, double z)
double DPsib (int I, int J, int i, int j, double z)
double Psic (int I, int J, int K, int i, int j, int k, double z)
Function Documentation
DPsia()
double DPsia (int I, int i, double z)
Definition at line 30 of file AMPFunctionsA.cpp.
References Jacobi_P().
Referenced by DPsib(), Triangle::elem_traces(), Quadrilateral::elem_traces(), Linear::elem_traces(), Hexahedral::elem_traces(), Hexahedral::eval_GradPhi(), and Quadrilateral::eval_GradPhi().
DPsib()
double DPsib (int I, int J, int i, int j, double z)
Definition at line 71 of file AMPFunctionsA.cpp.
References DPsia(), and Jacobi_P().
Referenced by Triangle::elem_traces().
Psia()
double Psia (int I, int i, double z)
Definition at line 8 of file AMPFunctionsA.cpp.
References Jacobi_P().
Referenced by Hexahedral::computeAtPoints(), Linear::computeAtPoints(), Tetrahedral::computeAtPoints(), Triangle::computeAtPoints(), Quadrilateral::computeAtPoints(), Hexahedral::computeVertice(), Linear::computeVertice(), Tetrahedral::computeVertice(), Triangle::computeVertice(), Quadrilateral::computeVertice(), Triangle::Dirichlet(), Quadrilateral::Dirichlet(), Linear::elem_traces(), Hexahedral::elem_traces(), Triangle::elem_traces(), Quadrilateral::elem_traces(), Hexahedral::eval_GradPhi(), Quadrilateral::eval_GradPhi(), Linear::evalGQ(), Tetrahedral::evalGQ(), Triangle::evalGQ(), Quadrilateral::evalGQ(), Hexahedral::evalGQ(), Linear::make_local_matrices(), Tetrahedral::make_local_matrices(), Quadrilateral::make_local_matrices(), Hexahedral::make_local_matrices(), Triangle::make_local_matrices(), Hexahedral::mass(), Triangle::mass(), Quadrilateral::mass(), Linear::mass(), Tetrahedral::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Psib(), Psic(), Triangle::set(), Quadrilateral::set(), Linear::set(), Hexahedral::set(), Triangle::vector_of_integral_of_f_Phi_dv(), Quadrilateral::vector_of_integral_of_f_Phi_dv(), Linear::vector_of_integral_of_f_Phi_dv(), Hexahedral::vector_of_integral_of_f_Phi_dv(), and Tetrahedral::vector_of_integral_of_f_Phi_dv().
Psib()
double Psib (int I, int J, int i, int j, double z)
Definition at line 51 of file AMPFunctionsA.cpp.
References Jacobi_P(), and Psia().
Referenced by Tetrahedral::computeAtPoints(), Triangle::computeAtPoints(), Tetrahedral::computeVertice(), Triangle::computeVertice(), Triangle::elem_traces(), Tetrahedral::evalGQ(), Triangle::evalGQ(), Tetrahedral::make_local_matrices(), Triangle::make_local_matrices(), Tetrahedral::mass(), Triangle::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Psic(), Triangle::set(), Tetrahedral::vector_of_integral_of_f_Phi_dv(), and Triangle::vector_of_integral_of_f_Phi_dv().
Psic()
double Psic (int I, int J, int K, int i, int j, int k, double z)
Definition at line 93 of file AMPFunctionsA.cpp.
References Jacobi_P(), Psia(), and Psib().
Referenced by Tetrahedral::computeAtPoints(), Tetrahedral::computeVertice(), Tetrahedral::evalGQ(), Tetrahedral::make_local_matrices(), Tetrahedral::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), and Tetrahedral::vector_of_integral_of_f_Phi_dv().