ASPFunctions.cpp File Reference
#include `spectral.h`
Functions
void jacobi_poly (int n, double alpha, double beta, double x, double cx[])
void Jacobi_P (int n, double a, double b, double x, double &y, double &dy, double &d2y)
void Jacobi_P (int n, double a, double b, double x, double &y)
void Jacobi_P (int n, double a, double b, double x, double &y, double &dy)
void Jacobi_roots (int m, double alpha, double beta, double x[])
double my_gamma (double x)
double gamma_log (double x)
double C (int Q, double alpha, double beta, double xi)
void Gauss_Lobatto_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
void Gauss_Radau_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
void Gauss_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
double B (int q, double alpha, double beta, double xi)
double d_epsilon (void)
Function Documentation
B()
double B (int q, double alpha, double beta, double xi)
Definition at line 801 of file ASPFunctions.cpp.
References aux, Jacobi_P(), and my_gamma().
Referenced by DG_Prob::DG_EI_Epetra_Inflow(), DG_Prob::DG_EI_Epetra_Interior(), DG_Prob::DG_EI_Epetra_Outflow(), DG_Prob::DG_initial_conditions(), Quadrilateral::Dirichlet(), Triangle::Dirichlet(), DG_Prob::Eigenvectors(), Gauss_Radau_Jacobi_parameters(), PhElem< 2 >::make_Kcomp_Elast2D(), PhElem< 2 >::projetar_C0(), DG_Elem::show_Volume(), ED_Prob::SolveElast2D_dyn(), PhElem< 2 >::transformacao_direta(), and DG_Elem::VolumeIntegrals().
C()
double C (int Q, double alpha, double beta, double xi)
Definition at line 637 of file ASPFunctions.cpp.
References aux, Jacobi_P(), and my_gamma().
Referenced by Gauss_Lobatto_Jacobi_parameters(), PhElem< 2 >::make_Kcomp_Elast2D(), and ED_Prob::SolveElast2D_dyn().
d_epsilon()
double d_epsilon (void)
Definition at line 816 of file ASPFunctions.cpp.
Referenced by gamma_log().
gamma_log()
double gamma_log (double x)
Definition at line 348 of file ASPFunctions.cpp.
References d_epsilon(), p1(), and p2().
Referenced by my_gamma().
Gauss_Jacobi_parameters()
void Gauss_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
Definition at line 756 of file ASPFunctions.cpp.
References aaux, aux, Jacobi_P(), Jacobi_roots(), MAXQ, and my_gamma().
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_initial_conditions(), Quadrilateral::elem_traces(), Hexahedral::elem_traces(), Triangle::elem_traces(), Quadrilateral::gauss_parameters_default(), Linear::gauss_parameters_default(), Hexahedral::gauss_parameters_default(), Triangle::gauss_parameters_default(), DG_Prob::Processa_condicoes_contorno(), Triangle::trace(), Hexahedral::trace(), and Quadrilateral::trace().
Gauss_Lobatto_Jacobi_parameters()
void Gauss_Lobatto_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
Definition at line 660 of file ASPFunctions.cpp.
References aaux, aux, C(), Jacobi_P(), Jacobi_roots(), and MAXQ.
Referenced by Quadrilateral::Dirichlet(), Triangle::Dirichlet(), Quadrilateral::gauss_parameters_default(), Linear::gauss_parameters_default(), Hexahedral::gauss_parameters_default(), Tetrahedral::gauss_parameters_default(), and Triangle::gauss_parameters_default().
Gauss_Radau_Jacobi_parameters()
void Gauss_Radau_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
Definition at line 712 of file ASPFunctions.cpp.
References aaux, aux, B(), Jacobi_P(), Jacobi_roots(), and MAXQ.
Referenced by Quadrilateral::gauss_parameters_default(), Linear::gauss_parameters_default(), Hexahedral::gauss_parameters_default(), Triangle::gauss_parameters_default(), and Tetrahedral::gauss_parameters_default().
Jacobi_P() [1/3]
void Jacobi_P (int n, double a, double b, double x, double & y, double & dy, double & d2y)
Definition at line 140 of file ASPFunctions.cpp.
Referenced by B(), C(), ColDifGJ(), ColDifGLJ(), ColDifGRJ(), DPsia(), DPsib(), Gauss_Jacobi_parameters(), Gauss_Lobatto_Jacobi_parameters(), Gauss_Radau_Jacobi_parameters(), Jacobi_roots(), Psia(), Psib(), and Psic().
Jacobi_P() [2/3]
void Jacobi_P (int n, double a, double b, double x, double & y)
Definition at line 185 of file ASPFunctions.cpp.
Jacobi_P() [3/3]
void Jacobi_P (int n, double a, double b, double x, double & y, double & dy)
Definition at line 230 of file ASPFunctions.cpp.
jacobi_poly()
void jacobi_poly (int n, double alpha, double beta, double x, double cx[])
Definition at line 5 of file ASPFunctions.cpp.
Jacobi_roots()
void Jacobi_roots (int m, double alpha, double beta, double x[])
Definition at line 274 of file ASPFunctions.cpp.
References e, Jacobi_P(), and m.
Referenced by ColDifGJ(), ColDifGLJ(), ColDifGRJ(), Gauss_Jacobi_parameters(), Gauss_Lobatto_Jacobi_parameters(), and Gauss_Radau_Jacobi_parameters().
my_gamma()
double my_gamma (double x)
Definition at line 303 of file ASPFunctions.cpp.
References gamma_log().
Referenced by B(), C(), and Gauss_Jacobi_parameters().