DG_Elem Class Reference
#include <DG_Elem.hpp>
Public Member Functions
DG_Elem ()
~DG_Elem ()
void inicia_vetores ()
void set_fontes (double sw, double sn)
double show_rho ()
double show_Volume ()
void inicia_funcoes_na_borda (EDGE *border)
void finaliza_vetores ()
void inicia_tracos (EDGE *border)
void echo_traco (FILE *f_eco=nullptr)
void Atualizar_valores (FILE *fout=NULL)
void set_permeabilidade (const double, const double, const double)
void set_mass_density (double)
void set_porosidade (double)
void VolumeIntegrals_UMFPACK (const double Dt, Fluids fls, int &count, int *Ti, int *Tj, double *Tx, double *B, double *=NULL, double *=NULL)
void VolumeIntegrals (const double Dt, Fluids fls, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS, double *=NULL, double *=NULL)
void VolumeTracos (const double Dt, Fluids fls, double *=NULL, double *=NULL)
void VolumeIntegralsT (const double Dt_new, const double Dt_old, int &count, int *Ti, int *Tj, double *Tx, double *B)
void calcula_tracos (Fluids fls)
void VolumeIntegrals_IG (Fluids fls, int &count, int *Ti, int *Tj, double *Tx, double *B)
void perm_val (double K[3])
void Traco_sn (const int &h, double *saida)
void Traco_pw (const int &h, double *saida)
void Traco_Kgrad_pw (const int &h, double **saida)
void Traco_Kgrad_pc (const int &h, double **saida)
void Traco_Kgrad_sn (const int &h, double **saida)
void Traco_phi (const int &lado, const int &ivar, const int &ind, double *saida)
void Traco_phi_1 (const int &lado, const int &ivar, const int &pos, double *saida)
void Traco_grad_phi (const int &lado, const int &ivar, const int &ind, double **saida)
void Traco_Kgrad_phi_n (const int &lado, const int &ivar, const int &ind, double *saida)
int show_NumLocalVars ()
void teste ()
void set_ptr_stdel (Stdel *pointer, Stdel *pointer1)
void set_ptr_stdel (Stdel *pointers[])
void set_ptr_stdel (Stdel *pointer)
void set_ptr_stdel_var (const int ind, Stdel *pointer)
void set_Vert_map (const int &n_in, int ver_temp[])
void set_ptvert (const Vertice *pointer)
void read_vertices (FILE *, const int &)
void set_sgn ()
int show_sgn (const int &ia, const int &i)
const int show_gbnmap (int ivar, int modo) const
int show_numv ()
int show_nume ()
int show_numf ()
void set_type (const int &num)
int type_val ()
void print_numeracao (FILE *fout, const int &k)
void print_modes (FILE *fout, const int &k) const
void zera_vetores (const int &k)
void zera_bs (const int &k)
void make_vector (const int &ia, double(*f)(double, double, double))
void make_vector_Elast2D_dyn (const double a[])
void make_Kcomp_Elast2D (const double lambda, const double mu)
void make_Kcomp_Elast2D_dyn (const double lambda, const double mu, const double a[])
void make_K_Elast2D (const double lambda, const double mu, double **K)
void VectorElast2D (const int &i, double sum[])
void VectorElast2D (double vector[])
void P_eval_print_Elast2D (FILE *fout, const double X[], double lambda, double mu)
void P_eval_print_Elast2D_dyn (FILE *fout, const int &prnflag, const double X[], double lambda, double mu, const double a[])
void make_K_Imiscivel2F (const double, const double, const double, const double, const double [], double(*)(double), double(*)(double), double(*)(double))
double Kcomp (const int &i, const int &j)
double K_Imisc2F (const int &i, const int &j)
void make_Vector_Eq_S1 (const double, const double, const double, const double, const double [3], double(*)(double))
int map (const int &var, const int &no_local)
void mapa_inverso (const int &ivar, const double X[])
void P_eval_u (const double X[])
void P_eval_u (const double X[], const int &ia)
void P_eval_u_p1 (const double X[], const int &ia)
void P_eval_print (const double X[], const int &numf, FILE *fout, double(*)(double, double, double))
void P_print (const int &numf, FILE *file)
void P_eval_vert (const double X[], double f_vert[])
void P_eval_phys (const int &numf, double f0[])
void Increment_field (const double X[], const int &numf, const double dt)
void compute_JV (const int &ia)
void print_matrices (FILE *fout)
void Processar_dados (int &NL, std::vector< ARESTA > &aresta, int &NF, std::vector< FACE > &face_vec)
void check_connectivity (FILE *fout, const int &ia)
void assign_gbnmap (const int &ia, const int &i, const int &val)
void inicia_gbnmap (int &count)
void inicia_gbnmap (const int &ivar, int &count)
void inicia_gbtrbmap (int &count)
void set_gbnmap (const int &ia, const int gbnmap_temp[], const int sgn_temp[])
void set_stgbtrbmap (const int &b, const int &vmapM, const int &vmapP)
int show_gbtrbmap ()
int show_stgbtrbmapM (const int &a)
int show_stgbtrbmapP (const int &a)
void check_gradiente (FILE *fout, const int &ia)
Stdel * show_ptr_stdel (const int &n) const
void BoundCond (const int &face, int bflag[], double bc[], double(*func)(double, double, double), const int &nf, const int &bndtype)
void Neumann (const int &aresta, const int &varn, const double rho1, const double mu1, const double rho2, const double mu2, const double gravidade[])
double show_u (const int &i)
double show_u (const int &, const int &)
double show_b0 (const int &i)
double show_b0 (const int &, const int &)
double show_bs (const int &, const int &)
double show_J ()
void make_MassMatrices ()
int show_Vert_map (int i)
int show_Aresta (int i)
int show_Face (int i)
int show_sinal (int i)
int show_border_num (int i)
int show_part_num ()
void set_part_num (const int &num=-1)
double Phi_val (const int &var, const int &ind, const int &pos)
void projetar_C0 (FILE *file, double(*func)(double, double, double), const int &ivar)
void transformacao_direta (double f[], const int &ivar)
void teste_transformacao_direta (FILE *fin, FILE *fout, const int &npoints, const double coord[])
void set_border_tipo (EDGE *border, const int &aresta, const int &t)
void set_border_num (const int &aresta, const int &num)
void Imprimir_valores (FILE *fileout, const int &npoints, const double coord[])
void printwGQJ (FILE *fileout)
void Avancar_u0 (const double X[], const double relax=1.0)
void Atualizar_u0 (const double X[])
void Copia_u0_em_ (double X[])
void Copia_u0_em_ (Teuchos::RCP< Epetra_Vector > X)
void Comparar_u0 (const double X[])
void Salvar_u0 ()
void Restaurar_u0 ()
void escrever_restart (FILE *fout)
void ler_restart (FILE *fin)
void ler_restart_buffer (FILE *fin, double *buff, int &count)
void restart_element (double *buff, int &count)
void teste_gradiente ()
int get_trace_border_map (const int &aresta)
void gbnmap_vertices (std::vector< std::vector< int >> gbn)
void gbnmap_vertices (int *gbn, const int &ivar)
void gbnmap_faces (const int face_vec[], const int &ivar)
void gbnmap_aresta (const int &aresta, const int &sinal, const int &ivar, const int &count, int &inc)
void gbnmap_arestas (const int aresta_vec[], const int &ivar)
void gbnmap_interior (const int &ivar, int &count)
void anexa_gbnmap (const int &ivar, vector< int > &)
void vetor_superficie (const int &num_local, double &area, double normal[3])
Protected Attributes
Stdel * ptr_stdel [NumVariaveis]
int type
const Vertice * ptvert
int NumLocalVars
int ndim
Spatial dimension.
int numv
Number of vertices.
int nume
Number of edges.
int numf
Number of faces.
int numborders
Number of borders in the element.
int numn [NumVariaveis]
int numb [NumVariaveis]
int Vert_map [8]
int aresta_map [12]
int face_map [6]
int border_num [12]
int sinal [12]
sinal refers to the borders
int part_num
numero da particao a qual pertence
int gbnmap [NumVariaveis][MAXNN]
mapping from local to global nodes (or modes)
int sgn [NumVariaveis][MAXNN]
sign of the local mode (or mode)
double J
Jacobian from the physical to the standard element.
double * JV
Ponteiro para matriz do Jacobiano nos pontos gaussianos;.
double * b0 [NumVariaveis]
[MAXMODES*MAXNFIELDS]; vector of body forces
double * bs [NumVariaveis]
vector of force boundary conditions
double * u0 [NumVariaveis]
vector with the coefficients of each mode
double * usave [NumVariaveis]
int gbtrbmap
Beginning index on the global array where the local border Gauss quadrature points (traces) are mapped; this map facilitates the use of mpi for paralell calculations over element borders.
int * stgbtrbmapM
Array containing the start point in the global trace array of the internal trace of the border.
int * stgbtrbmapP
Array containing the start point in the global trace array of the external trace of the border.
int vetores_iniciados
Private Attributes
double * sna
double * pwa
ponteiros para os valores nos pontos de Gauss da saturacao e pressao atuais
double rho
densidade de massa ou porosidade
double porosidade
double perm [3]
permeabilidades nas 3 direcoes
double qn
double qw
double Volume
Volume do elemento (= area do elemento para elementos bidimensionais e comprimento para elem. 1D.
double * Jb
Jacobiano nos pontos de Gauss sobre as bordas; usado na integração sobre bordas.
double ** Mass_sn
double ** Trsn
double ** Trpw
double *** LaplacianoPhi
double *** TrKgrad_sn
double *** TrKgrad_pw
double *** TrKgrad_pc
double **** TrPhi
double **** GradPhi
double **** TrKgradPhi_n
double ***** TrGradPhi
double * PhiArray
Detailed Description
Definition at line 19 of file DG_Elem.hpp.
Constructor & Destructor Documentation
DG_Elem()
DG_Elem::DG_Elem () [inline]
Definition at line 23 of file DG_Elem.hpp.
References rho, and PhElem< 2 >::vetores_iniciados.
 DG_Elem()
DG_Elem::~DG_Elem () [inline]
Definition at line 24 of file DG_Elem.hpp.
References inicia_vetores().
Member Function Documentation
anexa_gbnmap()
void PhElem< NumVariaveis >::anexa_gbnmap (const int & ivar, vector< int > & list) [inherited]
Definition at line 308 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, and PhElem< NumVariaveis >::numn.
assign_gbnmap()
void PhElem< NumVariaveis >::assign_gbnmap (const int & ia, const int & i, const int & val) [inherited]
Definition at line 830 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap.
Atualizar_u0()
void PhElem< NumVariaveis >::Atualizar_u0 (const double X[]) [inherited]
Definition at line 377 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
Atualizar_valores()
void DG_Elem::Atualizar_valores (FILE * fout = NULL)
Definition at line 15 of file DG_Elem.cpp.
References Stdel::evalGQ(), pres, Stdel::printGQtofile(), PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, pwa, sat, sna, PhElem< 2 >::u0, and PhElem< 2 >::Vert_map.
Referenced by DG_Prob::DG_initial_conditions(), and show_Volume().
Avancar_u0()
void PhElem< NumVariaveis >::Avancar_u0 (const double X[], const double relax = 1.0) [inherited]
Definition at line 342 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
BoundCond()
void PhElem< NumVariaveis >::BoundCond (const int & face, int bflag[], double bc[], double(*)(double, double, double) func, const int & nf, const int & bndtype) [inherited]
calcula_tracos()
void DG_Elem::calcula_tracos (Fluids fls)
Definition at line 222 of file DG_Elem.cpp.
References aux, aux1, Fluids::dpc(), PhElem< 2 >::ndim, PhElem< 2 >::numborders, PhElem< 2 >::numn, perm, pos, pres, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), sat, TrGradPhi, TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, TrPhi, Trpw, Trsn, and PhElem< 2 >::u0.
Referenced by show_Volume().
check_connectivity()
void PhElem< NumVariaveis >::check_connectivity (FILE * fout, const int & ia) [inherited]
Definition at line 800 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::ptr_stdel, and Stdel::show_ind().
check_gradiente()
void PhElem< NumVariaveis >::check_gradiente (FILE * fout, const int & ia) [inherited]
Definition at line 811 of file PhElem.hpp.
References Stdel::evalGQ(), Stdel::Gradiente(), PhElem< NumVariaveis >::ndim, Stdel::NGQP_val(), PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, sn, PhElem< NumVariaveis >::u0, and PhElem< NumVariaveis >::Vert_map.
Comparar_u0()
void PhElem< NumVariaveis >::Comparar_u0 (const double X[]) [inherited]
Definition at line 358 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
compute_JV()
void PhElem< NumVariaveis >::compute_JV (const int & ia) [inherited]
Definition at line 1376 of file PhElem.hpp.
References Stdel::Jacobian(), PhElem< NumVariaveis >::JV, Stdel::NGQP_val(), PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, and PhElem< NumVariaveis >::Vert_map.
Referenced by inicia_vetores().
Copia_u0_em_() [1/2]
void PhElem< NumVariaveis >::Copia_u0_em_ (double X[]) [inherited]
Definition at line 293 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
Copia_u0_em_() [2/2]
void PhElem< NumVariaveis >::Copia_u0_em_ (Teuchos::RCP< Epetra_Vector > X) [inherited]
Definition at line 300 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
echo_traco()
void DG_Elem::echo_traco (FILE * f_eco = nullptr)
Definition at line 309 of file DG_Elem.cpp.
References PhElem< 2 >::JV, PhElem< 2 >::ndim, Stdel::NGQP_val(), PhElem< 2 >::numborders, PhElem< 2 >::NumLocalVars, PhElem< 2 >::numn, pos, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, PhElem< 2 >::sinal, TrGradPhi, TrKgradPhi_n, and TrPhi.
Referenced by show_Volume().
escrever_restart()
void PhElem< NumVariaveis >::escrever_restart (FILE * fout) [inherited]
Definition at line 242 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
finaliza_vetores()
void DG_Elem::finaliza_vetores ()
Definition at line 1650 of file DG_Elem.cpp.
References GradPhi, Jb, PhElem< 2 >::JV, LaplacianoPhi, Mass_sn, PhElem< 2 >::ndim, PhElem< 2 >::numborders, PhElem< 2 >::numn, Stdel::P_val(), PhElem< 2 >::ptr_stdel, pwa, sna, PhElem< 2 >::stgbtrbmapM, PhElem< 2 >::stgbtrbmapP, TrGradPhi, TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, TrKgradPhi_n, TrPhi, Trpw, Trsn, PhElem< 2 >::u0, PhElem< 2 >::usave, and PhElem< 2 >::vetores_iniciados.
Referenced by show_Volume(), and DG_Prob::~DG_Prob().
gbnmap_aresta()
void PhElem< NumVariaveis >::gbnmap_aresta (const int & aresta, const int & sinal, const int & ivar, const int & count, int & inc) [inherited]
Definition at line 1719 of file PhElem.hpp.
References aux, PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::sgn, Stdel::show_emapi(), Stdel::show_emapv(), and PhElem< NumVariaveis >::sinal.
gbnmap_arestas()
void PhElem< NumVariaveis >::gbnmap_arestas (const int aresta_vec[], const int & ivar) [inherited]
Definition at line 1832 of file PhElem.hpp.
References a, Stdel::aresta_lvert(), PhElem< NumVariaveis >::aresta_map, aux, PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::nume, PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::sgn, Stdel::show_emapi(), Stdel::show_emapv(), PhElem< NumVariaveis >::sinal, and PhElem< NumVariaveis >::Vert_map.
gbnmap_faces()
void PhElem< NumVariaveis >::gbnmap_faces (const int face_vec[], const int & ivar) [inherited]
Definition at line 1754 of file PhElem.hpp.
References aux1, Stdel::face_lvert(), PhElem< NumVariaveis >::face_map, PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numf, Stdel::P_val(), PhElem< NumVariaveis >::ptr_stdel, quad_ordem(), PhElem< NumVariaveis >::sgn, Stdel::show_fd0(), Stdel::show_fd1(), Stdel::show_fv2(), Stdel::show_ind_mode(), Stdel::show_nvf(), PhElem< NumVariaveis >::sinal, and PhElem< NumVariaveis >::Vert_map.
gbnmap_interior()
void PhElem< NumVariaveis >::gbnmap_interior (const int & ivar, int & count) [inherited]
Definition at line 1742 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::sgn.
gbnmap_vertices() [1/2]
void PhElem< NumVariaveis >::gbnmap_vertices (std::vector< std::vector< int >> gbn) [inherited]
Definition at line 1696 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::gbnmap_vertices(), PhElem< NumVariaveis >::numv, PhElem< NumVariaveis >::sgn, and PhElem< NumVariaveis >::Vert_map.
gbnmap_vertices() [2/2]
void PhElem< NumVariaveis >::gbnmap_vertices (int * gbn, const int & ivar) [inherited]
get_trace_border_map()
int PhElem< NumVariaveis >::get_trace_border_map (const int & aresta) [inherited]
Definition at line 520 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbtrbmap, PhElem< NumVariaveis >::ptr_stdel, Stdel::qborder_val(), and qmax.
Imprimir_valores()
void PhElem< NumVariaveis >::Imprimir_valores (FILE * fileout, const int & npoints, const double coord[]) [inherited]
Increment_field()
void PhElem< NumVariaveis >::Increment_field (const double X[], const int & numf, const double dt) [inherited]
inicia_funcoes_na_borda()
void DG_Elem::inicia_funcoes_na_borda (EDGE * border)
Definition at line 44 of file DG_Elem.cpp.
References PhElem< 2 >::border_num, Stdel::elem_traces(), Stdel::eval_Phi(), Stdel::Gradiente(), GradPhi, Jb, LaplacianoPhi, n_e, PhElem< 2 >::ndim, Stdel::NGQP_val(), EDGE::normal, PhElem< 2 >::numborders, PhElem< 2 >::NumLocalVars, PhElem< 2 >::numn, perm, pos, PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, Stdel::qborder_val(), qmax, PhElem< 2 >::sinal, TrGradPhi, TrKgradPhi_n, TrPhi, and PhElem< 2 >::Vert_map.
Referenced by DG_Prob::DG_initial_conditions(), and show_Volume().
inicia_gbnmap() [1/2]
void PhElem< NumVariaveis >::inicia_gbnmap (int & count) [inherited]
Definition at line 838 of file PhElem.hpp.
References PhElem< NumVariaveis >::inicia_gbnmap().
inicia_gbnmap() [2/2]
void PhElem< NumVariaveis >::inicia_gbnmap (const int & ivar, int & count) [inherited]
Definition at line 846 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::sgn.
inicia_gbtrbmap()
void PhElem< NumVariaveis >::inicia_gbtrbmap (int & count) [inherited]
Definition at line 856 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbtrbmap, PhElem< NumVariaveis >::numborders, PhElem< NumVariaveis >::ptr_stdel, Stdel::qborder_val(), qmax, PhElem< NumVariaveis >::stgbtrbmapM, and PhElem< NumVariaveis >::stgbtrbmapP.
inicia_tracos()
void DG_Elem::inicia_tracos (EDGE * border)
Definition at line 158 of file DG_Elem.cpp.
References PhElem< 2 >::border_num, Stdel::eval_Phi(), Stdel::Gradiente(), GradPhi, n_e, PhElem< 2 >::ndim, Stdel::NGQP_val(), EDGE::normal, PhElem< 2 >::numborders, PhElem< 2 >::NumLocalVars, PhElem< 2 >::numn, perm, pos, PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, Stdel::qborder_val(), qmax, PhElem< 2 >::sinal, Stdel::trace(), TrGradPhi, TrKgradPhi_n, TrPhi, and PhElem< 2 >::Vert_map.
Referenced by show_Volume().
inicia_vetores()
void DG_Elem::inicia_vetores ()
Definition at line 1463 of file DG_Elem.cpp.
References PhElem< 2 >::compute_JV(), GradPhi, Jb, PhElem< 2 >::JV, LaplacianoPhi, Mass_sn, PhElem< 2 >::ndim, Stdel::NGQP_val(), PhElem< 2 >::numborders, PhElem< 2 >::NumLocalVars, PhElem< 2 >::numn, PhElem< 2 >::ptr_stdel, pwa, Stdel::qborder_val(), qmax, sna, TrGradPhi, TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, TrKgradPhi_n, TrPhi, Trpw, Trsn, PhElem< 2 >::u0, PhElem< 2 >::usave, and PhElem< 2 >::vetores_iniciados.
Referenced by DG_Prob::DG_initial_conditions(), DG_Prob::projetar_C0(), and ~DG_Elem().
K_Imisc2F()
double PhElem< NumVariaveis >::K_Imisc2F (const int & i, const int & j) [inherited]
Kcomp()
double PhElem< NumVariaveis >::Kcomp (const int & i, const int & j) [inherited]
Definition at line 183 of file Elastostatica.cpp.
References PhElem< NumVariaveis >::sgn.
ler_restart()
void PhElem< NumVariaveis >::ler_restart (FILE * fin) [inherited]
Definition at line 252 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
ler_restart_buffer()
void PhElem< NumVariaveis >::ler_restart_buffer (FILE * fin, double * buff, int & count) [inherited]
Definition at line 261 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn.
make_K_Elast2D()
void PhElem< NumVariaveis >::make_K_Elast2D (const double lambda, const double mu, double ** K) [inherited]
Definition at line 7 of file Elastostatica.cpp.
References aaux, aux, PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::JV, m, n0, and PhElem< NumVariaveis >::ptvert.
make_K_Imiscivel2F()
void PhElem< NumVariaveis >::make_K_Imiscivel2F (const double , const double , const double , const double , const double [], double(*)(double) , double(*)(double) , double(*)(double)) [inherited]
make_Kcomp_Elast2D()
void PhElem< NumVariaveis >::make_Kcomp_Elast2D (const double lambda, const double mu) [inherited]
Definition at line 197 of file Elastostatica.cpp.
References aux, B(), C(), e, force0(), PhElem< NumVariaveis >::make_K_Elast2D(), PhElem< NumVariaveis >::make_vector(), and n0.
make_Kcomp_Elast2D_dyn()
void PhElem< NumVariaveis >::make_Kcomp_Elast2D_dyn (const double lambda, const double mu, const double a[]) [inherited]
Definition at line 386 of file Elastodinamica2D.cpp.
References aux, and n0.
make_MassMatrices()
void PhElem< NumVariaveis >::make_MassMatrices () [inherited]
make_vector()
void PhElem< NumVariaveis >::make_vector (const int & ia, double(*)(double, double, double) f) [inherited]
make_vector_Elast2D_dyn()
void PhElem< NumVariaveis >::make_vector_Elast2D_dyn (const double a[]) [inherited]
Definition at line 369 of file Elastodinamica2D.cpp.
References aux.
make_Vector_Eq_S1()
void PhElem< NumVariaveis >::make_Vector_Eq_S1 (const double , const double , const double , const double , const double [3], double(*)(double)) [inherited]
map()
int PhElem< NumVariaveis >::map (const int & var, const int & no_local) [inherited]
Definition at line 573 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap.
mapa_inverso()
void PhElem< NumVariaveis >::mapa_inverso (const int & ivar, const double X[]) [inherited]
Definition at line 280 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
Neumann()
void PhElem< NumVariaveis >::Neumann (const int & aresta, const int & varn, const double rho1, const double mu1, const double rho2, const double mu2, const double gravidade[]) [inherited]
P_eval_phys()
void PhElem< NumVariaveis >::P_eval_phys (const int & numf, double f0[]) [inherited]
Definition at line 617 of file PhElem.hpp.
References Stdel::evalGQ(), PhElem< NumVariaveis >::numn, PhElem< NumVariaveis >::ptr_stdel, and PhElem< NumVariaveis >::u0.
P_eval_print()
void PhElem< NumVariaveis >::P_eval_print (const double X[], const int & numf, FILE * fout, double(*)(double, double, double)) [inherited]
P_eval_print_Elast2D()
void PhElem< NumVariaveis >::P_eval_print_Elast2D (FILE * fout, const double X[], double lambda, double mu) [inherited]
Definition at line 88 of file Elastostatica.cpp.
References PhElem< NumVariaveis >::b0, PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::map(), PhElem< NumVariaveis >::numf, PhElem< NumVariaveis >::ptvert, PhElem< NumVariaveis >::sgn, PhElem< NumVariaveis >::u0, and PhElem< NumVariaveis >::VectorElast2D().
P_eval_print_Elast2D_dyn()
void PhElem< NumVariaveis >::P_eval_print_Elast2D_dyn (FILE * fout, const int & prnflag, const double X[], double lambda, double mu, const double a[]) [inherited]
Definition at line 458 of file Elastodinamica2D.cpp.
P_eval_u() [1/2]
void PhElem< NumVariaveis >::P_eval_u (const double X[]) [inherited]
P_eval_u() [2/2]
void PhElem< NumVariaveis >::P_eval_u (const double X[], const int & ia) [inherited]
P_eval_u_p1()
void PhElem< NumVariaveis >::P_eval_u_p1 (const double X[], const int & ia) [inherited]
P_eval_vert()
void PhElem< NumVariaveis >::P_eval_vert (const double X[], double f_vert[]) [inherited]
P_print()
void PhElem< NumVariaveis >::P_print (const int & numf, FILE * file) [inherited]
Definition at line 631 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn, Stdel::printtofile(), PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, PhElem< NumVariaveis >::u0, and PhElem< NumVariaveis >::Vert_map.
perm_val()
void DG_Elem::perm_val (double K[3])
Definition at line 401 of file DG_Elem.cpp.
References perm.
Referenced by DG_Prob::DG_EI_IG(), and show_Volume().
Phi_val()
double PhElem< NumVariaveis >::Phi_val (const int & var, const int & ind, const int & pos) [inline], [inherited]
Definition at line 140 of file PhElem.hpp.
References PhElem< NumVariaveis >::anexa_gbnmap(), PhElem< NumVariaveis >::Atualizar_u0(), PhElem< NumVariaveis >::Avancar_u0(), PhElem< NumVariaveis >::Comparar_u0(), PhElem< NumVariaveis >::Copia_u0_em_(), PhElem< NumVariaveis >::escrever_restart(), PhElem< NumVariaveis >::gbnmap_aresta(), PhElem< NumVariaveis >::gbnmap_arestas(), PhElem< NumVariaveis >::gbnmap_faces(), PhElem< NumVariaveis >::gbnmap_interior(), PhElem< NumVariaveis >::gbnmap_vertices(), PhElem< NumVariaveis >::get_trace_border_map(), PhElem< NumVariaveis >::Imprimir_valores(), PhElem< NumVariaveis >::ler_restart(), PhElem< NumVariaveis >::ler_restart_buffer(), PhElem< NumVariaveis >::printwGQJ(), PhElem< NumVariaveis >::projetar_C0(), PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::restart_element(), PhElem< NumVariaveis >::Restaurar_u0(), PhElem< NumVariaveis >::Salvar_u0(), PhElem< NumVariaveis >::set_border_num(), PhElem< NumVariaveis >::set_border_tipo(), Stdel::show_Phi_val(), PhElem< NumVariaveis >::sinal, PhElem< NumVariaveis >::teste_gradiente(), PhElem< NumVariaveis >::teste_transformacao_direta(), PhElem< NumVariaveis >::transformacao_direta(), and PhElem< NumVariaveis >::vetor_superficie().
print_matrices()
void PhElem< NumVariaveis >::print_matrices (FILE * fout) [inherited]
print_modes()
void PhElem< NumVariaveis >::print_modes (FILE * fout, const int & k) const [inherited]
Definition at line 551 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, Stdel::nv_val(), and PhElem< NumVariaveis >::ptr_stdel.
print_numeracao()
void PhElem< NumVariaveis >::print_numeracao (FILE * fout, const int & k) [inherited]
Definition at line 541 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, and PhElem< NumVariaveis >::numb.
printwGQJ()
void PhElem< NumVariaveis >::printwGQJ (FILE * fileout) [inherited]
Definition at line 316 of file PhElem.hpp.
References PhElem< NumVariaveis >::JV, Stdel::printwGQtofile(), PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, and PhElem< NumVariaveis >::Vert_map.
Processar_dados()
void PhElem< NumVariaveis >::Processar_dados (int & NL, std::vector< ARESTA > & aresta, int & NF, std::vector< FACE > & face_vec) [inherited]
Definition at line 682 of file PhElem.hpp.
References aresta_gbnum(), Stdel::aresta_lvert(), PhElem< NumVariaveis >::aresta_map, face_gbnum(), Stdel::face_lvert(), PhElem< NumVariaveis >::face_map, n0, Stdel::nborder_val(), PhElem< NumVariaveis >::ndim, Stdel::ndim_val(), Stdel::ne_val(), Stdel::nf_val(), PhElem< NumVariaveis >::numborders, PhElem< NumVariaveis >::nume, PhElem< NumVariaveis >::numf, PhElem< NumVariaveis >::numv, Stdel::nv_val(), PhElem< NumVariaveis >::ptr_stdel, Stdel::show_face_tipo(), Stdel::show_nvf(), PhElem< NumVariaveis >::sinal, and PhElem< NumVariaveis >::Vert_map.
projetar_C0()
void PhElem< NumVariaveis >::projetar_C0 (FILE * file, double(*)(double, double, double) func, const int & ivar) [inherited]
Definition at line 880 of file PhElem.hpp.
References aux, B(), Stdel::computeFuncGQ(), Stdel::Dirichlet(), Stdel::eval_Phi(), PhElem< NumVariaveis >::JV, Stdel::mass(), Stdel::NGQP_val(), PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::numborders, PhElem< NumVariaveis >::numn, Stdel::printtofile(), PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, PhElem< NumVariaveis >::sgn, PhElem< NumVariaveis >::u0, Stdel::vector_of_integral_of_f_Phi_dv(), and PhElem< NumVariaveis >::Vert_map.
read_vertices()
void PhElem< NumVariaveis >::read_vertices (FILE * finput, const int & nv) [inherited]
Definition at line 563 of file PhElem.hpp.
References PhElem< NumVariaveis >::Vert_map.
restart_element()
void PhElem< NumVariaveis >::restart_element (double * buff, int & count) [inherited]
Definition at line 270 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::u0.
Restaurar_u0()
void PhElem< NumVariaveis >::Restaurar_u0 () [inherited]
Definition at line 333 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn, PhElem< NumVariaveis >::u0, and PhElem< NumVariaveis >::usave.
Salvar_u0()
void PhElem< NumVariaveis >::Salvar_u0 () [inherited]
Definition at line 325 of file PhElem.hpp.
References PhElem< NumVariaveis >::numn, PhElem< NumVariaveis >::u0, and PhElem< NumVariaveis >::usave.
set_border_num()
void PhElem< NumVariaveis >::set_border_num (const int & aresta, const int & num) [inherited]
Definition at line 514 of file PhElem.hpp.
References PhElem< NumVariaveis >::border_num.
set_border_tipo()
void PhElem< NumVariaveis >::set_border_tipo (EDGE * border, const int & aresta, const int & t) [inherited]
Definition at line 503 of file PhElem.hpp.
References PhElem< NumVariaveis >::border_num, and EDGE::tipo.
set_fontes()
void DG_Elem::set_fontes (double sw, double sn) [inline]
Definition at line 27 of file DG_Elem.hpp.
References qn, qw, and sn.
Referenced by DG_Prob::DG_initial_conditions(), and DG_Prob::projetar_C0().
set_gbnmap()
void PhElem< NumVariaveis >::set_gbnmap (const int & ia, const int gbnmap_temp[], const int sgn_temp[]) [inherited]
Definition at line 789 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::sgn.
set_mass_density()
void DG_Elem::set_mass_density (double value)
Definition at line 38 of file DG_Elem.cpp.
References rho.
Referenced by show_Volume().
set_part_num()
void PhElem< NumVariaveis >::set_part_num (const int & num = -1) [inherited]
Definition at line 1406 of file PhElem.hpp.
References PhElem< NumVariaveis >::numv, Vertice::part_num, PhElem< NumVariaveis >::part_num, PhElem< NumVariaveis >::ptvert, and PhElem< NumVariaveis >::Vert_map.
set_permeabilidade()
void DG_Elem::set_permeabilidade (const double x, const double y, const double z)
Definition at line 30 of file DG_Elem.cpp.
References perm.
Referenced by DG_Prob::DG_initial_conditions(), DG_Prob::projetar_C0(), and show_Volume().
set_porosidade()
void DG_Elem::set_porosidade (double value)
Definition at line 152 of file DG_Elem.cpp.
References porosidade.
Referenced by DG_Prob::DG_initial_conditions(), DG_Prob::projetar_C0(), and show_Volume().
set_ptr_stdel() [1/3]
void PhElem< NumVariaveis >::set_ptr_stdel (Stdel * pointer, Stdel * pointer1) [inherited]
Definition at line 460 of file PhElem.hpp.
References Stdel::nb_val(), Stdel::nn_val(), PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::ptr_stdel.
set_ptr_stdel() [2/3]
void PhElem< NumVariaveis >::set_ptr_stdel (Stdel * pointers[]) [inherited]
Definition at line 482 of file PhElem.hpp.
References Stdel::nb_val(), Stdel::nn_val(), PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::ptr_stdel.
set_ptr_stdel() [3/3]
void PhElem< NumVariaveis >::set_ptr_stdel (Stdel * pointer) [inherited]
Definition at line 452 of file PhElem.hpp.
References Stdel::nb_val(), Stdel::nn_val(), PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::ptr_stdel.
set_ptr_stdel_var()
void PhElem< NumVariaveis >::set_ptr_stdel_var (const int ind, Stdel * pointer) [inherited]
Definition at line 474 of file PhElem.hpp.
References Stdel::nb_val(), Stdel::nn_val(), PhElem< NumVariaveis >::numb, PhElem< NumVariaveis >::numn, and PhElem< NumVariaveis >::ptr_stdel.
set_ptvert()
void PhElem< NumVariaveis >::set_ptvert (const Vertice * pointer) [inherited]
Definition at line 493 of file PhElem.hpp.
References PhElem< NumVariaveis >::ptvert.
set_sgn()
void PhElem< NumVariaveis >::set_sgn () [inherited]
set_stgbtrbmap()
void PhElem< NumVariaveis >::set_stgbtrbmap (const int & b, const int & vmapM, const int & vmapP) [inherited]
Definition at line 870 of file PhElem.hpp.
References PhElem< NumVariaveis >::stgbtrbmapM, and PhElem< NumVariaveis >::stgbtrbmapP.
set_type()
void PhElem< NumVariaveis >::set_type (const int & num) [inherited]
Definition at line 529 of file PhElem.hpp.
References PhElem< NumVariaveis >::type.
set_Vert_map()
void PhElem< NumVariaveis >::set_Vert_map (const int & n_in, int ver_temp[]) [inherited]
Definition at line 774 of file PhElem.hpp.
References PhElem< NumVariaveis >::numv, PhElem< NumVariaveis >::type, and PhElem< NumVariaveis >::Vert_map.
show_Aresta()
int PhElem< NumVariaveis >::show_Aresta (int i) [inline], [inherited]
Definition at line 133 of file PhElem.hpp.
References PhElem< NumVariaveis >::aresta_map.
show_b0() [1/2]
double PhElem< NumVariaveis >::show_b0 (const int & i) [inherited]
show_b0() [2/2]
double PhElem< NumVariaveis >::show_b0 (const int & var, const int & no) [inherited]
Definition at line 602 of file PhElem.hpp.
References PhElem< NumVariaveis >::b0.
show_border_num()
int PhElem< NumVariaveis >::show_border_num (int i) [inline], [inherited]
Definition at line 136 of file PhElem.hpp.
References PhElem< NumVariaveis >::border_num.
show_bs()
double PhElem< NumVariaveis >::show_bs (const int & var, const int & no) [inherited]
Definition at line 609 of file PhElem.hpp.
References PhElem< NumVariaveis >::bs.
show_Face()
int PhElem< NumVariaveis >::show_Face (int i) [inline], [inherited]
Definition at line 134 of file PhElem.hpp.
References PhElem< NumVariaveis >::face_map.
show_gbnmap()
const int PhElem< NumVariaveis >::show_gbnmap (int ivar, int modo) const [inline], [inherited]
Definition at line 39 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbnmap.
show_gbtrbmap()
int PhElem< NumVariaveis >::show_gbtrbmap () [inline], [inherited]
Definition at line 105 of file PhElem.hpp.
References PhElem< NumVariaveis >::gbtrbmap.
show_J()
double PhElem< NumVariaveis >::show_J () [inline], [inherited]
Definition at line 129 of file PhElem.hpp.
References PhElem< NumVariaveis >::J, and PhElem< NumVariaveis >::make_MassMatrices().
show_nume()
int PhElem< NumVariaveis >::show_nume () [inline], [inherited]
Definition at line 41 of file PhElem.hpp.
References PhElem< NumVariaveis >::nume.
show_numf()
int PhElem< NumVariaveis >::show_numf () [inline], [inherited]
Definition at line 42 of file PhElem.hpp.
References a, PhElem< NumVariaveis >::assign_gbnmap(), PhElem< NumVariaveis >::check_connectivity(), PhElem< NumVariaveis >::compute_JV(), PhElem< NumVariaveis >::Increment_field(), PhElem< NumVariaveis >::inicia_gbnmap(), PhElem< NumVariaveis >::inicia_gbtrbmap(), PhElem< NumVariaveis >::K_Imisc2F(), PhElem< NumVariaveis >::Kcomp(), PhElem< NumVariaveis >::make_K_Elast2D(), PhElem< NumVariaveis >::make_K_Imiscivel2F(), PhElem< NumVariaveis >::make_Kcomp_Elast2D(), PhElem< NumVariaveis >::make_Kcomp_Elast2D_dyn(), PhElem< NumVariaveis >::make_vector(), PhElem< NumVariaveis >::make_vector_Elast2D_dyn(), PhElem< NumVariaveis >::make_Vector_Eq_S1(), PhElem< NumVariaveis >::map(), PhElem< NumVariaveis >::mapa_inverso(), PhElem< NumVariaveis >::numf, PhElem< NumVariaveis >::P_eval_phys(), PhElem< NumVariaveis >::P_eval_print(), PhElem< NumVariaveis >::P_eval_print_Elast2D(), PhElem< NumVariaveis >::P_eval_print_Elast2D_dyn(), PhElem< NumVariaveis >::P_eval_u(), PhElem< NumVariaveis >::P_eval_u_p1(), PhElem< NumVariaveis >::P_eval_vert(), PhElem< NumVariaveis >::P_print(), PhElem< NumVariaveis >::print_matrices(), PhElem< NumVariaveis >::print_modes(), PhElem< NumVariaveis >::print_numeracao(), PhElem< NumVariaveis >::Processar_dados(), PhElem< NumVariaveis >::set_gbnmap(), PhElem< NumVariaveis >::set_stgbtrbmap(), PhElem< NumVariaveis >::set_type(), PhElem< NumVariaveis >::type_val(), PhElem< NumVariaveis >::VectorElast2D(), PhElem< NumVariaveis >::zera_bs(), and PhElem< NumVariaveis >::zera_vetores().
show_NumLocalVars()
int PhElem< NumVariaveis >::show_NumLocalVars () [inline], [inherited]
Definition at line 28 of file PhElem.hpp.
References PhElem< NumVariaveis >::NumLocalVars, PhElem< NumVariaveis >::read_vertices(), PhElem< NumVariaveis >::set_ptr_stdel(), PhElem< NumVariaveis >::set_ptr_stdel_var(), PhElem< NumVariaveis >::set_ptvert(), PhElem< NumVariaveis >::set_sgn(), PhElem< NumVariaveis >::set_Vert_map(), and PhElem< NumVariaveis >::teste().
show_numv()
int PhElem< NumVariaveis >::show_numv () [inline], [inherited]
Definition at line 40 of file PhElem.hpp.
References PhElem< NumVariaveis >::numv.
show_part_num()
int PhElem< NumVariaveis >::show_part_num () [inline], [inherited]
Definition at line 137 of file PhElem.hpp.
References PhElem< NumVariaveis >::part_num, and PhElem< NumVariaveis >::set_part_num().
show_ptr_stdel()
Stdel * PhElem< NumVariaveis >::show_ptr_stdel (const int & n) const [inherited]
Definition at line 588 of file PhElem.hpp.
References PhElem< NumVariaveis >::ptr_stdel.
show_rho()
double DG_Elem::show_rho () [inline]
Definition at line 28 of file DG_Elem.hpp.
References rho.
show_sgn()
int PhElem< NumVariaveis >::show_sgn (const int & ia, const int & i) [inline], [inherited]
Definition at line 38 of file PhElem.hpp.
References PhElem< NumVariaveis >::sgn.
show_sinal()
int PhElem< NumVariaveis >::show_sinal (int i) [inline], [inherited]
Definition at line 135 of file PhElem.hpp.
References PhElem< NumVariaveis >::sinal.
show_stgbtrbmapM()
int PhElem< NumVariaveis >::show_stgbtrbmapM (const int & a) [inline], [inherited]
Definition at line 106 of file PhElem.hpp.
References PhElem< NumVariaveis >::stgbtrbmapM.
show_stgbtrbmapP()
int PhElem< NumVariaveis >::show_stgbtrbmapP (const int & a) [inline], [inherited]
Definition at line 107 of file PhElem.hpp.
References PhElem< NumVariaveis >::BoundCond(), PhElem< NumVariaveis >::check_gradiente(), PhElem< NumVariaveis >::Neumann(), PhElem< NumVariaveis >::show_b0(), PhElem< NumVariaveis >::show_bs(), PhElem< NumVariaveis >::show_ptr_stdel(), PhElem< NumVariaveis >::show_u(), and PhElem< NumVariaveis >::stgbtrbmapP.
show_u() [1/2]
double PhElem< NumVariaveis >::show_u (const int & i) [inherited]
show_u() [2/2]
double PhElem< NumVariaveis >::show_u (const int & var, const int & no) [inherited]
Definition at line 595 of file PhElem.hpp.
References PhElem< NumVariaveis >::u0.
show_Vert_map()
int PhElem< NumVariaveis >::show_Vert_map (int i) [inline], [inherited]
Definition at line 132 of file PhElem.hpp.
References PhElem< NumVariaveis >::Vert_map.
show_Volume()
double DG_Elem::show_Volume () [inline]
Definition at line 29 of file DG_Elem.hpp.
References Atualizar_valores(), B(), calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), perm_val(), set_mass_density(), set_permeabilidade(), set_porosidade(), Traco_Kgrad_pc(), Traco_Kgrad_pw(), Traco_Kgrad_sn(), Traco_phi(), Traco_pw(), Traco_sn(), Volume, VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), VolumeIntegralsT(), and VolumeTracos().
teste()
void PhElem< NumVariaveis >::teste () [inherited]
Definition at line 189 of file Elastostatica.cpp.
teste_gradiente()
void PhElem< NumVariaveis >::teste_gradiente () [inherited]
Definition at line 1426 of file PhElem.hpp.
References aux, e, Stdel::eval_GradPhi(), Stdel::eval_Phi(), Stdel::Gradiente(), PhElem< NumVariaveis >::ndim, Stdel::NGQP_val(), PhElem< NumVariaveis >::numn, PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, and PhElem< NumVariaveis >::Vert_map.
teste_transformacao_direta()
void PhElem< NumVariaveis >::teste_transformacao_direta (FILE * fin, FILE * fout, const int & npoints, const double coord[]) [inherited]
Traco_grad_phi()
void DG_Elem::Traco_grad_phi (const int & lado, const int & ivar, const int & ind, double ** saida)
Definition at line 472 of file DG_Elem.cpp.
References PhElem< 2 >::ndim, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and TrGradPhi.
Referenced by Traco_phi_1().
Traco_Kgrad_pc()
void DG_Elem::Traco_Kgrad_pc (const int & h, double ** saida)
Definition at line 432 of file DG_Elem.cpp.
References PhElem< 2 >::ndim, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and TrKgrad_pc.
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), for(), and show_Volume().
Traco_Kgrad_phi_n()
void DG_Elem::Traco_Kgrad_phi_n (const int & lado, const int & ivar, const int & ind, double * saida)
Definition at line 483 of file DG_Elem.cpp.
References PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and TrKgradPhi_n.
Referenced by DG_Prob::DG_EI_IG(), for(), and Traco_phi_1().
Traco_Kgrad_pw()
void DG_Elem::Traco_Kgrad_pw (const int & h, double ** saida)
Definition at line 422 of file DG_Elem.cpp.
References PhElem< 2 >::ndim, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and TrKgrad_pw.
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), for(), and show_Volume().
Traco_Kgrad_sn()
void DG_Elem::Traco_Kgrad_sn (const int & h, double ** saida)
Definition at line 442 of file DG_Elem.cpp.
References PhElem< 2 >::ndim, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and TrKgrad_sn.
Referenced by DG_Prob::DG_EI_IG(), for(), and show_Volume().
Traco_phi()
void DG_Elem::Traco_phi (const int & lado, const int & ivar, const int & ind, double * saida)
Definition at line 454 of file DG_Elem.cpp.
References pos, PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and TrPhi.
Referenced by DG_Prob::DG_EI_IG(), and show_Volume().
Traco_phi_1()
void DG_Elem::Traco_phi_1 (const int & lado, const int & ivar, const int & pos, double * saida) [inline]
Definition at line 81 of file DG_Elem.hpp.
References PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, Traco_grad_phi(), Traco_Kgrad_phi_n(), and TrPhi.
Referenced by DG_Prob::DG_EI_Inflow(), DG_Prob::DG_EI_Interior(), and DG_Prob::DG_EI_Outflow().
Traco_pw()
void DG_Elem::Traco_pw (const int & h, double * saida)
Definition at line 415 of file DG_Elem.cpp.
References PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and Trpw.
Referenced by DG_Prob::DG_EI_IG(), and show_Volume().
Traco_sn()
void DG_Elem::Traco_sn (const int & h, double * saida)
Definition at line 408 of file DG_Elem.cpp.
References PhElem< 2 >::ptr_stdel, Stdel::qborder_val(), qmax, and Trsn.
Referenced by DG_Prob::DG_EI_IG(), and show_Volume().
transformacao_direta()
void PhElem< NumVariaveis >::transformacao_direta (double f[], const int & ivar) [inherited]
Definition at line 980 of file PhElem.hpp.
References aux, B(), PhElem< NumVariaveis >::JV, Stdel::mass(), PhElem< NumVariaveis >::numn, PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::u0, and Stdel::vector_of_integral_of_f_Phi_dv().
type_val()
int PhElem< NumVariaveis >::type_val () [inherited]
Definition at line 535 of file PhElem.hpp.
References PhElem< NumVariaveis >::type.
VectorElast2D() [1/2]
void PhElem< NumVariaveis >::VectorElast2D (const int & i, double sum[]) [inherited]
VectorElast2D() [2/2]
void PhElem< NumVariaveis >::VectorElast2D (double vector[]) [inherited]
Definition at line 161 of file Elastostatica.cpp.
References PhElem< NumVariaveis >::b0, and PhElem< NumVariaveis >::sgn.
vetor_superficie()
void PhElem< NumVariaveis >::vetor_superficie (const int & num_local, double & area, double normal[3]) [inherited]
Definition at line 1487 of file PhElem.hpp.
References PhElem< NumVariaveis >::ptr_stdel, PhElem< NumVariaveis >::ptvert, Stdel::superficie_externa(), and PhElem< NumVariaveis >::Vert_map.
VolumeIntegrals()
void DG_Elem::VolumeIntegrals (const double Dt, Fluids fls, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS, double * gbtrsn = NULL, double * gbtrpw = NULL)
Definition at line 1124 of file DG_Elem.cpp.
References aaux, aux, B(), d2_pc, Fluids::d2pc(), d_lambdan, d_lambdat, d_lambdaw, d_pc, Fluids::dkrn(), Fluids::dkrw(), Fluids::dpc(), Stdel::eval_Phi(), Stdel::evalGQ(), PhElem< 2 >::gbnmap, PhElem< 2 >::gbtrbmap, Stdel::Gradiente(), GradPhi, indice(), integral(), PhElem< 2 >::JV, Fluids::Krn(), Fluids::Krw(), lambdan, lambdat, lambdaw, m, mun, muw, n0, PhElem< 2 >::ndim, Stdel::NGQP_val(), npos(), PhElem< 2 >::numborders, PhElem< 2 >::numn, pc, perm, phi_l, phi_r, porosidade, pres, Fluids::pressao_capilar(), PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, pw, Stdel::qborder_val(), qmax, qn, qw, sat, Fluids::show_mun(), Fluids::show_muw(), PhElem< 2 >::sinal, sn, sna, Stdel::trace(), TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, Trpw, Trsn, PhElem< 2 >::u0, and PhElem< 2 >::Vert_map.
Referenced by DG_Prob::DG_MatrizVetor_Epetra(), and show_Volume().
VolumeIntegrals_IG()
void DG_Elem::VolumeIntegrals_IG (Fluids fls, int & count, int * Ti, int * Tj, double * Tx, double * B)
Definition at line 492 of file DG_Elem.cpp.
References aux, d2_pc, Fluids::d2pc(), d_lambdan, d_lambdat, d_lambdaw, d_pc, Fluids::dkrn(), Fluids::dkrw(), Fluids::dpc(), Stdel::evalGQ(), PhElem< 2 >::gbnmap, Stdel::Gradiente(), GradPhi, integral(), PhElem< 2 >::JV, Fluids::Krn(), Fluids::Krw(), lambdan, lambdat, lambdaw, m, mun, muw, PhElem< 2 >::ndim, Stdel::NGQP_val(), PhElem< 2 >::numborders, PhElem< 2 >::numn, pc, perm, pres, Fluids::pressao_capilar(), prodev(), prodvv(), PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, pw, Stdel::qborder_val(), qmax, sat, Fluids::show_mun(), Fluids::show_muw(), PhElem< 2 >::sinal, sn, somavv(), Stdel::trace(), TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, Trpw, Trsn, PhElem< 2 >::u0, and PhElem< 2 >::Vert_map.
Referenced by DG_Prob::DG_initial_conditions(), and show_Volume().
VolumeIntegrals_UMFPACK()
void DG_Elem::VolumeIntegrals_UMFPACK (const double Dt, Fluids fls, int & count, int * Ti, int * Tj, double * Tx, double * B, double * gbtrsn = NULL, double * gbtrpw = NULL)
Definition at line 635 of file DG_Elem.cpp.
References aaux, aux, d2_pc, Fluids::d2pc(), d_lambdan, d_lambdat, d_lambdaw, d_pc, Fluids::dkrn(), Fluids::dkrw(), Fluids::dpc(), Stdel::eval_Phi(), Stdel::evalGQ(), PhElem< 2 >::gbnmap, PhElem< 2 >::gbtrbmap, Stdel::Gradiente(), GradPhi, indice(), integral(), PhElem< 2 >::JV, Fluids::Krn(), Fluids::Krw(), lambdan, lambdat, lambdaw, m, mun, muw, n0, PhElem< 2 >::ndim, Stdel::NGQP_val(), npos(), PhElem< 2 >::numborders, PhElem< 2 >::numn, pc, perm, phi_l, phi_r, porosidade, pres, Fluids::pressao_capilar(), PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, pw, Stdel::qborder_val(), qmax, qn, qw, sat, Fluids::show_mun(), Fluids::show_muw(), PhElem< 2 >::sinal, sn, sna, Stdel::trace(), TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, Trpw, Trsn, PhElem< 2 >::u0, and PhElem< 2 >::Vert_map.
Referenced by DG_Prob::DG_MatrizVetor_UMFPACK(), and show_Volume().
VolumeIntegralsT()
void DG_Elem::VolumeIntegralsT (const double Dt_new, const double Dt_old, int & count, int * Ti, int * Tj, double * Tx, double * B)
Definition at line 960 of file DG_Elem.cpp.
References aux, Stdel::eval_Phi(), Stdel::evalGQ(), PhElem< 2 >::gbnmap, PhElem< 2 >::JV, m, Mass_sn, Stdel::NGQP_val(), PhElem< 2 >::numn, phi_r, porosidade, PhElem< 2 >::ptr_stdel, sat, sn, sna, and PhElem< 2 >::u0.
Referenced by show_Volume().
VolumeTracos()
void DG_Elem::VolumeTracos (const double Dt, Fluids fls, double * gbtrsn = NULL, double * gbtrpw = NULL)
Definition at line 1024 of file DG_Elem.cpp.
References aux, d2_pc, Fluids::d2pc(), d_lambdan, d_lambdat, d_lambdaw, d_pc, Fluids::dkrn(), Fluids::dkrw(), Fluids::dpc(), Stdel::evalGQ(), PhElem< 2 >::gbtrbmap, Stdel::Gradiente(), PhElem< 2 >::JV, Fluids::Krn(), Fluids::Krw(), lambdan, lambdat, lambdaw, m, mun, muw, PhElem< 2 >::ndim, Stdel::NGQP_val(), PhElem< 2 >::numborders, pc, perm, pres, Fluids::pressao_capilar(), PhElem< 2 >::ptr_stdel, PhElem< 2 >::ptvert, pw, Stdel::qborder_val(), qmax, sat, Fluids::show_mun(), Fluids::show_muw(), PhElem< 2 >::sinal, sn, Stdel::trace(), TrKgrad_pc, TrKgrad_pw, TrKgrad_sn, Trpw, Trsn, PhElem< 2 >::u0, and PhElem< 2 >::Vert_map.
Referenced by DG_Prob::DG_imprimir_taxas_de_producao(), DG_Prob::DG_MatrizVetor_Epetra(), DG_Prob::DG_MatrizVetor_UMFPACK(), and show_Volume().
zera_bs()
void PhElem< NumVariaveis >::zera_bs (const int & k) [inherited]
zera_vetores()
void PhElem< NumVariaveis >::zera_vetores (const int & k) [inherited]
Member Data Documentation
aresta_map
int PhElem< NumVariaveis >::aresta_map[12] [protected], [inherited]
Definition at line 195 of file PhElem.hpp.
b0
double* PhElem< NumVariaveis >::b0[NumVariaveis] [protected], [inherited]
[MAXMODES*MAXNFIELDS]; vector of body forces
Definition at line 201 of file PhElem.hpp.
border_num
int PhElem< NumVariaveis >::border_num[12] [protected], [inherited]
Definition at line 195 of file PhElem.hpp.
Referenced by inicia_funcoes_na_borda(), and inicia_tracos().
bs
double* PhElem< NumVariaveis >::bs[NumVariaveis] [protected], [inherited]
vector of force boundary conditions
Definition at line 202 of file PhElem.hpp.
face_map
int PhElem< NumVariaveis >::face_map[6] [protected], [inherited]
Definition at line 195 of file PhElem.hpp.
gbnmap
int PhElem< NumVariaveis >::gbnmap[NumVariaveis][MAXNN] [protected], [inherited]
mapping from local to global nodes (or modes)
Definition at line 197 of file PhElem.hpp.
Referenced by VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeIntegralsT().
gbtrbmap
int PhElem< NumVariaveis >::gbtrbmap [protected], [inherited]
Beginning index on the global array where the local border Gauss quadrature points (traces) are mapped; this map facilitates the use of mpi for paralell calculations over element borders.
Definition at line 207 of file PhElem.hpp.
Referenced by VolumeIntegrals(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
GradPhi
double**** DG_Elem::GradPhi [private]
Definition at line 124 of file DG_Elem.hpp.
Referenced by finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), VolumeIntegrals(), VolumeIntegrals_IG(), and VolumeIntegrals_UMFPACK().
J
double PhElem< NumVariaveis >::J [protected], [inherited]
Jacobian from the physical to the standard element.
Definition at line 199 of file PhElem.hpp.
Jb
double* DG_Elem::Jb [private]
Jacobiano nos pontos de Gauss sobre as bordas; usado na integração sobre bordas.
Definition at line 115 of file DG_Elem.hpp.
Referenced by finaliza_vetores(), inicia_funcoes_na_borda(), and inicia_vetores().
JV
double* PhElem< NumVariaveis >::JV [protected], [inherited]
Ponteiro para matriz do Jacobiano nos pontos gaussianos;.
Definition at line 200 of file PhElem.hpp.
Referenced by echo_traco(), finaliza_vetores(), inicia_vetores(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), VolumeIntegralsT(), and VolumeTracos().
LaplacianoPhi
double*** DG_Elem::LaplacianoPhi [private]
Definition at line 119 of file DG_Elem.hpp.
Referenced by finaliza_vetores(), inicia_funcoes_na_borda(), and inicia_vetores().
Mass_sn
double** DG_Elem::Mass_sn [private]
Definition at line 116 of file DG_Elem.hpp.
Referenced by finaliza_vetores(), inicia_vetores(), and VolumeIntegralsT().
ndim
int PhElem< NumVariaveis >::ndim [protected], [inherited]
Spatial dimension.
Definition at line 188 of file PhElem.hpp.
Referenced by calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), Traco_grad_phi(), Traco_Kgrad_pc(), Traco_Kgrad_pw(), Traco_Kgrad_sn(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
numb
int PhElem< NumVariaveis >::numb[NumVariaveis] [protected], [inherited]
Definition at line 194 of file PhElem.hpp.
numborders
int PhElem< NumVariaveis >::numborders [protected], [inherited]
Number of borders in the element.
Definition at line 192 of file PhElem.hpp.
Referenced by calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
nume
int PhElem< NumVariaveis >::nume [protected], [inherited]
Number of edges.
Definition at line 190 of file PhElem.hpp.
numf
int PhElem< NumVariaveis >::numf [protected], [inherited]
Number of faces.
Definition at line 191 of file PhElem.hpp.
NumLocalVars
int PhElem< NumVariaveis >::NumLocalVars [protected], [inherited]
Definition at line 187 of file PhElem.hpp.
Referenced by echo_traco(), inicia_funcoes_na_borda(), inicia_tracos(), and inicia_vetores().
numn
int PhElem< NumVariaveis >::numn[NumVariaveis] [protected], [inherited]
Definition at line 193 of file PhElem.hpp.
Referenced by calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeIntegralsT().
numv
int PhElem< NumVariaveis >::numv [protected], [inherited]
Number of vertices.
Definition at line 189 of file PhElem.hpp.
part_num
int PhElem< NumVariaveis >::part_num [protected], [inherited]
numero da particao a qual pertence
Definition at line 196 of file PhElem.hpp.
perm
double DG_Elem::perm[3] [private]
permeabilidades nas 3 direcoes
Definition at line 111 of file DG_Elem.hpp.
Referenced by calcula_tracos(), inicia_funcoes_na_borda(), inicia_tracos(), perm_val(), set_permeabilidade(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
PhiArray
double* DG_Elem::PhiArray [private]
Definition at line 127 of file DG_Elem.hpp.
porosidade
double DG_Elem::porosidade [private]
Definition at line 110 of file DG_Elem.hpp.
Referenced by set_porosidade(), VolumeIntegrals(), VolumeIntegrals_UMFPACK(), and VolumeIntegralsT().
ptr_stdel
Stdel* PhElem< NumVariaveis >::ptr_stdel[NumVariaveis] [protected], [inherited]
Definition at line 184 of file PhElem.hpp.
Referenced by Atualizar_valores(), calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), Traco_grad_phi(), Traco_Kgrad_pc(), Traco_Kgrad_phi_n(), Traco_Kgrad_pw(), Traco_Kgrad_sn(), Traco_phi(), Traco_phi_1(), Traco_pw(), Traco_sn(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), VolumeIntegralsT(), and VolumeTracos().
ptvert
const Vertice* PhElem< NumVariaveis >::ptvert [protected], [inherited]
Definition at line 186 of file PhElem.hpp.
Referenced by Atualizar_valores(), inicia_funcoes_na_borda(), inicia_tracos(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
pwa
double * DG_Elem::pwa [private]
ponteiros para os valores nos pontos de Gauss da saturacao e pressao atuais
Definition at line 108 of file DG_Elem.hpp.
Referenced by Atualizar_valores(), finaliza_vetores(), and inicia_vetores().
qn
double DG_Elem::qn [private]
Definition at line 112 of file DG_Elem.hpp.
Referenced by set_fontes(), VolumeIntegrals(), and VolumeIntegrals_UMFPACK().
qw
double DG_Elem::qw [private]
Definition at line 112 of file DG_Elem.hpp.
Referenced by set_fontes(), VolumeIntegrals(), and VolumeIntegrals_UMFPACK().
rho
double DG_Elem::rho [private]
densidade de massa ou porosidade
Definition at line 109 of file DG_Elem.hpp.
Referenced by DG_Elem(), set_mass_density(), and show_rho().
sgn
int PhElem< NumVariaveis >::sgn[NumVariaveis][MAXNN] [protected], [inherited]
sign of the local mode (or mode)
Definition at line 198 of file PhElem.hpp.
sinal
int PhElem< NumVariaveis >::sinal[12] [protected], [inherited]
sinal refers to the borders
Definition at line 195 of file PhElem.hpp.
Referenced by echo_traco(), inicia_funcoes_na_borda(), inicia_tracos(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
sna
double* DG_Elem::sna [private]
Definition at line 108 of file DG_Elem.hpp.
Referenced by Atualizar_valores(), finaliza_vetores(), inicia_vetores(), VolumeIntegrals(), VolumeIntegrals_UMFPACK(), and VolumeIntegralsT().
stgbtrbmapM
int* PhElem< NumVariaveis >::stgbtrbmapM [protected], [inherited]
Array containing the start point in the global trace array of the internal trace of the border.
Definition at line 212 of file PhElem.hpp.
Referenced by finaliza_vetores().
stgbtrbmapP
int* PhElem< NumVariaveis >::stgbtrbmapP [protected], [inherited]
Array containing the start point in the global trace array of the external trace of the border.
Definition at line 214 of file PhElem.hpp.
Referenced by finaliza_vetores().
TrGradPhi
double***** DG_Elem::TrGradPhi [private]
Definition at line 126 of file DG_Elem.hpp.
Referenced by calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), and Traco_grad_phi().
TrKgrad_pc
double*** DG_Elem::TrKgrad_pc [private]
Definition at line 122 of file DG_Elem.hpp.
Referenced by calcula_tracos(), finaliza_vetores(), inicia_vetores(), Traco_Kgrad_pc(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
TrKgrad_pw
double*** DG_Elem::TrKgrad_pw [private]
Definition at line 121 of file DG_Elem.hpp.
Referenced by calcula_tracos(), finaliza_vetores(), inicia_vetores(), Traco_Kgrad_pw(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
TrKgrad_sn
double*** DG_Elem::TrKgrad_sn [private]
Definition at line 120 of file DG_Elem.hpp.
Referenced by calcula_tracos(), finaliza_vetores(), inicia_vetores(), Traco_Kgrad_sn(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
TrKgradPhi_n
double**** DG_Elem::TrKgradPhi_n [private]
Definition at line 125 of file DG_Elem.hpp.
Referenced by echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), and Traco_Kgrad_phi_n().
TrPhi
double**** DG_Elem::TrPhi [private]
Definition at line 123 of file DG_Elem.hpp.
Referenced by calcula_tracos(), echo_traco(), finaliza_vetores(), inicia_funcoes_na_borda(), inicia_tracos(), inicia_vetores(), Traco_phi(), and Traco_phi_1().
Trpw
double** DG_Elem::Trpw [private]
Definition at line 118 of file DG_Elem.hpp.
Referenced by calcula_tracos(), finaliza_vetores(), inicia_vetores(), Traco_pw(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
Trsn
double** DG_Elem::Trsn [private]
Definition at line 117 of file DG_Elem.hpp.
Referenced by calcula_tracos(), finaliza_vetores(), inicia_vetores(), Traco_sn(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
type
int PhElem< NumVariaveis >::type [protected], [inherited]
Definition at line 185 of file PhElem.hpp.
u0
double* PhElem< NumVariaveis >::u0[NumVariaveis] [protected], [inherited]
vector with the coefficients of each mode
Definition at line 203 of file PhElem.hpp.
Referenced by Atualizar_valores(), calcula_tracos(), finaliza_vetores(), inicia_vetores(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), VolumeIntegralsT(), and VolumeTracos().
usave
double* PhElem< NumVariaveis >::usave[NumVariaveis] [protected], [inherited]
Definition at line 204 of file PhElem.hpp.
Referenced by finaliza_vetores(), and inicia_vetores().
Vert_map
int PhElem< NumVariaveis >::Vert_map[8] [protected], [inherited]
Definition at line 195 of file PhElem.hpp.
Referenced by Atualizar_valores(), inicia_funcoes_na_borda(), inicia_tracos(), VolumeIntegrals(), VolumeIntegrals_IG(), VolumeIntegrals_UMFPACK(), and VolumeTracos().
vetores_iniciados
int PhElem< NumVariaveis >::vetores_iniciados [protected], [inherited]
Definition at line 216 of file PhElem.hpp.
Referenced by DG_Elem(), finaliza_vetores(), and inicia_vetores().
Volume
double DG_Elem::Volume [private]
Volume do elemento (= area do elemento para elementos bidimensionais e comprimento para elem. 1D.
Definition at line 113 of file DG_Elem.hpp.
Referenced by show_Volume().
The documentation for this class was generated from the following files:
DG_Elem.hpp
DG_Elem.cpp