DG_Prob Class Reference
#include <DG_Prob.h>
Public Member Functions
DG_Prob (Epetra_Comm &comm)
~DG_Prob ()
void preamble (char *str)
void Driver (char *argv=0)
void DG_alocar_mem_local (const int qmax, const int nsat, const int npres)
void DG_liberar_mem_local (const int nsat, const int npres)
void DG_initial_conditions ()
void DG_eco ()
void DG_Iterate ()
void DG_Iterate_NOX ()
void Ge_MVRA0 (const double Dt, Epetra_Map Map, double &valor0, double_t &norm_delta_X)
void Ge_MVRA (const double Dt, Epetra_Map Map, double &valor, int &token, double_t &norm_delta_X)
int Eigenvectors (const double Dt, const Epetra_Map &Map)
void DG_conditionNumber (Epetra_Map Map)
void Ler_Arquivo_Dados_DG (char *arq_par)
void MPI_Recebe_Dados_DG ()
void DG_Transfere_rst (int *b_in, double *b_do, double *buff)
void DG_MatrizVetor_UMFPACK (const double Dt, int &count, const int nz, int *Ti, int *Tj, double *Tx, double *B)
void DG_MatrizVetor_Epetra (const double Dt, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
void DG_EI_Interior (const EDGE border, int &count, int *Ti, int *Tj, double *Tx, double *B)
void DG_EI_Inflow (const EDGE border, int &count, int *Ti, int *Tj, double *Tx, double *B)
void DG_EI_Outflow (const EDGE border, int &count, int *Ti, int *Tj, double *Tx, double *B)
void DG_EI_Epetra_Interior (const EDGE border, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
void DG_EI_Epetra_Inflow (const EDGE border, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
void DG_EI_Epetra_Outflow (const EDGE border, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
int DG_EI_Inflow (const EDGE border, double *mx, double *B, int *indx)
int DG_EI_Interior (const EDGE border, double *mx, double *B, int *indx)
int DG_EI_Outflow (const EDGE border, double *mx, double *B, int *indx)
void DG_EI_flux (const EDGE border, double &flux_w, double &flux_n)
void DG_EI_IG (const EDGE border, const double sigma, const double sigma1, const double beta, int &count, int *Ti, int *Tj, double *Tx, double *B, const int qmax, const double w0[])
void DG_Escrever_rst (const int nprt=0)
void DG_imprimir_taxas_de_producao (FILE *fout3, double valor, double valor0, double valor1, int iter)
void projetar_C0 (FILE *file, double(*func)(double, double, double), const int &ivar)
bool evaluate (const FillType flag, const Epetra_Vector *X, Epetra_Vector *FVec, Epetra_RowMatrix *Jacobian)
void Processa_condicoes_contorno ()
Epetra_Comm * show_Comm ()
Teuchos::RCP< Epetra_Vector > getSolution ()
Teuchos::RCP< Epetra_CrsMatrix > getJacobian ()
void Ler__Geometria (FILE *finput, double *coord, int *Ed, int *BC)
void set_id (const int rank, const int size)
void Marcar_condicoes_contorno (int *, std::vector< std::vector< int > >)
void Processar_elementos ()
void set_finput (FILE *ptr)
void set_fout (FILE *ptr)
void set_fout1 (FILE *ptr)
void set_fout2 (FILE *ptr)
void set_fout3 (FILE *ptr)
int show_NG ()
int show_NUMNP ()
int show_NELEM ()
int show_NL ()
int show_NF ()
int show_NumD ()
void RenumerarNos ()
void RenumerarNos (int, int &)
void Particionar_malha (const int *buf)
void ResolverComTrilinos (const std::string Pack, Epetra_Map Map, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS, double_t &norm_delta_X)
void Construir_bordas ()
void gbnmap_continuous (const int &ivar, int &count)
void gbnmap_continuous (int &count)
void mesh_suporte (const int &P, int Temp_V[], int Temp_A[], int Temp_F[], int &count)
void gbnmap_discontinuous (const int &ivar, int &count)
void Facet_eco (FILE *fout)
void MPI_Recebe_Dados_GeProb ()
void Ler_e_Processar_malha (char *arq_geo)
Protected Attributes
Epetra_Comm * Comm
Teuchos::RCP< Epetra_Vector > solution
int MyPID
int NumProc
int NumElemTypeents
int NumGlobalElements
int myid
int comm_size
int NumD
int NumC
const int NumVAR
const int NumFIELDS
Field_struct Field [N_FIELDS]
int FieldOfVar [N_VAR]
int dim
int NG
int NUMNP
int NELEM
int NDFCD
int NL
int NF
int NBORDER
Vertice * V
std::vector< ARESTA > Aresta
std::vector< FACE > Face
MyElem * el
int * novoNum
EDGE * border
std::vector< FACET > facet
std::vector< int > bflag
int DNBC
int NBC [20][3]
int nin
int nout
std::vector< int > in_borders
std::vector< int > out_borders
int NumPart
Numero de particoes.
std::vector< PARTICAO > Particao
Linear * ptrLinear [N_FIELDS]
Triangle * ptrTriang [N_FIELDS]
Quadrilateral * ptrQuadri [N_FIELDS]
Tetrahedral * ptrTetrahedral [N_FIELDS]
Hexahedral * ptrHexahedral [N_FIELDS]
std::string TrilinosSolver
std::string AmesosSolverType
Private Attributes
int count
int nz
int restart_flag
0 comeca; 1 continua
double theta
double pd
double mun
double muw
double rhon
double rhow
double porosidade
char arq_rst [256]
string contendo o nome do arquivo para recomecar simulacao
char arq_sai [256]
string contendo o nome do arquivo para saida dos resultados
char arq_eco [256]
string contendo o nome do arquivo para eco dos dados
char arq_flu [256]
string contendo o nome do arquivo de fluxos
double t
tempo de simulacao
double Dt
Intervalo de tempo; pode variar conforme falhe a convergencia.
double Dt0
Intervalo de tempo inicial.
double fatordt
fator de reducao do Dt
double t_final
tempo final de simulacao
double tprint
intervalo entre escritas de resultados no arquivo
double precisao
precisao da iteracao de Gauss
double qdado
int passo
int tnc
int tncut
double injrate_w
double injrate_n
double prodrate_w
double prodrate_n
double Iw
double In
double Qw
double Qn
double injrate_w0
double injrate_n0
double prodrate_w0
double prodrate_n0
double gravidade [3]
double perm
double sigma
double sigma1
double beta
Fluids fluids
double * gbtrpw
double * gbtrsn
double *** Kgsn
double *** Kgpw
double *** Kgpc
Kgxx [iE][i][iq] = Traco de Kgrad_xx.
double **** K_g_phi_n
gphi_# [dir][iq] = grad_phi
bool memoria_alocada = false
Detailed Description
Definition at line 22 of file DG_Prob.h.
Constructor & Destructor Documentation
DG_Prob()
DG_Prob::DG_Prob (Epetra_Comm & comm)
Definition at line 14 of file DG_Prob.cpp.
 DG_Prob()
DG_Prob::~DG_Prob ()
Definition at line 17 of file DG_Prob.cpp.
References DG_liberar_mem_local(), GeProb< MyElem, 2, 2 >::el, DG_Elem::finaliza_vetores(), gbtrpw, gbtrsn, GeProb< MyElem, 2, 2 >::NELEM, Stdel::nn_val(), npres, nsat, pres, sat, and PhElem< NumVariaveis >::show_ptr_stdel().
Member Function Documentation
Construir_bordas()
void GeProb< MyElem , N_VAR, N_FIELDS >::Construir_bordas () [inherited]
Definition at line 1136 of file GeProb.hpp.
References aux, GeProb< ElemType, N_VAR, N_FIELDS >::border, EDGE::comprimento, GeProb< ElemType, N_VAR, N_FIELDS >::dim, e, GeProb< ElemType, N_VAR, N_FIELDS >::el, EDGE::elemento, n0, EDGE::Na, EDGE::Nb, GeProb< ElemType, N_VAR, N_FIELDS >::NBORDER, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, GeProb< ElemType, N_VAR, N_FIELDS >::NF, GeProb< ElemType, N_VAR, N_FIELDS >::NL, EDGE::normal, EDGE::num_elem, EDGE::num_local, GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP, EDGE::pdir, EDGE::sdir, EDGE::sinal, and EDGE::tipo.
DG_alocar_mem_local()
void DG_Prob::DG_alocar_mem_local (const int qmax, const int nsat, const int npres)
Definition at line 406 of file DG_Prob.cpp.
References iE, K_g_phi_n, Kgpc, Kgpw, Kgsn, memoria_alocada, npres, nsat, pres, qmax, and sat.
Referenced by DG_initial_conditions(), and projetar_C0().
DG_conditionNumber()
void DG_Prob::DG_conditionNumber (Epetra_Map Map)
Definition at line 151 of file DG_MVRA.cpp.
References DG_MatrizVetor_Epetra(), Dt, sigma, and sigma1.
DG_eco()
void DG_Prob::DG_eco ()
Definition at line 6 of file DG_eco.cpp.
References a, arq_eco, beta, GeProb< MyElem, 2, 2 >::border, EDGE::comprimento, GeProb< MyElem, 2, 2 >::dim, Dt0, e, GeProb< MyElem, 2, 2 >::el, EDGE::elemento, fatordt, GeProb< MyElem, 2, 2 >::Field, gravidade, PhElem< NumVariaveis >::map(), mun, muw, GeProb< MyElem, 2, 2 >::myid, Stdel::nb_val(), GeProb< MyElem, 2, 2 >::NBORDER, Stdel::nborder_val(), Stdel::ne_val(), GeProb< MyElem, 2, 2 >::NELEM, GeProb< MyElem, 2, 2 >::NF, GeProb< MyElem, 2, 2 >::NL, Stdel::nn_val(), EDGE::num_local, GeProb< MyElem, 2, 2 >::NumD, GeProb< MyElem, 2, 2 >::NumFIELDS, GeProb< MyElem, 2, 2 >::NUMNP, GeProb< MyElem, 2, 2 >::NumVAR, Stdel::nv_val(), Field_struct::P, p_in, p_out, pd, perm, porosidade, precisao, pw_ini, qdado, rhon, rhow, PhElem< NumVariaveis >::show_border_num(), PhElem< NumVariaveis >::show_part_num(), PhElem< NumVariaveis >::show_ptr_stdel(), PhElem< NumVariaveis >::show_stgbtrbmapM(), PhElem< NumVariaveis >::show_stgbtrbmapP(), sigma, sigma1, EDGE::sinal, sn_in, sn_ini, t, t_final, theta, EDGE::tipo, tncut, tprint, PhElem< NumVariaveis >::type_val(), and GeProb< MyElem, 2, 2 >::V.
Referenced by Driver().
DG_EI_Epetra_Inflow()
void DG_Prob::DG_EI_Epetra_Inflow (const EDGE border, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
Definition at line 7 of file DG_EI_Inflow_a.cpp.
References B(), DG_EI_Inflow(), GeProb< MyElem, 2, 2 >::el, EDGE::elemento, Stdel::nn_val(), pres, sat, and PhElem< NumVariaveis >::show_ptr_stdel().
Referenced by DG_MatrizVetor_Epetra().
DG_EI_Epetra_Interior()
void DG_Prob::DG_EI_Epetra_Interior (const EDGE border, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
Definition at line 5 of file DG_EI_Interior_a.cpp.
References B(), DG_EI_Interior(), GeProb< MyElem, 2, 2 >::el, EDGE::elemento, Stdel::nn_val(), pres, sat, and PhElem< NumVariaveis >::show_ptr_stdel().
Referenced by DG_MatrizVetor_Epetra().
DG_EI_Epetra_Outflow()
void DG_Prob::DG_EI_Epetra_Outflow (const EDGE border, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
Definition at line 4 of file DG_EI_Outflow_a.cpp.
References B(), DG_EI_Outflow(), GeProb< MyElem, 2, 2 >::el, EDGE::elemento, Stdel::nn_val(), pres, sat, and PhElem< NumVariaveis >::show_ptr_stdel().
Referenced by DG_MatrizVetor_Epetra().
DG_EI_flux()
void DG_Prob::DG_EI_flux (const EDGE border, double & flux_w, double & flux_n)
Definition at line 4 of file DG_EI_flux.cpp.
References a, aux, EDGE::comprimento, Dtemp, e, GeProb< MyElem, 2, 2 >::el, EDGE::elemento, fluids, Gauss_Jacobi_parameters(), EDGE::gbtrbind, gbtrsn, iE, Jac, K_g_pc_n, K_g_pw_n, Kgpc, Kgpw, Fluids::Krn(), Fluids::Krw(), lambdan, lambdat, lambdaw, length, MAXQ, mun, muw, n_e, ndim, Stdel::ndim_val(), EDGE::normal, EDGE::num_local, Stdel::qborder_val(), qmax, Fluids::show_mun(), Fluids::show_muw(), PhElem< NumVariaveis >::show_ptr_stdel(), sn, DG_Elem::Traco_Kgrad_pc(), DG_Elem::Traco_Kgrad_pw(), and w.
Referenced by DG_imprimir_taxas_de_producao(), and DG_initial_conditions().
DG_EI_IG()
void DG_Prob::DG_EI_IG (const EDGE border, const double sigma, const double sigma1, const double beta, int & count, int * Ti, int * Tj, double * Tx, double * B, const int qmax, const double w0[])
Definition at line 7 of file DG_IG_EI.cpp.
References a, aux, aux1, aux2, EDGE::comprimento, count, d2_pc, Fluids::d2pc(), d_lambdan, d_lambdat, d_lambdaw, d_pc, Fluids::dkrn(), Fluids::dkrw(), Fluids::dpc(), e, GeProb< MyElem, 2, 2 >::el, EDGE::elemento, fluids, iEl, iEr, integral(), Kgpc, Kgpw, Kgsn, kln, klt, kn, Fluids::Krn(), Fluids::Krw(), lambdan, lambdat, lambdaw, length, m, PhElem< NumVariaveis >::map(), mun, muw, n_e, ndim, Stdel::ndim_val(), Stdel::nn_val(), EDGE::normal, EDGE::num_local, pc, EDGE::pdir, penalty, penalty1, perm, DG_Elem::perm_val(), phi_l, phi_r, pres, Fluids::pressao_capilar(), prod3v(), prodvv(), pw, qmax, sat, EDGE::sdir, Fluids::show_mun(), Fluids::show_muw(), PhElem< NumVariaveis >::show_ptr_stdel(), Sinal(), sn, subtvv(), EDGE::tipo, DG_Elem::Traco_Kgrad_pc(), DG_Elem::Traco_Kgrad_phi_n(), DG_Elem::Traco_Kgrad_pw(), DG_Elem::Traco_Kgrad_sn(), DG_Elem::Traco_phi(), DG_Elem::Traco_pw(), DG_Elem::Traco_sn(), and w.
Referenced by DG_initial_conditions().
DG_EI_Inflow() [1/2]
void DG_Prob::DG_EI_Inflow (const EDGE border, int & count, int * Ti, int * Tj, double * Tx, double * B)
Referenced by DG_EI_Epetra_Inflow(), and DG_MatrizVetor_UMFPACK().
DG_EI_Inflow() [2/2]
int DG_Prob::DG_EI_Inflow (const EDGE border, double * mx, double * B, int * indx)
Definition at line 14 of file DG_EI_Inflow_b.cpp.
References a, aux, aux1, aux2, d2_pc, d_lambdan, d_lambdat, d_lambdaw, d_pc, e, fluids, iEl, iEr, indice(), Stdel::is_on_border(), K_g_pc_n, K_g_phi_n, K_g_pw_n, K_g_sn_n, kln, klt, klw, lambdan, lambdat, lambdaw, PhElem< NumVariaveis >::map(), n0, Stdel::nn_val(), npos(), pc, EDGE::pdir, penalty, penalty1, phi_l, phi_r, pos, pres, Fluids::pressao_capilar(), pw, qmax, sat, EDGE::sdir, PhElem< NumVariaveis >::show_ptr_stdel(), DG_Elem::Traco_phi_1(), and w.
DG_EI_Interior() [1/2]
void DG_Prob::DG_EI_Interior (const EDGE border, int & count, int * Ti, int * Tj, double * Tx, double * B)
Definition at line 6 of file DG_EI_Interior.cpp.
References a, aux, aux1, aux2, count, d2_pc, d_lambdan, d_lambdat, d_lambdaw, d_pc, e, iEl, iEr, indice_interior(), Stdel::is_on_border(), K_g_pc_n, K_g_phi_n, K_g_pw_n, K_g_sn_n, Kgpw, kln, klt, klw, lambdan, lambdat, lambdaw, PhElem< NumVariaveis >::map(), n_e, ndim, Stdel::nn_val(), npos(), pc, penalty, penalty1, phi_l, phi_r, pos, pres, pw, qmax, sat, PhElem< NumVariaveis >::show_ptr_stdel(), Sinal(), DG_Elem::Traco_phi_1(), and w.
Referenced by DG_EI_Epetra_Interior(), and DG_MatrizVetor_UMFPACK().
DG_EI_Interior() [2/2]
int DG_Prob::DG_EI_Interior (const EDGE border, double * mx, double * B, int * indx)
Definition at line 11 of file DG_EI_Interior_b.cpp.
References a, aux, aux1, aux2, d2_pc, d_lambdan, d_lambdat, d_lambdaw, d_pc, e, iEl, iEr, indice_interior(), Stdel::is_on_border(), K_g_pc_n, K_g_phi_n, K_g_pw_n, K_g_sn_n, Kgpw, kln, klt, klw, lambdan, lambdat, lambdaw, PhElem< NumVariaveis >::map(), n_e, ndim, Stdel::nn_val(), npos(), pc, penalty, penalty1, phi_l, phi_r, pos, pres, pw, qmax, sat, PhElem< NumVariaveis >::show_ptr_stdel(), Sinal(), DG_Elem::Traco_phi_1(), and w.
DG_EI_Outflow() [1/2]
void DG_Prob::DG_EI_Outflow (const EDGE border, int & count, int * Ti, int * Tj, double * Tx, double * B)
Definition at line 6 of file DG_EI_Outflow.cpp.
References a, aux, aux1, aux2, count, d_lambdat, d_lambdaw, e, iEl, iEr, indice(), Stdel::is_on_border(), K_g_phi_n, K_g_pw_n, klt, klw, lambdat, lambdaw, PhElem< NumVariaveis >::map(), n0, Stdel::nn_val(), npos(), EDGE::pdir, penalty, phi_l, phi_r, pos, pres, pw, qmax, sat, PhElem< NumVariaveis >::show_ptr_stdel(), DG_Elem::Traco_phi_1(), and w.
Referenced by DG_EI_Epetra_Outflow(), and DG_MatrizVetor_UMFPACK().
DG_EI_Outflow() [2/2]
int DG_Prob::DG_EI_Outflow (const EDGE border, double * mx, double * B, int * indx)
Definition at line 12 of file DG_EI_Outflow_b.cpp.
References a, aux, aux1, aux2, d_lambdat, d_lambdaw, e, iEl, iEr, indice(), Stdel::is_on_border(), K_g_phi_n, K_g_pw_n, klt, klw, lambdat, lambdaw, PhElem< NumVariaveis >::map(), n0, Stdel::nn_val(), npos(), EDGE::pdir, penalty, phi_l, phi_r, pos, pres, pw, qmax, sat, PhElem< NumVariaveis >::show_ptr_stdel(), DG_Elem::Traco_phi_1(), and w.
DG_Escrever_rst()
void DG_Prob::DG_Escrever_rst (const int nprt = 0)
Definition at line 550 of file DG_Prob.cpp.
References arq_sai, Dt, GeProb< MyElem, 2, 2 >::el, In, injrate_n0, injrate_w0, Iw, GeProb< MyElem, 2, 2 >::NELEM, passo, prodrate_n0, prodrate_w0, Qn, Qw, t, and tnc.
Referenced by DG_Iterate().
DG_imprimir_taxas_de_producao()
void DG_Prob::DG_imprimir_taxas_de_producao (FILE * fout3, double valor, double valor0, double valor1, int iter)
Definition at line 15 of file DG_saidas_intermediarias.cpp.
References GeProb< MyElem, 2, 2 >::border, DG_EI_flux(), Dt, GeProb< MyElem, 2, 2 >::el, EDGE::elemento, fluids, gbtrpw, gbtrsn, In, GeProb< MyElem, 2, 2 >::in_borders, injrate_n, injrate_n0, injrate_w, injrate_w0, Iw, GeProb< MyElem, 2, 2 >::myid, GeProb< MyElem, 2, 2 >::nin, GeProb< MyElem, 2, 2 >::nout, GeProb< MyElem, 2, 2 >::out_borders, passo, prodrate_n, prodrate_n0, prodrate_w, prodrate_w0, Qn, Qw, t, tnc, and DG_Elem::VolumeTracos().
Referenced by DG_Iterate().
DG_initial_conditions()
void DG_Prob::DG_initial_conditions ()
Definition at line 62 of file DG_Prob.cpp.
References arq_rst, arq_sai, DG_Elem::Atualizar_valores(), B(), beta, GeProb< MyElem, 2, 2 >::border, GeProb< MyElem, 2, 2 >::Comm, count, DG_alocar_mem_local(), DG_EI_flux(), DG_EI_IG(), DG_Transfere_rst(), Dt, Dt0, Dtemp, GeProb< MyElem, 2, 2 >::el, fluids, Gauss_Jacobi_parameters(), GeProb< MyElem, 2, 2 >::gbnmap_continuous(), Tstruct::i, In, GeProb< MyElem, 2, 2 >::in_borders, DG_Elem::inicia_funcoes_na_borda(), PhElem< NumVariaveis >::inicia_gbnmap(), DG_Elem::inicia_vetores(), injrate_n0, injrate_w0, Iw, Tstruct::j, Jac, PhElem< NumVariaveis >::mapa_inverso(), MAXQ, mun, muw, GeProb< MyElem, 2, 2 >::myid, ndim, Stdel::ndim_val(), GeProb< MyElem, 2, 2 >::NELEM, GeProb< MyElem, 2, 2 >::nin, GeProb< MyElem, 2, 2 >::NL, Stdel::nn_val(), GeProb< MyElem, 2, 2 >::nout, npres, nsat, GeProb< MyElem, 2, 2 >::NumD, nz, GeProb< MyElem, 2, 2 >::out_borders, pd, perm, porosidade, pres, prodrate_n0, prodrate_w0, PhElem< NumVariaveis >::projetar_C0(), Stdel::qborder_val(), qmax, Qn, Qw, ResolverSistema(), restart_flag, rhon, rhow, sat, DG_Elem::set_fontes(), Fluids::set_mun(), Fluids::set_muw(), Fluids::set_pd(), DG_Elem::set_permeabilidade(), DG_Elem::set_porosidade(), Fluids::set_rhon(), Fluids::set_rhow(), Fluids::set_theta(), PhElem< NumVariaveis >::show_ptr_stdel(), sn_inicial(), t, theta, Vstruct::v, DG_Elem::VolumeIntegrals_IG(), and Tstruct::x.
Referenced by Driver().
DG_Iterate()
void DG_Prob::DG_Iterate ()
Definition at line 13 of file DG_Iterate.cpp.
References arq_flu, arq_rst, arq_sai, GeProb< MyElem, 2, 2 >::Comm, DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), Dt, Dt0, GeProb< MyElem, 2, 2 >::el, fatordt, Ge_MVRA(), Ge_MVRA0(), In, injrate_n0, injrate_w0, Iw, GeProb< MyElem, 2, 2 >::myid, GeProb< MyElem, 2, 2 >::NELEM, GeProb< MyElem, 2, 2 >::NumD, passo, prodrate_n0, prodrate_w0, Qn, Qw, restart_flag, t, t_final, tnc, tncut, and tprint.
Referenced by Driver().
DG_Iterate_NOX()
void DG_Prob::DG_Iterate_NOX ()
DG_liberar_mem_local()
void DG_Prob::DG_liberar_mem_local (const int nsat, const int npres)
Definition at line 490 of file DG_Prob.cpp.
References iE, K_g_phi_n, Kgpc, Kgpw, Kgsn, memoria_alocada, npres, nsat, pres, and sat.
Referenced by ~DG_Prob().
DG_MatrizVetor_Epetra()
void DG_Prob::DG_MatrizVetor_Epetra (const double Dt, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
Definition at line 82 of file DG_MVRA.cpp.
References GeProb< MyElem, 2, 2 >::border, GeProb< MyElem, 2, 2 >::Comm, DG_EI_Epetra_Inflow(), DG_EI_Epetra_Interior(), DG_EI_Epetra_Outflow(), GeProb< MyElem, 2, 2 >::el, fluids, gbtrpw, gbtrsn, GeProb< MyElem, 2, 2 >::myid, GeProb< MyElem, 2, 2 >::Particao, t, EDGE::tipo, DG_Elem::VolumeIntegrals(), and DG_Elem::VolumeTracos().
Referenced by DG_conditionNumber(), Eigenvectors(), Ge_MVRA(), and Ge_MVRA0().
DG_MatrizVetor_UMFPACK()
void DG_Prob::DG_MatrizVetor_UMFPACK (const double Dt, int & count, const int nz, int * Ti, int * Tj, double * Tx, double * B)
Definition at line 349 of file DG_Prob.cpp.
References GeProb< MyElem, 2, 2 >::border, DG_EI_Inflow(), DG_EI_Interior(), DG_EI_Outflow(), GeProb< MyElem, 2, 2 >::el, fluids, gbtrpw, gbtrsn, GeProb< MyElem, 2, 2 >::NumD, GeProb< MyElem, 2, 2 >::NumPart, GeProb< MyElem, 2, 2 >::Particao, t, EDGE::tipo, DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
DG_Transfere_rst()
void DG_Prob::DG_Transfere_rst (int * b_in, double * b_do, double * buff)
Definition at line 7 of file Transfere_rst.cpp.
References count, Dt, GeProb< MyElem, 2, 2 >::el, In, injrate_n0, injrate_w0, Iw, GeProb< MyElem, 2, 2 >::NELEM, passo, prodrate_n0, prodrate_w0, Qn, Qw, t, and tnc.
Referenced by DG_initial_conditions().
Driver()
void DG_Prob::Driver (char * argv = 0)
Definition at line 6 of file DG_driver.cpp.
References GeProb< MyElem, 2, 2 >::AmesosSolverType, GeProb< MyElem, 2, 2 >::Comm, DG_eco(), DG_initial_conditions(), DG_Iterate(), GeProb< MyElem, 2, 2 >::myid, GeProb< MyElem, 2, 2 >::NumD, and GeProb< MyElem, 2, 2 >::TrilinosSolver.
Eigenvectors()
int DG_Prob::Eigenvectors (const double Dt, const Epetra_Map & Map)
Definition at line 20 of file DG_Eigenvectors.cpp.
References B(), GeProb< MyElem, 2, 2 >::Comm, DG_MatrizVetor_Epetra(), e, and GeProb< MyElem, 2, 2 >::MyPID.
evaluate()
bool DG_Prob::evaluate (const FillType flag, const Epetra_Vector * X, Epetra_Vector * FVec, Epetra_RowMatrix * Jacobian)
Facet_eco()
void GeProb< MyElem , N_VAR, N_FIELDS >::Facet_eco (FILE * fout) [inherited]
Definition at line 602 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::border, GeProb< ElemType, N_VAR, N_FIELDS >::facet, and GeProb< ElemType, N_VAR, N_FIELDS >::NBORDER.
gbnmap_continuous() [1/2]
void GeProb< MyElem , N_VAR, N_FIELDS >::gbnmap_continuous (const int & ivar, int & count) [inherited]
Definition at line 1081 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Aresta, GeProb< ElemType, N_VAR, N_FIELDS >::dim, e, GeProb< ElemType, N_VAR, N_FIELDS >::el, GeProb< ElemType, N_VAR, N_FIELDS >::mesh_suporte(), GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, GeProb< ElemType, N_VAR, N_FIELDS >::NF, GeProb< ElemType, N_VAR, N_FIELDS >::NL, and GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP.
Referenced by DG_initial_conditions().
gbnmap_continuous() [2/2]
void GeProb< MyElem , N_VAR, N_FIELDS >::gbnmap_continuous (int & count) [inherited]
Definition at line 1066 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::gbnmap_continuous(), and GeProb< ElemType, N_VAR, N_FIELDS >::NumD.
gbnmap_discontinuous()
void GeProb< MyElem , N_VAR, N_FIELDS >::gbnmap_discontinuous (const int & ivar, int & count) [inherited]
Definition at line 1124 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::el, and GeProb< ElemType, N_VAR, N_FIELDS >::NELEM.
Ge_MVRA()
void DG_Prob::Ge_MVRA (const double Dt, Epetra_Map Map, double & valor, int & token, double_t & norm_delta_X)
Definition at line 28 of file DG_MVRA.cpp.
References GeProb< MyElem, 2, 2 >::Comm, DG_MatrizVetor_Epetra(), precisao, GeProb< MyElem, 2, 2 >::ResolverComTrilinos(), and GeProb< MyElem, 2, 2 >::TrilinosSolver.
Referenced by DG_Iterate().
Ge_MVRA0()
void DG_Prob::Ge_MVRA0 (const double Dt, Epetra_Map Map, double & valor0, double_t & norm_delta_X)
Definition at line 6 of file DG_MVRA.cpp.
References GeProb< MyElem, 2, 2 >::Comm, DG_MatrizVetor_Epetra(), GeProb< MyElem, 2, 2 >::ResolverComTrilinos(), and GeProb< MyElem, 2, 2 >::TrilinosSolver.
Referenced by DG_Iterate().
getJacobian()
Teuchos::RCP<Epetra_CrsMatrix> GeProb< MyElem , N_VAR, N_FIELDS >::getJacobian () [inherited]
getSolution()
Teuchos::RCP<Epetra_Vector> GeProb< MyElem , N_VAR, N_FIELDS >::getSolution () [inline], [inherited]
Definition at line 24 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::getJacobian(), GeProb< ElemType, N_VAR, N_FIELDS >::Ler__Geometria(), and GeProb< ElemType, N_VAR, N_FIELDS >::solution.
Ler__Geometria()
void GeProb< MyElem , N_VAR, N_FIELDS >::Ler__Geometria (FILE * finput, double * coord, int * Ed, int * BC) [inherited]
Definition at line 639 of file GeProb.hpp.
References a, GeProb< ElemType, N_VAR, N_FIELDS >::DNBC, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, and GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP.
Ler_Arquivo_Dados_DG()
void DG_Prob::Ler_Arquivo_Dados_DG (char * arq_par)
Definition at line 147 of file DG_preamble.cpp.
References beta, GeProb< MyElem, 2, 2 >::Comm, GeProb< MyElem, 2, 2 >::comm_size, Dt0, fatordt, gravidade, MPI_Recebe_Dados_DG(), mun, muw, GeProb< MyElem, 2, 2 >::myid, p_in, p_out, pd, perm, porosidade, precisao, pw_ini, qdado, restart_flag, rhon, rhow, sigma, sigma1, sn_in, sn_ini, t_final, theta, tncut, and tprint.
Referenced by preamble().
Ler_e_Processar_malha()
void GeProb< MyElem , N_VAR, N_FIELDS >::Ler_e_Processar_malha (char * arq_geo) [inherited]
Definition at line 830 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Comm, GeProb< ElemType, N_VAR, N_FIELDS >::comm_size, GeProb< ElemType, N_VAR, N_FIELDS >::Construir_bordas(), GeProb< ElemType, N_VAR, N_FIELDS >::dim, GeProb< ElemType, N_VAR, N_FIELDS >::DNBC, GeProb< ElemType, N_VAR, N_FIELDS >::el, ElemType, GeProb< ElemType, N_VAR, N_FIELDS >::Ler__Geometria(), GeProb< ElemType, N_VAR, N_FIELDS >::Marcar_condicoes_contorno(), GeProb< ElemType, N_VAR, N_FIELDS >::myid, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP, GeProb< ElemType, N_VAR, N_FIELDS >::NumPart, GeProb< ElemType, N_VAR, N_FIELDS >::Particionar_malha(), GeProb< ElemType, N_VAR, N_FIELDS >::Processar_elementos(), tetrahedro_faz_face_mask(), GeProb< ElemType, N_VAR, N_FIELDS >::V, Vertice::x, Vertice::y, and Vertice::z.
Referenced by ED_Prob::preamble(), and preamble().
Marcar_condicoes_contorno()
void GeProb< MyElem , N_VAR, N_FIELDS >::Marcar_condicoes_contorno (int * BC, std::vector< std::vector< int > > face_mask) [inherited]
Definition at line 1296 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::bflag, GeProb< ElemType, N_VAR, N_FIELDS >::border, GeProb< ElemType, N_VAR, N_FIELDS >::DNBC, GeProb< ElemType, N_VAR, N_FIELDS >::el, and GeProb< ElemType, N_VAR, N_FIELDS >::NG.
mesh_suporte()
void GeProb< MyElem , N_VAR, N_FIELDS >::mesh_suporte (const int & P, int Temp_V[], int Temp_A[], int Temp_F[], int & count) [inherited]
Definition at line 1030 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Face, GeProb< ElemType, N_VAR, N_FIELDS >::NF, GeProb< ElemType, N_VAR, N_FIELDS >::NL, and GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP.
MPI_Recebe_Dados_DG()
void DG_Prob::MPI_Recebe_Dados_DG ()
Definition at line 193 of file DG_preamble.cpp.
References beta, Dt0, fatordt, gravidade, mun, muw, p_in, p_out, pd, perm, porosidade, precisao, pw_ini, qdado, restart_flag, rhon, rhow, sigma, sigma1, sn_in, sn_ini, t_final, theta, tncut, and tprint.
Referenced by Ler_Arquivo_Dados_DG().
MPI_Recebe_Dados_GeProb()
void GeProb< MyElem , N_VAR, N_FIELDS >::MPI_Recebe_Dados_GeProb () [inherited]
Definition at line 717 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Comm, GeProb< ElemType, N_VAR, N_FIELDS >::comm_size, GeProb< ElemType, N_VAR, N_FIELDS >::DNBC, GeProb< ElemType, N_VAR, N_FIELDS >::myid, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP, and GeProb< ElemType, N_VAR, N_FIELDS >::NumPart.
Particionar_malha()
void GeProb< MyElem , N_VAR, N_FIELDS >::Particionar_malha (const int * buf) [inherited]
Definition at line 468 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::border, GeProb< ElemType, N_VAR, N_FIELDS >::el, EDGE::elemento, GeProb< ElemType, N_VAR, N_FIELDS >::myid, PARTICAO::nbor, GeProb< ElemType, N_VAR, N_FIELDS >::NBORDER, PARTICAO::nele, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, PARTICAO::ngho, GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP, GeProb< ElemType, N_VAR, N_FIELDS >::NumPart, EDGE::part_num, GeProb< ElemType, N_VAR, N_FIELDS >::Particao, EDGE::tipo, and GeProb< ElemType, N_VAR, N_FIELDS >::V.
preamble()
void DG_Prob::preamble (char * str)
Definition at line 15 of file DG_preamble.cpp.
References arq_eco, arq_flu, arq_rst, arq_sai, GeProb< MyElem, 2, 2 >::border, GeProb< MyElem, 2, 2 >::Comm, GeProb< MyElem, 2, 2 >::comm_size, count, GeProb< MyElem, 2, 2 >::el, EDGE::elemento, GeProb< MyElem, 2, 2 >::Field, GeProb< MyElem, 2, 2 >::FieldOfVar, EDGE::gbtrbind, gbtrpw, gbtrsn, PhElem< NumVariaveis >::get_trace_border_map(), PhElem< NumVariaveis >::inicia_gbtrbmap(), Ler_Arquivo_Dados_DG(), GeProb< MyElem, 2, 2 >::Ler_e_Processar_malha(), GeProb< MyElem, 2, 2 >::myid, GeProb< MyElem, 2, 2 >::NBORDER, Stdel::nborder_val(), GeProb< MyElem, 2, 2 >::NELEM, EDGE::num_local, GeProb< MyElem, 2, 2 >::NumFIELDS, GeProb< MyElem, 2, 2 >::NumVAR, Processa_condicoes_contorno(), PhElem< NumVariaveis >::set_stgbtrbmap(), PhElem< NumVariaveis >::show_ptr_stdel(), t, and EDGE::tipo.
Processa_condicoes_contorno()
void DG_Prob::Processa_condicoes_contorno ()
Definition at line 656 of file DG_Prob.cpp.
References aux, GeProb< MyElem, 2, 2 >::bflag, GeProb< MyElem, 2, 2 >::border, GeProb< MyElem, 2, 2 >::DNBC, Dtemp, GeProb< MyElem, 2, 2 >::el, EDGE::elemento, funcao_pdir(), funcao_sdir(), Gauss_Jacobi_parameters(), GeProb< MyElem, 2, 2 >::in_borders, MAXQ, EDGE::Na, EDGE::Nb, GeProb< MyElem, 2, 2 >::NBORDER, GeProb< MyElem, 2, 2 >::NG, GeProb< MyElem, 2, 2 >::nin, GeProb< MyElem, 2, 2 >::nout, GeProb< MyElem, 2, 2 >::out_borders, EDGE::pdir, qmax, EDGE::sdir, PhElem< NumVariaveis >::show_ptr_stdel(), t, EDGE::tipo, GeProb< MyElem, 2, 2 >::V, w, Vertice::x, and Vertice::y.
Referenced by preamble().
Processar_elementos()
void GeProb< MyElem , N_VAR, N_FIELDS >::Processar_elementos () [inherited]
Definition at line 307 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Aresta, GeProb< ElemType, N_VAR, N_FIELDS >::el, GeProb< ElemType, N_VAR, N_FIELDS >::Face, GeProb< ElemType, N_VAR, N_FIELDS >::Field, GeProb< ElemType, N_VAR, N_FIELDS >::FieldOfVar, MAXNL, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, GeProb< ElemType, N_VAR, N_FIELDS >::NF, GeProb< ElemType, N_VAR, N_FIELDS >::NG, GeProb< ElemType, N_VAR, N_FIELDS >::NL, GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP, GeProb< ElemType, N_VAR, N_FIELDS >::ptrHexahedral, GeProb< ElemType, N_VAR, N_FIELDS >::ptrLinear, GeProb< ElemType, N_VAR, N_FIELDS >::ptrQuadri, GeProb< ElemType, N_VAR, N_FIELDS >::ptrTetrahedral, and GeProb< ElemType, N_VAR, N_FIELDS >::ptrTriang.
projetar_C0()
void DG_Prob::projetar_C0 (FILE * file, double(*)(double, double, double) func, const int & ivar)
Definition at line 564 of file DG_Prob.cpp.
References DG_alocar_mem_local(), GeProb< MyElem, 2, 2 >::el, PhElem< NumVariaveis >::inicia_gbnmap(), DG_Elem::inicia_vetores(), GeProb< MyElem, 2, 2 >::NELEM, Stdel::nn_val(), npres, nsat, GeProb< MyElem, 2, 2 >::NumD, perm, porosidade, pres, PhElem< NumVariaveis >::projetar_C0(), Stdel::qborder_val(), qmax, sat, DG_Elem::set_fontes(), DG_Elem::set_permeabilidade(), DG_Elem::set_porosidade(), and PhElem< NumVariaveis >::show_ptr_stdel().
RenumerarNos() [1/2]
void GeProb< MyElem , N_VAR, N_FIELDS >::RenumerarNos () [inherited]
Definition at line 386 of file GeProb.hpp.
References a, GeProb< ElemType, N_VAR, N_FIELDS >::bflag, GeProb< ElemType, N_VAR, N_FIELDS >::NG, GeProb< ElemType, N_VAR, N_FIELDS >::novoNum, and GeProb< ElemType, N_VAR, N_FIELDS >::NumD.
RenumerarNos() [2/2]
void GeProb< MyElem , N_VAR, N_FIELDS >::RenumerarNos (int numf, int & ND) [inherited]
Definition at line 430 of file GeProb.hpp.
References a, GeProb< ElemType, N_VAR, N_FIELDS >::bflag, GeProb< ElemType, N_VAR, N_FIELDS >::NG, and GeProb< ElemType, N_VAR, N_FIELDS >::novoNum.
ResolverComTrilinos()
void GeProb< MyElem , N_VAR, N_FIELDS >::ResolverComTrilinos (const std::string Pack, Epetra_Map Map, Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS, double_t & norm_delta_X) [inherited]
Definition at line 734 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::AmesosSolverType, GeProb< ElemType, N_VAR, N_FIELDS >::Comm, e, GeProb< ElemType, N_VAR, N_FIELDS >::el, GeProb< ElemType, N_VAR, N_FIELDS >::myid, GeProb< ElemType, N_VAR, N_FIELDS >::NELEM, and GeProb< ElemType, N_VAR, N_FIELDS >::NumD.
Referenced by Ge_MVRA(), and Ge_MVRA0().
set_finput()
**********************************************************************************************************************************************************void GeProb< MyElem , N_VAR, N_FIELDS >::set_finput (FILE * ptr) [inherited]
Definition at line 243 of file GeProb.hpp.
set_fout()
void GeProb< MyElem , N_VAR, N_FIELDS >::set_fout (FILE * ptr) [inherited]
Definition at line 250 of file GeProb.hpp.
set_fout1()
void GeProb< MyElem , N_VAR, N_FIELDS >::set_fout1 (FILE * ptr) [inherited]
Definition at line 257 of file GeProb.hpp.
set_fout2()
void GeProb< MyElem , N_VAR, N_FIELDS >::set_fout2 (FILE * ptr) [inherited]
Definition at line 264 of file GeProb.hpp.
set_fout3()
void GeProb< MyElem , N_VAR, N_FIELDS >::set_fout3 (FILE * ptr) [inherited]
Definition at line 271 of file GeProb.hpp.
set_id()
void GeProb< MyElem , N_VAR, N_FIELDS >::set_id (const int rank, const int size) [inline], [inherited]
Definition at line 38 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::comm_size, GeProb< ElemType, N_VAR, N_FIELDS >::Marcar_condicoes_contorno(), GeProb< ElemType, N_VAR, N_FIELDS >::myid, GeProb< ElemType, N_VAR, N_FIELDS >::Processar_elementos(), GeProb< ElemType, N_VAR, N_FIELDS >::set_finput(), GeProb< ElemType, N_VAR, N_FIELDS >::set_fout(), GeProb< ElemType, N_VAR, N_FIELDS >::set_fout1(), GeProb< ElemType, N_VAR, N_FIELDS >::set_fout2(), GeProb< ElemType, N_VAR, N_FIELDS >::set_fout3(), GeProb< ElemType, N_VAR, N_FIELDS >::show_NELEM(), GeProb< ElemType, N_VAR, N_FIELDS >::show_NG(), and GeProb< ElemType, N_VAR, N_FIELDS >::show_NUMNP().
show_Comm()
Epetra_Comm* GeProb< MyElem , N_VAR, N_FIELDS >::show_Comm () [inline], [inherited]
Definition at line 22 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Comm.
show_NELEM()
int GeProb< MyElem , N_VAR, N_FIELDS >::show_NELEM () [inherited]
Definition at line 299 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::NELEM.
show_NF()
int GeProb< MyElem , N_VAR, N_FIELDS >::show_NF () [inline], [inherited]
Definition at line 55 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::NF.
show_NG()
int GeProb< MyElem , N_VAR, N_FIELDS >::show_NG () [inherited]
Definition at line 285 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::NG.
show_NL()
int GeProb< MyElem , N_VAR, N_FIELDS >::show_NL () [inline], [inherited]
Definition at line 54 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::NL.
show_NumD()
int GeProb< MyElem , N_VAR, N_FIELDS >::show_NumD () [inline], [inherited]
Definition at line 56 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::Construir_bordas(), GeProb< ElemType, N_VAR, N_FIELDS >::Facet_eco(), GeProb< ElemType, N_VAR, N_FIELDS >::gbnmap_continuous(), GeProb< ElemType, N_VAR, N_FIELDS >::gbnmap_discontinuous(), GeProb< ElemType, N_VAR, N_FIELDS >::Ler_e_Processar_malha(), GeProb< ElemType, N_VAR, N_FIELDS >::mesh_suporte(), GeProb< ElemType, N_VAR, N_FIELDS >::MPI_Recebe_Dados_GeProb(), GeProb< ElemType, N_VAR, N_FIELDS >::NumD, GeProb< ElemType, N_VAR, N_FIELDS >::Particionar_malha(), GeProb< ElemType, N_VAR, N_FIELDS >::RenumerarNos(), and GeProb< ElemType, N_VAR, N_FIELDS >::ResolverComTrilinos().
show_NUMNP()
int GeProb< MyElem , N_VAR, N_FIELDS >::show_NUMNP () [inherited]
Definition at line 292 of file GeProb.hpp.
References GeProb< ElemType, N_VAR, N_FIELDS >::NUMNP.
Member Data Documentation
AmesosSolverType
std::string GeProb< MyElem , N_VAR, N_FIELDS >::AmesosSolverType [protected], [inherited]
Definition at line 151 of file GeProb.hpp.
Referenced by Driver().
Aresta
std::vector<ARESTA> GeProb< MyElem , N_VAR, N_FIELDS >::Aresta [protected], [inherited]
Definition at line 113 of file GeProb.hpp.
arq_eco
char DG_Prob::arq_eco[256] [private]
string contendo o nome do arquivo para eco dos dados
Definition at line 135 of file DG_Prob.h.
Referenced by DG_eco(), and preamble().
arq_flu
char DG_Prob::arq_flu[256] [private]
string contendo o nome do arquivo de fluxos
Definition at line 136 of file DG_Prob.h.
Referenced by DG_Iterate(), and preamble().
arq_rst
char DG_Prob::arq_rst[256] [private]
string contendo o nome do arquivo para recomecar simulacao
Definition at line 133 of file DG_Prob.h.
Referenced by DG_initial_conditions(), DG_Iterate(), and preamble().
arq_sai
char DG_Prob::arq_sai[256] [private]
string contendo o nome do arquivo para saida dos resultados
Definition at line 134 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_initial_conditions(), DG_Iterate(), and preamble().
beta
double DG_Prob::beta [private]
Definition at line 157 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
bflag
std::vector<int> GeProb< MyElem , N_VAR, N_FIELDS >::bflag [protected], [inherited]
Definition at line 126 of file GeProb.hpp.
Referenced by Processa_condicoes_contorno().
border
EDGE* GeProb< MyElem , N_VAR, N_FIELDS >::border [protected], [inherited]
Definition at line 121 of file GeProb.hpp.
Referenced by DG_eco(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_MatrizVetor_Epetra(), DG_MatrizVetor_UMFPACK(), ED_Prob::preamble(), preamble(), and Processa_condicoes_contorno().
Comm
Epetra_Comm* GeProb< MyElem , N_VAR, N_FIELDS >::Comm [protected], [inherited]
Definition at line 79 of file GeProb.hpp.
Referenced by DG_initial_conditions(), DG_Iterate(), DG_MatrizVetor_Epetra(), Driver(), Eigenvectors(), Ge_MVRA(), Ge_MVRA0(), Ler_Arquivo_Dados_DG(), ED_Prob::preamble(), and preamble().
comm_size
int GeProb< MyElem , N_VAR, N_FIELDS >::comm_size [protected], [inherited]
Definition at line 90 of file GeProb.hpp.
Referenced by Ler_Arquivo_Dados_DG(), ED_Prob::preamble(), and preamble().
count
int DG_Prob::count [private]
Definition at line 128 of file DG_Prob.h.
Referenced by DG_EI_IG(), DG_EI_Interior(), DG_EI_Outflow(), DG_initial_conditions(), DG_Transfere_rst(), and preamble().
dim
int GeProb< MyElem , N_VAR, N_FIELDS >::dim [protected], [inherited]
Definition at line 104 of file GeProb.hpp.
Referenced by DG_eco().
DNBC
int GeProb< MyElem , N_VAR, N_FIELDS >::DNBC [protected], [inherited]
Definition at line 127 of file GeProb.hpp.
Referenced by Processa_condicoes_contorno().
Dt
double DG_Prob::Dt [private]
Intervalo de tempo; pode variar conforme falhe a convergencia.
Definition at line 138 of file DG_Prob.h.
Referenced by DG_conditionNumber(), DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
Dt0
double DG_Prob::Dt0 [private]
Intervalo de tempo inicial.
Definition at line 139 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), DG_Iterate(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
el
MyElem * GeProb< MyElem , N_VAR, N_FIELDS >::el [protected], [inherited]
Definition at line 115 of file GeProb.hpp.
Referenced by DG_eco(), DG_EI_Epetra_Inflow(), DG_EI_Epetra_Interior(), DG_EI_Epetra_Outflow(), DG_EI_flux(), DG_EI_IG(), DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), DG_MatrizVetor_Epetra(), DG_MatrizVetor_UMFPACK(), DG_Transfere_rst(), ED_Prob::preamble(), preamble(), Processa_condicoes_contorno(), projetar_C0(), ED_Prob::SolveElast2D_dyn(), and ~DG_Prob().
Face
std::vector<FACE> GeProb< MyElem , N_VAR, N_FIELDS >::Face [protected], [inherited]
Definition at line 114 of file GeProb.hpp.
facet
std::vector<FACET> GeProb< MyElem , N_VAR, N_FIELDS >::facet [protected], [inherited]
Definition at line 122 of file GeProb.hpp.
fatordt
double DG_Prob::fatordt [private]
fator de reducao do Dt
Definition at line 140 of file DG_Prob.h.
Referenced by DG_eco(), DG_Iterate(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
Field
Field_struct GeProb< MyElem , N_VAR, N_FIELDS >::Field[N_FIELDS] [protected], [inherited]
Definition at line 98 of file GeProb.hpp.
Referenced by DG_eco(), ED_Prob::preamble(), and preamble().
FieldOfVar
int GeProb< MyElem , N_VAR, N_FIELDS >::FieldOfVar[N_VAR] [protected], [inherited]
Definition at line 100 of file GeProb.hpp.
Referenced by ED_Prob::preamble(), and preamble().
fluids
Fluids DG_Prob::fluids [private]
Definition at line 159 of file DG_Prob.h.
Referenced by DG_EI_flux(), DG_EI_IG(), DG_EI_Inflow(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_MatrizVetor_Epetra(), and DG_MatrizVetor_UMFPACK().
gbtrpw
double* DG_Prob::gbtrpw [private]
Definition at line 165 of file DG_Prob.h.
Referenced by DG_imprimir_taxas_de_producao(), DG_MatrizVetor_Epetra(), DG_MatrizVetor_UMFPACK(), preamble(), and ~DG_Prob().
gbtrsn
double* DG_Prob::gbtrsn [private]
Definition at line 166 of file DG_Prob.h.
Referenced by DG_EI_flux(), DG_imprimir_taxas_de_producao(), DG_MatrizVetor_Epetra(), DG_MatrizVetor_UMFPACK(), preamble(), and ~DG_Prob().
gravidade
double DG_Prob::gravidade[3] [private]
Definition at line 154 of file DG_Prob.h.
Referenced by DG_eco(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
In
double DG_Prob::In [private]
Definition at line 151 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
in_borders
std::vector<int> GeProb< MyElem , N_VAR, N_FIELDS >::in_borders [protected], [inherited]
Definition at line 131 of file GeProb.hpp.
Referenced by DG_imprimir_taxas_de_producao(), DG_initial_conditions(), and Processa_condicoes_contorno().
injrate_n
double DG_Prob::injrate_n [private]
Definition at line 149 of file DG_Prob.h.
Referenced by DG_imprimir_taxas_de_producao().
injrate_n0
double DG_Prob::injrate_n0 [private]
Definition at line 152 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
injrate_w
double DG_Prob::injrate_w [private]
Definition at line 149 of file DG_Prob.h.
Referenced by DG_imprimir_taxas_de_producao().
injrate_w0
double DG_Prob::injrate_w0 [private]
Definition at line 152 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
Iw
double DG_Prob::Iw [private]
Definition at line 151 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
K_g_phi_n
double**** DG_Prob::K_g_phi_n [private]
gphi_# [dir][iq] = grad_phi
<
Parameters
dir = direcao da derivada
iq = indice do ponto de quadratura de Gauss
<trphi [elemento][variavel][modo][iq] = traco de phi
Parameters
Elemento da borda = 0 ou 1 (lado da borda)
Variavel = sat (=0) ou pres (=1)
Modo = numero do modo local
iq = indice do ponto de quadratura de GaussK_g_phi_n [iE][variavel][modo][iq] = Traco K * grad_phi . normal
iE = Elemento da borda = 0 ou 1 (lado da borda)
Variavel = sat (=0) ou pres (=1)
Modo = numero do modo local
iq = indice do ponto de quadratura de Gauss
Definition at line 198 of file DG_Prob.h.
Referenced by DG_alocar_mem_local(), DG_EI_Inflow(), DG_EI_Interior(), DG_EI_Outflow(), and DG_liberar_mem_local().
Kgpc
double*** DG_Prob::Kgpc [private]
Kgxx [iE][i][iq] = Traco de Kgrad_xx.
Parameters
iE = Elemento da borda = 0 ou 1 (lado da borda)
dir = direcao da derivada
iq = indice do ponto de quadratura de Gauss
Definition at line 171 of file DG_Prob.h.
Referenced by DG_alocar_mem_local(), DG_EI_flux(), DG_EI_IG(), and DG_liberar_mem_local().
Kgpw
double*** DG_Prob::Kgpw [private]
Definition at line 170 of file DG_Prob.h.
Referenced by DG_alocar_mem_local(), DG_EI_flux(), DG_EI_IG(), DG_EI_Interior(), and DG_liberar_mem_local().
Kgsn
double*** DG_Prob::Kgsn [private]
Definition at line 169 of file DG_Prob.h.
Referenced by DG_alocar_mem_local(), DG_EI_IG(), and DG_liberar_mem_local().
memoria_alocada
bool DG_Prob::memoria_alocada = false [private]
Definition at line 206 of file DG_Prob.h.
Referenced by DG_alocar_mem_local(), and DG_liberar_mem_local().
mun
double DG_Prob::mun [private]
Definition at line 131 of file DG_Prob.h.
Referenced by DG_eco(), DG_EI_flux(), DG_EI_IG(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
muw
double DG_Prob::muw [private]
Definition at line 131 of file DG_Prob.h.
Referenced by DG_eco(), DG_EI_flux(), DG_EI_IG(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
myid
int GeProb< MyElem , N_VAR, N_FIELDS >::myid [protected], [inherited]
Definition at line 89 of file GeProb.hpp.
Referenced by DG_eco(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), DG_MatrizVetor_Epetra(), Driver(), Ler_Arquivo_Dados_DG(), ED_Prob::preamble(), and preamble().
MyPID
int GeProb< MyElem , N_VAR, N_FIELDS >::MyPID [protected], [inherited]
Definition at line 84 of file GeProb.hpp.
Referenced by Eigenvectors().
NBC
int GeProb< MyElem , N_VAR, N_FIELDS >::NBC[20][3] [protected], [inherited]
Definition at line 128 of file GeProb.hpp.
NBORDER
int GeProb< MyElem , N_VAR, N_FIELDS >::NBORDER [protected], [inherited]
Definition at line 111 of file GeProb.hpp.
Referenced by DG_eco(), ED_Prob::preamble(), preamble(), and Processa_condicoes_contorno().
NDFCD
int GeProb< MyElem , N_VAR, N_FIELDS >::NDFCD [protected], [inherited]
Definition at line 108 of file GeProb.hpp.
NELEM
int GeProb< MyElem , N_VAR, N_FIELDS >::NELEM [protected], [inherited]
Definition at line 107 of file GeProb.hpp.
Referenced by DG_eco(), DG_Escrever_rst(), DG_initial_conditions(), DG_Iterate(), DG_Transfere_rst(), ED_Prob::preamble(), preamble(), projetar_C0(), ED_Prob::SolveElast2D_dyn(), and ~DG_Prob().
NF
int GeProb< MyElem , N_VAR, N_FIELDS >::NF [protected], [inherited]
Definition at line 110 of file GeProb.hpp.
Referenced by DG_eco().
NG
int GeProb< MyElem , N_VAR, N_FIELDS >::NG [protected], [inherited]
Definition at line 105 of file GeProb.hpp.
Referenced by Processa_condicoes_contorno(), and ED_Prob::SolveElast2D_dyn().
nin
int GeProb< MyElem , N_VAR, N_FIELDS >::nin [protected], [inherited]
Definition at line 129 of file GeProb.hpp.
Referenced by DG_imprimir_taxas_de_producao(), DG_initial_conditions(), and Processa_condicoes_contorno().
NL
int GeProb< MyElem , N_VAR, N_FIELDS >::NL [protected], [inherited]
Definition at line 109 of file GeProb.hpp.
Referenced by DG_eco(), and DG_initial_conditions().
nout
int GeProb< MyElem , N_VAR, N_FIELDS >::nout [protected], [inherited]
Definition at line 130 of file GeProb.hpp.
Referenced by DG_imprimir_taxas_de_producao(), DG_initial_conditions(), and Processa_condicoes_contorno().
novoNum
int* GeProb< MyElem , N_VAR, N_FIELDS >::novoNum [protected], [inherited]
Definition at line 117 of file GeProb.hpp.
Referenced by ED_Prob::SolveElast2D_dyn().
NumC
int GeProb< MyElem , N_VAR, N_FIELDS >::NumC [protected], [inherited]
Definition at line 95 of file GeProb.hpp.
Referenced by ED_Prob::SolveElast2D_dyn().
NumD
int GeProb< MyElem , N_VAR, N_FIELDS >::NumD [protected], [inherited]
Definition at line 94 of file GeProb.hpp.
Referenced by DG_eco(), DG_initial_conditions(), DG_Iterate(), DG_MatrizVetor_UMFPACK(), Driver(), projetar_C0(), and ED_Prob::SolveElast2D_dyn().
NumElemTypeents
int GeProb< MyElem , N_VAR, N_FIELDS >::NumElemTypeents [protected], [inherited]
Definition at line 86 of file GeProb.hpp.
NumFIELDS
const int GeProb< MyElem , N_VAR, N_FIELDS >::NumFIELDS [protected], [inherited]
Definition at line 97 of file GeProb.hpp.
Referenced by DG_eco(), and preamble().
NumGlobalElements
int GeProb< MyElem , N_VAR, N_FIELDS >::NumGlobalElements [protected], [inherited]
Definition at line 87 of file GeProb.hpp.
NUMNP
int GeProb< MyElem , N_VAR, N_FIELDS >::NUMNP [protected], [inherited]
Definition at line 106 of file GeProb.hpp.
Referenced by DG_eco().
NumPart
int GeProb< MyElem , N_VAR, N_FIELDS >::NumPart [protected], [inherited]
Numero de particoes.
Definition at line 135 of file GeProb.hpp.
Referenced by DG_MatrizVetor_UMFPACK().
NumProc
int GeProb< MyElem , N_VAR, N_FIELDS >::NumProc [protected], [inherited]
Definition at line 85 of file GeProb.hpp.
NumVAR
const int GeProb< MyElem , N_VAR, N_FIELDS >::NumVAR [protected], [inherited]
Definition at line 96 of file GeProb.hpp.
Referenced by DG_eco(), and preamble().
nz
int DG_Prob::nz [private]
Definition at line 129 of file DG_Prob.h.
Referenced by DG_initial_conditions().
out_borders
std::vector<int> GeProb< MyElem , N_VAR, N_FIELDS >::out_borders [protected], [inherited]
Definition at line 131 of file GeProb.hpp.
Referenced by DG_imprimir_taxas_de_producao(), DG_initial_conditions(), and Processa_condicoes_contorno().
Particao
std::vector<PARTICAO> GeProb< MyElem , N_VAR, N_FIELDS >::Particao [protected], [inherited]
Definition at line 136 of file GeProb.hpp.
Referenced by DG_MatrizVetor_Epetra(), and DG_MatrizVetor_UMFPACK().
passo
int DG_Prob::passo [private]
Definition at line 145 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_Iterate(), and DG_Transfere_rst().
pd
double DG_Prob::pd [private]
Definition at line 131 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
perm
double DG_Prob::perm [private]
Definition at line 155 of file DG_Prob.h.
Referenced by DG_eco(), DG_EI_IG(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), MPI_Recebe_Dados_DG(), and projetar_C0().
porosidade
double DG_Prob::porosidade [private]
Definition at line 132 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), MPI_Recebe_Dados_DG(), and projetar_C0().
precisao
double DG_Prob::precisao [private]
precisao da iteracao de Gauss
Definition at line 143 of file DG_Prob.h.
Referenced by DG_eco(), Ge_MVRA(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
prodrate_n
double DG_Prob::prodrate_n [private]
Definition at line 150 of file DG_Prob.h.
Referenced by DG_imprimir_taxas_de_producao().
prodrate_n0
double DG_Prob::prodrate_n0 [private]
Definition at line 153 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
prodrate_w
double DG_Prob::prodrate_w [private]
Definition at line 150 of file DG_Prob.h.
Referenced by DG_imprimir_taxas_de_producao().
prodrate_w0
double DG_Prob::prodrate_w0 [private]
Definition at line 153 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
ptrHexahedral
Hexahedral* GeProb< MyElem , N_VAR, N_FIELDS >::ptrHexahedral[N_FIELDS] [protected], [inherited]
Definition at line 143 of file GeProb.hpp.
ptrLinear
Linear* GeProb< MyElem , N_VAR, N_FIELDS >::ptrLinear[N_FIELDS] [protected], [inherited]
Definition at line 139 of file GeProb.hpp.
ptrQuadri
Quadrilateral* GeProb< MyElem , N_VAR, N_FIELDS >::ptrQuadri[N_FIELDS] [protected], [inherited]
Definition at line 141 of file GeProb.hpp.
ptrTetrahedral
Tetrahedral* GeProb< MyElem , N_VAR, N_FIELDS >::ptrTetrahedral[N_FIELDS] [protected], [inherited]
Definition at line 142 of file GeProb.hpp.
ptrTriang
Triangle* GeProb< MyElem , N_VAR, N_FIELDS >::ptrTriang[N_FIELDS] [protected], [inherited]
Definition at line 140 of file GeProb.hpp.
qdado
double DG_Prob::qdado [private]
Definition at line 144 of file DG_Prob.h.
Referenced by DG_eco(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
Qn
double DG_Prob::Qn [private]
Definition at line 151 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
Qw
double DG_Prob::Qw [private]
Definition at line 151 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), and DG_Transfere_rst().
restart_flag
int DG_Prob::restart_flag [private]
0 comeca; 1 continua
Definition at line 130 of file DG_Prob.h.
Referenced by DG_initial_conditions(), DG_Iterate(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
rhon
double DG_Prob::rhon [private]
Definition at line 131 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
rhow
double DG_Prob::rhow [private]
Definition at line 131 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
sigma
double DG_Prob::sigma [private]
Definition at line 156 of file DG_Prob.h.
Referenced by DG_conditionNumber(), DG_eco(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
sigma1
double DG_Prob::sigma1 [private]
Definition at line 156 of file DG_Prob.h.
Referenced by DG_conditionNumber(), DG_eco(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
solution
Teuchos::RCP<Epetra_Vector> GeProb< MyElem , N_VAR, N_FIELDS >::solution [protected], [inherited]
Definition at line 81 of file GeProb.hpp.
t
double DG_Prob::t [private]
tempo de simulacao
Definition at line 137 of file DG_Prob.h.
Referenced by DG_eco(), DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_initial_conditions(), DG_Iterate(), DG_MatrizVetor_Epetra(), DG_MatrizVetor_UMFPACK(), DG_Transfere_rst(), preamble(), and Processa_condicoes_contorno().
t_final
double DG_Prob::t_final [private]
tempo final de simulacao
Definition at line 141 of file DG_Prob.h.
Referenced by DG_eco(), DG_Iterate(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
theta
double DG_Prob::theta [private]
Definition at line 131 of file DG_Prob.h.
Referenced by DG_eco(), DG_initial_conditions(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
tnc
int DG_Prob::tnc [private]
Definition at line 146 of file DG_Prob.h.
Referenced by DG_Escrever_rst(), DG_imprimir_taxas_de_producao(), DG_Iterate(), and DG_Transfere_rst().
tncut
int DG_Prob::tncut [private]
Definition at line 147 of file DG_Prob.h.
Referenced by DG_eco(), DG_Iterate(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
tprint
double DG_Prob::tprint [private]
intervalo entre escritas de resultados no arquivo
Definition at line 142 of file DG_Prob.h.
Referenced by DG_eco(), DG_Iterate(), Ler_Arquivo_Dados_DG(), and MPI_Recebe_Dados_DG().
TrilinosSolver
std::string GeProb< MyElem , N_VAR, N_FIELDS >::TrilinosSolver [protected], [inherited]
Definition at line 150 of file GeProb.hpp.
Referenced by Driver(), Ge_MVRA(), and Ge_MVRA0().
V
Vertice* GeProb< MyElem , N_VAR, N_FIELDS >::V [protected], [inherited]
Definition at line 112 of file GeProb.hpp.
Referenced by DG_eco(), and Processa_condicoes_contorno().
The documentation for this class was generated from the following files:
DG_Prob.h
DG_driver.cpp
DG_eco.cpp
DG_EI_flux.cpp
DG_EI_Inflow_a.cpp
DG_EI_Inflow_b.cpp
DG_EI_Interior.cpp
DG_EI_Interior_a.cpp
DG_EI_Interior_b.cpp
DG_EI_Outflow.cpp
DG_EI_Outflow_a.cpp
DG_EI_Outflow_b.cpp
DG_Eigenvectors.cpp
DG_IG_EI.cpp
DG_Iterate.cpp
DG_MVRA.cpp
DG_preamble.cpp
DG_Prob.cpp
DG_saidas_intermediarias.cpp
Transfere_rst.cpp