Mode Class Reference
#include <spectral.h>
Public Member Functions
Mode (int ap=0, int aq=0, int ar=0)
void set_mode (int ap, int aq, int ar)
int p_val ()
int q_val ()
int r_val ()
void print (FILE *fout=nullptr)
Private Attributes
int p
int q
int r
Detailed Description
mode
integers specifying the order of the modes in the local x,y and z directions, respectively.
Parameters
p = order of the mode in the x-direction
q = order of the mode in the y-direction
r = order of the mode in the z-direction
Definition at line 80 of file spectral.h.
Constructor & Destructor Documentation
Mode()
Mode::Mode (int ap = 0, int aq = 0, int ar = 0) [inline]
Definition at line 85 of file spectral.h.
Member Function Documentation
p_val()
int Mode::p_val () [inline]
Definition at line 87 of file spectral.h.
Referenced by Hexahedral::computeAtPoints(), Quadrilateral::computeAtPoints(), Tetrahedral::computeAtPoints(), Triangle::computeAtPoints(), Linear::computeAtPoints(), Triangle::computeVertice(), Quadrilateral::computeVertice(), Linear::computeVertice(), Hexahedral::computeVertice(), Tetrahedral::computeVertice(), Triangle::elem_traces(), Hexahedral::elem_traces(), Quadrilateral::elem_traces(), Linear::elem_traces(), Quadrilateral::eval_GradPhi(), Hexahedral::eval_GradPhi(), Tetrahedral::evalGQ(), Linear::make_local_matrices(), Quadrilateral::make_local_matrices(), Tetrahedral::make_local_matrices(), Hexahedral::make_local_matrices(), Triangle::make_local_matrices(), Quadrilateral::mass(), Triangle::mass(), Linear::mass(), Tetrahedral::mass(), Hexahedral::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Hexahedral::set(), Triangle::set(), Linear::set(), Quadrilateral::set(), Stdel::show_ind(), Linear::vector_of_integral_of_f_Phi_dv(), Hexahedral::vector_of_integral_of_f_Phi_dv(), Quadrilateral::vector_of_integral_of_f_Phi_dv(), Tetrahedral::vector_of_integral_of_f_Phi_dv(), and Triangle::vector_of_integral_of_f_Phi_dv().
print()
void Mode::print (FILE * fout = nullptr) [inline]
Definition at line 90 of file spectral.h.
Referenced by Hexahedral::localFaceModeMap(), Tetrahedral::localFaceModeMap(), Linear::print(), Quadrilateral::print(), Hexahedral::print(), and Triangle::print().
q_val()
int Mode::q_val () [inline]
Definition at line 88 of file spectral.h.
Referenced by Hexahedral::computeAtPoints(), Quadrilateral::computeAtPoints(), Tetrahedral::computeAtPoints(), Triangle::computeAtPoints(), Quadrilateral::computeVertice(), Tetrahedral::computeVertice(), Triangle::computeVertice(), Hexahedral::computeVertice(), Hexahedral::elem_traces(), Quadrilateral::elem_traces(), Triangle::elem_traces(), Quadrilateral::eval_GradPhi(), Hexahedral::eval_GradPhi(), Tetrahedral::evalGQ(), Tetrahedral::make_local_matrices(), Quadrilateral::make_local_matrices(), Hexahedral::make_local_matrices(), Triangle::make_local_matrices(), Tetrahedral::mass(), Quadrilateral::mass(), Hexahedral::mass(), Triangle::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Quadrilateral::set(), Hexahedral::set(), Triangle::set(), Stdel::show_ind(), Tetrahedral::vector_of_integral_of_f_Phi_dv(), Quadrilateral::vector_of_integral_of_f_Phi_dv(), Hexahedral::vector_of_integral_of_f_Phi_dv(), and Triangle::vector_of_integral_of_f_Phi_dv().
r_val()
int Mode::r_val () [inline]
Definition at line 89 of file spectral.h.
Referenced by Tetrahedral::computeAtPoints(), Tetrahedral::computeVertice(), Tetrahedral::evalGQ(), Tetrahedral::make_local_matrices(), Hexahedral::make_local_matrices(), Hexahedral::mass(), Tetrahedral::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Hexahedral::set(), Stdel::show_ind(), Tetrahedral::vector_of_integral_of_f_Phi_dv(), and Hexahedral::vector_of_integral_of_f_Phi_dv().
set_mode()
void Mode::set_mode (int ap, int aq, int ar) [inline]
Definition at line 86 of file spectral.h.
Referenced by Hexahedral::set(), Triangle::set(), Tetrahedral::set(), Quadrilateral::set(), and Linear::set().
Member Data Documentation
p
int Mode::p [private]
Definition at line 94 of file spectral.h.
q
int Mode::q [private]
Definition at line 94 of file spectral.h.
r
int Mode::r [private]
Definition at line 94 of file spectral.h.
The documentation for this class was generated from the following file:
spectral.h