PhElem< NumVariaveis > Class Template Reference
#include <PhElem.hpp>
Public Member Functions
PhElem ()
~PhElem ()
void inicia_vetores ()
void finaliza_vetores ()
int show_NumLocalVars ()
void teste ()
void set_ptr_stdel (Stdel *pointer, Stdel *pointer1)
void set_ptr_stdel (Stdel *pointers[])
void set_ptr_stdel (Stdel *pointer)
void set_ptr_stdel_var (const int ind, Stdel *pointer)
void set_Vert_map (const int &n_in, int ver_temp[])
void set_ptvert (const Vertice *pointer)
void read_vertices (FILE *, const int &)
void set_sgn ()
int show_sgn (const int &ia, const int &i)
const int show_gbnmap (int ivar, int modo) const
int show_numv ()
int show_nume ()
int show_numf ()
void set_type (const int &num)
int type_val ()
void print_numeracao (FILE *fout, const int &k)
void print_modes (FILE *fout, const int &k) const
void zera_vetores (const int &k)
void zera_bs (const int &k)
void make_vector (const int &ia, double(*f)(double, double, double))
void make_vector_Elast2D_dyn (const double a[])
void make_Kcomp_Elast2D (const double lambda, const double mu)
void make_Kcomp_Elast2D_dyn (const double lambda, const double mu, const double a[])
void make_K_Elast2D (const double lambda, const double mu, double **K)
void VectorElast2D (const int &i, double sum[])
void VectorElast2D (double vector[])
void P_eval_print_Elast2D (FILE *fout, const double X[], double lambda, double mu)
void P_eval_print_Elast2D_dyn (FILE *fout, const int &prnflag, const double X[], double lambda, double mu, const double a[])
void make_K_Imiscivel2F (const double, const double, const double, const double, const double [], double(*)(double), double(*)(double), double(*)(double))
double Kcomp (const int &i, const int &j)
double K_Imisc2F (const int &i, const int &j)
void make_Vector_Eq_S1 (const double, const double, const double, const double, const double [3], double(*)(double))
int map (const int &var, const int &no_local)
void mapa_inverso (const int &ivar, const double X[])
void P_eval_u (const double X[])
void P_eval_u (const double X[], const int &ia)
void P_eval_u_p1 (const double X[], const int &ia)
void P_eval_print (const double X[], const int &numf, FILE *fout, double(*)(double, double, double))
void P_print (const int &numf, FILE *file)
void P_eval_vert (const double X[], double f_vert[])
void P_eval_phys (const int &numf, double f0[])
void Increment_field (const double X[], const int &numf, const double dt)
void compute_JV (const int &ia)
void print_matrices (FILE *fout)
void Processar_dados (int &NL, std::vector< ARESTA > &aresta, int &NF, std::vector< FACE > &face_vec)
void check_connectivity (FILE *fout, const int &ia)
void assign_gbnmap (const int &ia, const int &i, const int &val)
void inicia_gbnmap (int &count)
void inicia_gbnmap (const int &ivar, int &count)
void inicia_gbtrbmap (int &count)
void set_gbnmap (const int &ia, const int gbnmap_temp[], const int sgn_temp[])
void set_stgbtrbmap (const int &b, const int &vmapM, const int &vmapP)
int show_gbtrbmap ()
int show_stgbtrbmapM (const int &a)
int show_stgbtrbmapP (const int &a)
void check_gradiente (FILE *fout, const int &ia)
Stdel * show_ptr_stdel (const int &n) const
void BoundCond (const int &face, int bflag[], double bc[], double(*func)(double, double, double), const int &nf, const int &bndtype)
void Neumann (const int &aresta, const int &varn, const double rho1, const double mu1, const double rho2, const double mu2, const double gravidade[])
double show_u (const int &i)
double show_u (const int &, const int &)
double show_b0 (const int &i)
double show_b0 (const int &, const int &)
double show_bs (const int &, const int &)
double show_J ()
void make_MassMatrices ()
int show_Vert_map (int i)
int show_Aresta (int i)
int show_Face (int i)
int show_sinal (int i)
int show_border_num (int i)
int show_part_num ()
void set_part_num (const int &num=-1)
double Phi_val (const int &var, const int &ind, const int &pos)
void projetar_C0 (FILE *file, double(*func)(double, double, double), const int &ivar)
void transformacao_direta (double f[], const int &ivar)
void teste_transformacao_direta (FILE *fin, FILE *fout, const int &npoints, const double coord[])
void set_border_tipo (EDGE *border, const int &aresta, const int &t)
void set_border_num (const int &aresta, const int &num)
void Imprimir_valores (FILE *fileout, const int &npoints, const double coord[])
void printwGQJ (FILE *fileout)
void Avancar_u0 (const double X[], const double relax=1.0)
void Atualizar_u0 (const double X[])
void Copia_u0_em_ (double X[])
void Copia_u0_em_ (Teuchos::RCP< Epetra_Vector > X)
void Comparar_u0 (const double X[])
void Salvar_u0 ()
void Restaurar_u0 ()
void escrever_restart (FILE *fout)
void ler_restart (FILE *fin)
void ler_restart_buffer (FILE *fin, double *buff, int &count)
void restart_element (double *buff, int &count)
void teste_gradiente ()
int get_trace_border_map (const int &aresta)
void gbnmap_vertices (std::vector< std::vector< int >> gbn)
void gbnmap_vertices (int *gbn, const int &ivar)
void gbnmap_faces (const int face_vec[], const int &ivar)
void gbnmap_aresta (const int &aresta, const int &sinal, const int &ivar, const int &count, int &inc)
void gbnmap_arestas (const int aresta_vec[], const int &ivar)
void gbnmap_interior (const int &ivar, int &count)
void anexa_gbnmap (const int &ivar, vector< int > &)
void vetor_superficie (const int &num_local, double &area, double normal[3])
Protected Attributes
Stdel * ptr_stdel [NumVariaveis]
int type
const Vertice * ptvert
int NumLocalVars = NumVariaveis
int ndim
Spatial dimension.
int numv
Number of vertices.
int nume
Number of edges.
int numf
Number of faces.
int numborders
Number of borders in the element.
int numn [NumVariaveis]
int numb [NumVariaveis]
int Vert_map [8]
int aresta_map [12]
int face_map [6]
int border_num [12]
int sinal [12]
sinal refers to the borders
int part_num
numero da particao a qual pertence
int gbnmap [NumVariaveis][MAXNN]
mapping from local to global nodes (or modes)
int sgn [NumVariaveis][MAXNN]
sign of the local mode (or mode)
double J
Jacobian from the physical to the standard element.
double * JV
Ponteiro para matriz do Jacobiano nos pontos gaussianos;.
double * b0 [NumVariaveis]
[MAXMODES*MAXNFIELDS]; vector of body forces
double * bs [NumVariaveis]
vector of force boundary conditions
double * u0 [NumVariaveis]
vector with the coefficients of each mode
double * usave [NumVariaveis]
int gbtrbmap
Beginning index on the global array where the local border Gauss quadrature points (traces) are mapped; this map facilitates the use of mpi for paralell calculations over element borders.
int * stgbtrbmapM
Array containing the start point in the global trace array of the internal trace of the border.
int * stgbtrbmapP
Array containing the start point in the global trace array of the external trace of the border.
int vetores_iniciados
Detailed Description
template<int NumVariaveis>
class PhElem< NumVariaveis >
Physical Elements
Definition at line 20 of file PhElem.hpp.
Constructor & Destructor Documentation
PhElem()
template<int NumVariaveis>
PhElem< NumVariaveis >::PhElem ()
Definition at line 229 of file PhElem.hpp.
 PhElem()
template<int NumVariaveis>
PhElem< NumVariaveis >::~PhElem () [inline]
Definition at line 25 of file PhElem.hpp.
Member Function Documentation
anexa_gbnmap()
template<int NumVariaveis>
void PhElem< NumVariaveis >::anexa_gbnmap (const int & ivar, vector< int > & list)
Definition at line 308 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
assign_gbnmap()
template<int NumVariaveis>
void PhElem< NumVariaveis >::assign_gbnmap (const int & ia, const int & i, const int & val)
Definition at line 830 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
Atualizar_u0()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Atualizar_u0 (const double X[])
Definition at line 377 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
Avancar_u0()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Avancar_u0 (const double X[], const double relax = 1.0)
Definition at line 342 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
BoundCond()
template<int NumVariaveis>
void PhElem< NumVariaveis >::BoundCond (const int & face, int bflag[], double bc[], double(*)(double, double, double) func, const int & nf, const int & bndtype)
Referenced by PhElem< 2 >::show_stgbtrbmapP().
check_connectivity()
template<int NumVariaveis>
void PhElem< NumVariaveis >::check_connectivity (FILE * fout, const int & ia)
Definition at line 800 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
check_gradiente()
template<int NumVariaveis>
void PhElem< NumVariaveis >::check_gradiente (FILE * fout, const int & ia)
Definition at line 811 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_stgbtrbmapP().
Comparar_u0()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Comparar_u0 (const double X[])
Definition at line 358 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
compute_JV()
template<int NumVariaveis>
void PhElem< NumVariaveis >::compute_JV (const int & ia)
Definition at line 1376 of file PhElem.hpp.
Referenced by PhElem< 2 >::inicia_vetores(), and PhElem< 2 >::show_numf().
Copia_u0_em_() [1/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::Copia_u0_em_ (double X[])
Definition at line 293 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
Copia_u0_em_() [2/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::Copia_u0_em_ (Teuchos::RCP< Epetra_Vector > X)
Definition at line 300 of file PhElem.hpp.
escrever_restart()
template<int NumVariaveis>
void PhElem< NumVariaveis >::escrever_restart (FILE * fout)
Definition at line 242 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
finaliza_vetores()
template<int NumVariaveis>
void PhElem< NumVariaveis >::finaliza_vetores ()
Definition at line 1897 of file PhElem.hpp.
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::~PhElem().
gbnmap_aresta()
template<int NumVariaveis>
void PhElem< NumVariaveis >::gbnmap_aresta (const int & aresta, const int & sinal, const int & ivar, const int & count, int & inc)
Definition at line 1719 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
gbnmap_arestas()
template<int NumVariaveis>
void PhElem< NumVariaveis >::gbnmap_arestas (const int aresta_vec[], const int & ivar)
Definition at line 1832 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
gbnmap_faces()
template<int NumVariaveis>
void PhElem< NumVariaveis >::gbnmap_faces (const int face_vec[], const int & ivar)
Definition at line 1754 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
gbnmap_interior()
template<int NumVariaveis>
void PhElem< NumVariaveis >::gbnmap_interior (const int & ivar, int & count)
Definition at line 1742 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
gbnmap_vertices() [1/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::gbnmap_vertices (std::vector< std::vector< int >> gbn)
Definition at line 1696 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_vertices(), and PhElem< 2 >::Phi_val().
gbnmap_vertices() [2/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::gbnmap_vertices (int * gbn, const int & ivar)
get_trace_border_map()
template<int NumVariaveis>
int PhElem< NumVariaveis >::get_trace_border_map (const int & aresta)
Definition at line 520 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val(), ED_Prob::preamble(), and DG_Prob::preamble().
Imprimir_valores()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Imprimir_valores (FILE * fileout, const int & npoints, const double coord[])
Referenced by PhElem< 2 >::Phi_val().
Increment_field()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Increment_field (const double X[], const int & numf, const double dt)
Referenced by PhElem< 2 >::show_numf().
inicia_gbnmap() [1/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::inicia_gbnmap (int & count)
Definition at line 838 of file PhElem.hpp.
Referenced by DG_Prob::DG_initial_conditions(), Tetrahedral::Dirichlet(), Hexahedral::Dirichlet(), PhElem< 2 >::inicia_gbnmap(), DG_Prob::projetar_C0(), and PhElem< 2 >::show_numf().
inicia_gbnmap() [2/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::inicia_gbnmap (const int & ivar, int & count)
Definition at line 846 of file PhElem.hpp.
inicia_gbtrbmap()
template<int NumVariaveis>
void PhElem< NumVariaveis >::inicia_gbtrbmap (int & count)
Definition at line 856 of file PhElem.hpp.
Referenced by ED_Prob::preamble(), DG_Prob::preamble(), and PhElem< 2 >::show_numf().
inicia_vetores()
template<int NumVariaveis>
void PhElem< NumVariaveis >::inicia_vetores ()
Definition at line 1858 of file PhElem.hpp.
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::~PhElem().
K_Imisc2F()
template<int NumVariaveis>
double PhElem< NumVariaveis >::K_Imisc2F (const int & i, const int & j)
Referenced by PhElem< 2 >::show_numf().
Kcomp()
template<int NumVariaveis>
double PhElem< NumVariaveis >::Kcomp (const int & i, const int & j)
Definition at line 183 of file Elastostatica.cpp.
Referenced by PhElem< 2 >::show_numf().
ler_restart()
template<int NumVariaveis>
void PhElem< NumVariaveis >::ler_restart (FILE * fin)
Definition at line 252 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
ler_restart_buffer()
template<int NumVariaveis>
void PhElem< NumVariaveis >::ler_restart_buffer (FILE * fin, double * buff, int & count)
Definition at line 261 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
make_K_Elast2D()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_K_Elast2D (const double lambda, const double mu, double ** K)
Definition at line 7 of file Elastostatica.cpp.
Referenced by PhElem< 2 >::make_Kcomp_Elast2D(), and PhElem< 2 >::show_numf().
make_K_Imiscivel2F()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_K_Imiscivel2F (const double , const double , const double , const double , const double [], double(*)(double) , double(*)(double) , double(*)(double))
Referenced by PhElem< 2 >::show_numf().
make_Kcomp_Elast2D()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_Kcomp_Elast2D (const double lambda, const double mu)
Definition at line 197 of file Elastostatica.cpp.
Referenced by PhElem< 2 >::show_numf().
make_Kcomp_Elast2D_dyn()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_Kcomp_Elast2D_dyn (const double lambda, const double mu, const double a[])
Definition at line 386 of file Elastodinamica2D.cpp.
Referenced by PhElem< 2 >::show_numf(), and ED_Prob::SolveElast2D_dyn().
make_MassMatrices()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_MassMatrices ()
Referenced by PhElem< 2 >::show_J().
make_vector()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_vector (const int & ia, double(*)(double, double, double) f)
Referenced by PhElem< 2 >::make_Kcomp_Elast2D(), and PhElem< 2 >::show_numf().
make_vector_Elast2D_dyn()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_vector_Elast2D_dyn (const double a[])
Definition at line 369 of file Elastodinamica2D.cpp.
Referenced by PhElem< 2 >::show_numf(), and ED_Prob::SolveElast2D_dyn().
make_Vector_Eq_S1()
template<int NumVariaveis>
void PhElem< NumVariaveis >::make_Vector_Eq_S1 (const double , const double , const double , const double , const double [3], double(*)(double))
Referenced by PhElem< 2 >::show_numf().
map()
template<int NumVariaveis>
int PhElem< NumVariaveis >::map (const int & var, const int & no_local)
Definition at line 573 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco(), DG_Prob::DG_EI_IG(), DG_Prob::DG_EI_Inflow(), DG_Prob::DG_EI_Interior(), DG_Prob::DG_EI_Outflow(), PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::show_numf(), and ED_Prob::SolveElast2D_dyn().
mapa_inverso()
template<int NumVariaveis>
void PhElem< NumVariaveis >::mapa_inverso (const int & ivar, const double X[])
Definition at line 280 of file PhElem.hpp.
Referenced by DG_Prob::DG_initial_conditions(), and PhElem< 2 >::show_numf().
Neumann()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Neumann (const int & aresta, const int & varn, const double rho1, const double mu1, const double rho2, const double mu2, const double gravidade[])
Referenced by PhElem< 2 >::show_stgbtrbmapP().
P_eval_phys()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_phys (const int & numf, double f0[])
Definition at line 617 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
P_eval_print()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_print (const double X[], const int & numf, FILE * fout, double(*)(double, double, double))
Referenced by PhElem< 2 >::show_numf().
P_eval_print_Elast2D()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_print_Elast2D (FILE * fout, const double X[], double lambda, double mu)
Definition at line 88 of file Elastostatica.cpp.
Referenced by PhElem< 2 >::show_numf().
P_eval_print_Elast2D_dyn()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_print_Elast2D_dyn (FILE * fout, const int & prnflag, const double X[], double lambda, double mu, const double a[])
Definition at line 458 of file Elastodinamica2D.cpp.
Referenced by PhElem< 2 >::show_numf(), and ED_Prob::SolveElast2D_dyn().
P_eval_u() [1/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_u (const double X[])
Referenced by PhElem< 2 >::show_numf().
P_eval_u() [2/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_u (const double X[], const int & ia)
P_eval_u_p1()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_u_p1 (const double X[], const int & ia)
Referenced by PhElem< 2 >::show_numf().
P_eval_vert()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_eval_vert (const double X[], double f_vert[])
Referenced by PhElem< 2 >::show_numf().
P_print()
template<int NumVariaveis>
void PhElem< NumVariaveis >::P_print (const int & numf, FILE * file)
Definition at line 631 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
Phi_val()
template<int NumVariaveis>
double PhElem< NumVariaveis >::Phi_val (const int & var, const int & ind, const int & pos) [inline]
Definition at line 140 of file PhElem.hpp.
print_matrices()
template<int NumVariaveis>
void PhElem< NumVariaveis >::print_matrices (FILE * fout)
Referenced by PhElem< 2 >::show_numf().
print_modes()
template<int NumVariaveis>
void PhElem< NumVariaveis >::print_modes (FILE * fout, const int & k) const
Definition at line 551 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
print_numeracao()
template<int NumVariaveis>
void PhElem< NumVariaveis >::print_numeracao (FILE * fout, const int & k)
Definition at line 541 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
printwGQJ()
template<int NumVariaveis>
void PhElem< NumVariaveis >::printwGQJ (FILE * fileout)
Definition at line 316 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
Processar_dados()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Processar_dados (int & NL, std::vector< ARESTA > & aresta, int & NF, std::vector< FACE > & face_vec)
Definition at line 682 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
projetar_C0()
template<int NumVariaveis>
void PhElem< NumVariaveis >::projetar_C0 (FILE * file, double(*)(double, double, double) func, const int & ivar)
Definition at line 880 of file PhElem.hpp.
Referenced by DG_Prob::DG_initial_conditions(), Tetrahedral::Dirichlet(), Hexahedral::Dirichlet(), PhElem< 2 >::Phi_val(), and DG_Prob::projetar_C0().
read_vertices()
template<int NumVariaveis>
void PhElem< NumVariaveis >::read_vertices (FILE * finput, const int & nv)
Definition at line 563 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_NumLocalVars().
restart_element()
template<int NumVariaveis>
void PhElem< NumVariaveis >::restart_element (double * buff, int & count)
Definition at line 270 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
Restaurar_u0()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Restaurar_u0 ()
Definition at line 333 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
Salvar_u0()
template<int NumVariaveis>
void PhElem< NumVariaveis >::Salvar_u0 ()
Definition at line 325 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
set_border_num()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_border_num (const int & aresta, const int & num)
Definition at line 514 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
set_border_tipo()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_border_tipo (EDGE * border, const int & aresta, const int & t)
Definition at line 503 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
set_gbnmap()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_gbnmap (const int & ia, const int gbnmap_temp[], const int sgn_temp[])
Definition at line 789 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_numf().
set_part_num()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_part_num (const int & num = -1)
Definition at line 1406 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_part_num().
set_ptr_stdel() [1/3]
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_ptr_stdel (Stdel * pointer, Stdel * pointer1)
Definition at line 460 of file PhElem.hpp.
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::show_NumLocalVars().
set_ptr_stdel() [2/3]
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_ptr_stdel (Stdel * pointers[])
Definition at line 482 of file PhElem.hpp.
set_ptr_stdel() [3/3]
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_ptr_stdel (Stdel * pointer)
Definition at line 452 of file PhElem.hpp.
set_ptr_stdel_var()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_ptr_stdel_var (const int ind, Stdel * pointer)
Definition at line 474 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_NumLocalVars().
set_ptvert()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_ptvert (const Vertice * pointer)
Definition at line 493 of file PhElem.hpp.
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::show_NumLocalVars().
set_sgn()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_sgn ()
Referenced by PhElem< 2 >::show_NumLocalVars().
set_stgbtrbmap()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_stgbtrbmap (const int & b, const int & vmapM, const int & vmapP)
Definition at line 870 of file PhElem.hpp.
Referenced by ED_Prob::preamble(), DG_Prob::preamble(), and PhElem< 2 >::show_numf().
set_type()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_type (const int & num)
Definition at line 529 of file PhElem.hpp.
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::show_numf().
set_Vert_map()
template<int NumVariaveis>
void PhElem< NumVariaveis >::set_Vert_map (const int & n_in, int ver_temp[])
Definition at line 774 of file PhElem.hpp.
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::show_NumLocalVars().
show_Aresta()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_Aresta (int i) [inline]
Definition at line 133 of file PhElem.hpp.
show_b0() [1/2]
template<int NumVariaveis>
double PhElem< NumVariaveis >::show_b0 (const int & i)
Referenced by PhElem< 2 >::show_stgbtrbmapP().
show_b0() [2/2]
template<int NumVariaveis>
double PhElem< NumVariaveis >::show_b0 (const int & var, const int & no)
Definition at line 602 of file PhElem.hpp.
show_border_num()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_border_num (int i) [inline]
Definition at line 136 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco().
show_bs()
template<int NumVariaveis>
double PhElem< NumVariaveis >::show_bs (const int & var, const int & no)
Definition at line 609 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_stgbtrbmapP().
show_Face()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_Face (int i) [inline]
Definition at line 134 of file PhElem.hpp.
show_gbnmap()
template<int NumVariaveis>
const int PhElem< NumVariaveis >::show_gbnmap (int ivar, int modo) const [inline]
Definition at line 39 of file PhElem.hpp.
show_gbtrbmap()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_gbtrbmap () [inline]
Definition at line 105 of file PhElem.hpp.
show_J()
template<int NumVariaveis>
double PhElem< NumVariaveis >::show_J () [inline]
Definition at line 129 of file PhElem.hpp.
show_nume()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_nume () [inline]
Definition at line 41 of file PhElem.hpp.
show_numf()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_numf () [inline]
Definition at line 42 of file PhElem.hpp.
show_NumLocalVars()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_NumLocalVars () [inline]
Definition at line 28 of file PhElem.hpp.
Referenced by ED_Prob::SolveElast2D_dyn().
show_numv()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_numv () [inline]
Definition at line 40 of file PhElem.hpp.
show_part_num()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_part_num () [inline]
Definition at line 137 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco().
show_ptr_stdel()
template<int NumVariaveis>
Stdel * PhElem< NumVariaveis >::show_ptr_stdel (const int & n) const
Definition at line 588 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco(), DG_Prob::DG_EI_Epetra_Inflow(), DG_Prob::DG_EI_Epetra_Interior(), DG_Prob::DG_EI_Epetra_Outflow(), DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), DG_Prob::DG_EI_Inflow(), DG_Prob::DG_EI_Interior(), DG_Prob::DG_EI_Outflow(), DG_Prob::DG_initial_conditions(), ED_Prob::preamble(), DG_Prob::preamble(), DG_Prob::Processa_condicoes_contorno(), DG_Prob::projetar_C0(), PhElem< 2 >::show_stgbtrbmapP(), and DG_Prob::~DG_Prob().
show_sgn()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_sgn (const int & ia, const int & i) [inline]
Definition at line 38 of file PhElem.hpp.
show_sinal()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_sinal (int i) [inline]
Definition at line 135 of file PhElem.hpp.
show_stgbtrbmapM()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_stgbtrbmapM (const int & a) [inline]
Definition at line 106 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco().
show_stgbtrbmapP()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_stgbtrbmapP (const int & a) [inline]
Definition at line 107 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco().
show_u() [1/2]
template<int NumVariaveis>
double PhElem< NumVariaveis >::show_u (const int & i)
Referenced by Hexahedral::Dirichlet(), Tetrahedral::Dirichlet(), and PhElem< 2 >::show_stgbtrbmapP().
show_u() [2/2]
template<int NumVariaveis>
double PhElem< NumVariaveis >::show_u (const int & var, const int & no)
Definition at line 595 of file PhElem.hpp.
show_Vert_map()
template<int NumVariaveis>
int PhElem< NumVariaveis >::show_Vert_map (int i) [inline]
Definition at line 132 of file PhElem.hpp.
teste()
template<int NumVariaveis>
void PhElem< NumVariaveis >::teste ()
Definition at line 189 of file Elastostatica.cpp.
Referenced by PhElem< 2 >::show_NumLocalVars().
teste_gradiente()
template<int NumVariaveis>
void PhElem< NumVariaveis >::teste_gradiente ()
Definition at line 1426 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
teste_transformacao_direta()
template<int NumVariaveis>
void PhElem< NumVariaveis >::teste_transformacao_direta (FILE * fin, FILE * fout, const int & npoints, const double coord[])
Referenced by PhElem< 2 >::Phi_val().
transformacao_direta()
template<int NumVariaveis>
void PhElem< NumVariaveis >::transformacao_direta (double f[], const int & ivar)
Definition at line 980 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
type_val()
template<int NumVariaveis>
int PhElem< NumVariaveis >::type_val ()
Definition at line 535 of file PhElem.hpp.
Referenced by DG_Prob::DG_eco(), and PhElem< 2 >::show_numf().
VectorElast2D() [1/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::VectorElast2D (const int & i, double sum[])
Referenced by PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::show_numf(), and ED_Prob::SolveElast2D_dyn().
VectorElast2D() [2/2]
template<int NumVariaveis>
void PhElem< NumVariaveis >::VectorElast2D (double vector[])
Definition at line 161 of file Elastostatica.cpp.
vetor_superficie()
template<int NumVariaveis>
void PhElem< NumVariaveis >::vetor_superficie (const int & num_local, double & area, double normal[3])
Definition at line 1487 of file PhElem.hpp.
Referenced by PhElem< 2 >::Phi_val().
zera_bs()
template<int NumVariaveis>
void PhElem< NumVariaveis >::zera_bs (const int & k)
Referenced by PhElem< 2 >::show_numf().
zera_vetores()
template<int NumVariaveis>
void PhElem< NumVariaveis >::zera_vetores (const int & k)
Referenced by PhElem< 2 >::show_numf().
Member Data Documentation
aresta_map
template<int NumVariaveis>
int PhElem< NumVariaveis >::aresta_map[12] [protected]
Definition at line 195 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::show_Aresta().
b0
template<int NumVariaveis>
double* PhElem< NumVariaveis >::b0[NumVariaveis] [protected]
[MAXMODES*MAXNFIELDS]; vector of body forces
Definition at line 201 of file PhElem.hpp.
Referenced by PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::show_b0(), and PhElem< 2 >::VectorElast2D().
border_num
template<int NumVariaveis>
int PhElem< NumVariaveis >::border_num[12] [protected]
Definition at line 195 of file PhElem.hpp.
Referenced by PhElem< 2 >::set_border_num(), PhElem< 2 >::set_border_tipo(), and PhElem< 2 >::show_border_num().
bs
template<int NumVariaveis>
double* PhElem< NumVariaveis >::bs[NumVariaveis] [protected]
vector of force boundary conditions
Definition at line 202 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_bs().
face_map
template<int NumVariaveis>
int PhElem< NumVariaveis >::face_map[6] [protected]
Definition at line 195 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::show_Face().
gbnmap
template<int NumVariaveis>
int PhElem< NumVariaveis >::gbnmap[NumVariaveis][MAXNN] [protected]
mapping from local to global nodes (or modes)
Definition at line 197 of file PhElem.hpp.
Referenced by PhElem< 2 >::anexa_gbnmap(), PhElem< 2 >::assign_gbnmap(), PhElem< 2 >::Atualizar_u0(), PhElem< 2 >::Avancar_u0(), PhElem< 2 >::check_connectivity(), PhElem< 2 >::Comparar_u0(), PhElem< 2 >::Copia_u0_em_(), PhElem< 2 >::gbnmap_aresta(), PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::gbnmap_interior(), PhElem< 2 >::gbnmap_vertices(), PhElem< 2 >::inicia_gbnmap(), PhElem< 2 >::make_K_Elast2D(), PhElem< 2 >::map(), PhElem< 2 >::mapa_inverso(), PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::print_modes(), PhElem< 2 >::print_numeracao(), PhElem< 2 >::set_gbnmap(), and PhElem< 2 >::show_gbnmap().
gbtrbmap
template<int NumVariaveis>
int PhElem< NumVariaveis >::gbtrbmap [protected]
Beginning index on the global array where the local border Gauss quadrature points (traces) are mapped; this map facilitates the use of mpi for paralell calculations over element borders.
Definition at line 207 of file PhElem.hpp.
Referenced by PhElem< 2 >::get_trace_border_map(), PhElem< 2 >::inicia_gbtrbmap(), and PhElem< 2 >::show_gbtrbmap().
J
template<int NumVariaveis>
double PhElem< NumVariaveis >::J [protected]
Jacobian from the physical to the standard element.
Definition at line 199 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_J().
JV
template<int NumVariaveis>
double* PhElem< NumVariaveis >::JV [protected]
Ponteiro para matriz do Jacobiano nos pontos gaussianos;.
Definition at line 200 of file PhElem.hpp.
Referenced by PhElem< 2 >::compute_JV(), PhElem< 2 >::finaliza_vetores(), PhElem< 2 >::make_K_Elast2D(), PhElem< 2 >::printwGQJ(), PhElem< 2 >::projetar_C0(), and PhElem< 2 >::transformacao_direta().
ndim
template<int NumVariaveis>
int PhElem< NumVariaveis >::ndim [protected]
Spatial dimension.
Definition at line 188 of file PhElem.hpp.
Referenced by PhElem< 2 >::check_gradiente(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::teste_gradiente().
numb
template<int NumVariaveis>
int PhElem< NumVariaveis >::numb[NumVariaveis] [protected]
Definition at line 194 of file PhElem.hpp.
Referenced by PhElem< 2 >::check_connectivity(), PhElem< 2 >::gbnmap_interior(), PhElem< 2 >::print_numeracao(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::set_ptr_stdel(), and PhElem< 2 >::set_ptr_stdel_var().
numborders
template<int NumVariaveis>
int PhElem< NumVariaveis >::numborders [protected]
Number of borders in the element.
Definition at line 192 of file PhElem.hpp.
Referenced by PhElem< 2 >::inicia_gbtrbmap(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::projetar_C0().
nume
template<int NumVariaveis>
int PhElem< NumVariaveis >::nume [protected]
Number of edges.
Definition at line 190 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::show_nume().
numf
template<int NumVariaveis>
int PhElem< NumVariaveis >::numf [protected]
Number of faces.
Definition at line 191 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::show_numf().
NumLocalVars
template<int NumVariaveis>
int PhElem< NumVariaveis >::NumLocalVars = NumVariaveis [protected]
Definition at line 187 of file PhElem.hpp.
Referenced by PhElem< 2 >::show_NumLocalVars().
numn
template<int NumVariaveis>
int PhElem< NumVariaveis >::numn[NumVariaveis] [protected]
Definition at line 193 of file PhElem.hpp.
Referenced by PhElem< 2 >::anexa_gbnmap(), PhElem< 2 >::Atualizar_u0(), PhElem< 2 >::Avancar_u0(), PhElem< 2 >::Comparar_u0(), PhElem< 2 >::Copia_u0_em_(), PhElem< 2 >::escrever_restart(), PhElem< 2 >::gbnmap_interior(), PhElem< 2 >::inicia_gbnmap(), PhElem< 2 >::inicia_vetores(), PhElem< 2 >::ler_restart(), PhElem< 2 >::ler_restart_buffer(), PhElem< 2 >::mapa_inverso(), PhElem< 2 >::P_eval_phys(), PhElem< 2 >::P_print(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::restart_element(), PhElem< 2 >::Restaurar_u0(), PhElem< 2 >::Salvar_u0(), PhElem< 2 >::set_gbnmap(), PhElem< 2 >::set_ptr_stdel(), PhElem< 2 >::set_ptr_stdel_var(), PhElem< 2 >::teste_gradiente(), and PhElem< 2 >::transformacao_direta().
numv
template<int NumVariaveis>
int PhElem< NumVariaveis >::numv [protected]
Number of vertices.
Definition at line 189 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_vertices(), PhElem< 2 >::Processar_dados(), PhElem< 2 >::set_part_num(), PhElem< 2 >::set_Vert_map(), and PhElem< 2 >::show_numv().
part_num
template<int NumVariaveis>
int PhElem< NumVariaveis >::part_num [protected]
numero da particao a qual pertence
Definition at line 196 of file PhElem.hpp.
Referenced by PhElem< 2 >::set_part_num(), and PhElem< 2 >::show_part_num().
ptr_stdel
template<int NumVariaveis>
Stdel* PhElem< NumVariaveis >::ptr_stdel[NumVariaveis] [protected]
Definition at line 184 of file PhElem.hpp.
Referenced by PhElem< 2 >::check_connectivity(), PhElem< 2 >::check_gradiente(), PhElem< 2 >::compute_JV(), PhElem< 2 >::gbnmap_aresta(), PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::get_trace_border_map(), PhElem< 2 >::inicia_gbtrbmap(), PhElem< 2 >::P_eval_phys(), PhElem< 2 >::P_print(), PhElem< 2 >::Phi_val(), PhElem< 2 >::print_modes(), PhElem< 2 >::printwGQJ(), PhElem< 2 >::Processar_dados(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::set_ptr_stdel(), PhElem< 2 >::set_ptr_stdel_var(), PhElem< 2 >::show_ptr_stdel(), PhElem< 2 >::teste_gradiente(), PhElem< 2 >::transformacao_direta(), and PhElem< 2 >::vetor_superficie().
ptvert
template<int NumVariaveis>
const Vertice* PhElem< NumVariaveis >::ptvert [protected]
Definition at line 186 of file PhElem.hpp.
Referenced by PhElem< 2 >::check_gradiente(), PhElem< 2 >::compute_JV(), PhElem< 2 >::make_K_Elast2D(), PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::P_print(), PhElem< 2 >::printwGQJ(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::set_part_num(), PhElem< 2 >::set_ptvert(), PhElem< 2 >::teste_gradiente(), and PhElem< 2 >::vetor_superficie().
sgn
template<int NumVariaveis>
int PhElem< NumVariaveis >::sgn[NumVariaveis][MAXNN] [protected]
sign of the local mode (or mode)
Definition at line 198 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_aresta(), PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::gbnmap_interior(), PhElem< 2 >::gbnmap_vertices(), PhElem< 2 >::inicia_gbnmap(), PhElem< 2 >::Kcomp(), PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::set_gbnmap(), PhElem< 2 >::show_sgn(), and PhElem< 2 >::VectorElast2D().
sinal
template<int NumVariaveis>
int PhElem< NumVariaveis >::sinal[12] [protected]
sinal refers to the borders
Definition at line 195 of file PhElem.hpp.
Referenced by PhElem< 2 >::gbnmap_aresta(), PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::Phi_val(), PhElem< 2 >::Processar_dados(), and PhElem< 2 >::show_sinal().
stgbtrbmapM
template<int NumVariaveis>
int* PhElem< NumVariaveis >::stgbtrbmapM [protected]
Array containing the start point in the global trace array of the internal trace of the border.
Definition at line 212 of file PhElem.hpp.
Referenced by PhElem< 2 >::finaliza_vetores(), PhElem< 2 >::inicia_gbtrbmap(), PhElem< 2 >::set_stgbtrbmap(), and PhElem< 2 >::show_stgbtrbmapM().
stgbtrbmapP
template<int NumVariaveis>
int* PhElem< NumVariaveis >::stgbtrbmapP [protected]
Array containing the start point in the global trace array of the external trace of the border.
Definition at line 214 of file PhElem.hpp.
Referenced by PhElem< 2 >::finaliza_vetores(), PhElem< 2 >::inicia_gbtrbmap(), PhElem< 2 >::set_stgbtrbmap(), and PhElem< 2 >::show_stgbtrbmapP().
type
template<int NumVariaveis>
int PhElem< NumVariaveis >::type [protected]
Definition at line 185 of file PhElem.hpp.
Referenced by PhElem< 2 >::set_type(), PhElem< 2 >::set_Vert_map(), and PhElem< 2 >::type_val().
u0
template<int NumVariaveis>
double* PhElem< NumVariaveis >::u0[NumVariaveis] [protected]
vector with the coefficients of each mode
Definition at line 203 of file PhElem.hpp.
Referenced by PhElem< 2 >::Atualizar_u0(), PhElem< 2 >::Avancar_u0(), PhElem< 2 >::check_gradiente(), PhElem< 2 >::Comparar_u0(), PhElem< 2 >::Copia_u0_em_(), PhElem< 2 >::escrever_restart(), PhElem< 2 >::finaliza_vetores(), PhElem< 2 >::inicia_vetores(), PhElem< 2 >::ler_restart(), PhElem< 2 >::mapa_inverso(), PhElem< 2 >::P_eval_phys(), PhElem< 2 >::P_eval_print_Elast2D(), PhElem< 2 >::P_print(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::restart_element(), PhElem< 2 >::Restaurar_u0(), PhElem< 2 >::Salvar_u0(), PhElem< 2 >::show_u(), and PhElem< 2 >::transformacao_direta().
usave
template<int NumVariaveis>
double* PhElem< NumVariaveis >::usave[NumVariaveis] [protected]
Definition at line 204 of file PhElem.hpp.
Referenced by PhElem< 2 >::finaliza_vetores(), PhElem< 2 >::inicia_vetores(), PhElem< 2 >::Restaurar_u0(), and PhElem< 2 >::Salvar_u0().
Vert_map
template<int NumVariaveis>
int PhElem< NumVariaveis >::Vert_map[8] [protected]
Definition at line 195 of file PhElem.hpp.
Referenced by PhElem< 2 >::check_gradiente(), PhElem< 2 >::compute_JV(), PhElem< 2 >::gbnmap_arestas(), PhElem< 2 >::gbnmap_faces(), PhElem< 2 >::gbnmap_vertices(), PhElem< 2 >::P_print(), PhElem< 2 >::printwGQJ(), PhElem< 2 >::Processar_dados(), PhElem< 2 >::projetar_C0(), PhElem< 2 >::read_vertices(), PhElem< 2 >::set_part_num(), PhElem< 2 >::set_Vert_map(), PhElem< 2 >::show_Vert_map(), PhElem< 2 >::teste_gradiente(), and PhElem< 2 >::vetor_superficie().
vetores_iniciados
template<int NumVariaveis>
int PhElem< NumVariaveis >::vetores_iniciados [protected]
Definition at line 216 of file PhElem.hpp.
Referenced by PhElem< 2 >::finaliza_vetores(), and PhElem< 2 >::inicia_vetores().
The documentation for this class was generated from the following files:
PhElem.hpp
Elastodinamica2D.cpp
Elastostatica.cpp