Fluids Class Reference
#include <Fluids.h>
Public Member Functions
void set_theta (double x)
void set_pd (double x)
void set_mun (double x)
void set_muw (double x)
void set_rhon (double x)
void set_rhow (double x)
double const show_theta ()
double const show_pd ()
double const show_mun ()
double const show_muw ()
double const show_rhon ()
double const show_rhow ()
double const Krw (double s)
double const Krn (double s)
double const dkrw (double s)
double const dkrn (double s)
double const pressao_capilar (double s)
double const dpc (double s)
double const d2pc (double s)
Private Attributes
double theta
double pd
double mun
double muw
double rhon
double rhow
Detailed Description
Definition at line 4 of file Fluids.h.
Member Function Documentation
d2pc()
double const Fluids::d2pc (double s)
Definition at line 5 of file Fluids.cpp.
References aux, pd, and theta.
Referenced by DG_Prob::DG_EI_IG(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
dkrn()
double const Fluids::dkrn (double s)
Definition at line 14 of file Fluids.cpp.
References aux, and theta.
Referenced by DG_Prob::DG_EI_IG(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
dkrw()
double const Fluids::dkrw (double s)
Definition at line 26 of file Fluids.cpp.
References aux, and theta.
Referenced by DG_Prob::DG_EI_IG(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
dpc()
double const Fluids::dpc (double s)
Definition at line 36 of file Fluids.cpp.
References aux, pd, and theta.
Referenced by DG_Elem::calcula_tracos(), DG_Prob::DG_EI_IG(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
Krn()
double const Fluids::Krn (double s)
Definition at line 46 of file Fluids.cpp.
References aux, and theta.
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
Krw()
double const Fluids::Krw (double s)
Definition at line 56 of file Fluids.cpp.
References aux, and theta.
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
pressao_capilar()
double const Fluids::pressao_capilar (double s)
Definition at line 66 of file Fluids.cpp.
References aux, p_in, p_out, pd, pw_ini, sn_in, sn_ini, and theta.
Referenced by DG_Prob::DG_EI_IG(), DG_Prob::DG_EI_Inflow(), show_rhow(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
set_mun()
void Fluids::set_mun (double x) [inline]
Definition at line 11 of file Fluids.h.
References mun.
Referenced by DG_Prob::DG_initial_conditions().
set_muw()
void Fluids::set_muw (double x) [inline]
Definition at line 12 of file Fluids.h.
References muw.
Referenced by DG_Prob::DG_initial_conditions().
set_pd()
void Fluids::set_pd (double x) [inline]
Definition at line 10 of file Fluids.h.
References pd.
Referenced by DG_Prob::DG_initial_conditions().
set_rhon()
void Fluids::set_rhon (double x) [inline]
Definition at line 13 of file Fluids.h.
References rhon.
Referenced by DG_Prob::DG_initial_conditions().
set_rhow()
void Fluids::set_rhow (double x) [inline]
Definition at line 14 of file Fluids.h.
References rhow.
Referenced by DG_Prob::DG_initial_conditions().
set_theta()
void Fluids::set_theta (double x) [inline]
Definition at line 9 of file Fluids.h.
References theta.
Referenced by DG_Prob::DG_initial_conditions().
show_mun()
double const Fluids::show_mun () [inline]
Definition at line 18 of file Fluids.h.
References mun.
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
show_muw()
double const Fluids::show_muw () [inline]
Definition at line 19 of file Fluids.h.
References muw.
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_EI_IG(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), DG_Elem::VolumeIntegrals_UMFPACK(), and DG_Elem::VolumeTracos().
show_pd()
double const Fluids::show_pd () [inline]
Definition at line 17 of file Fluids.h.
References pd.
show_rhon()
double const Fluids::show_rhon () [inline]
Definition at line 20 of file Fluids.h.
References rhon.
show_rhow()
double const Fluids::show_rhow () [inline]
Definition at line 21 of file Fluids.h.
References d2pc(), dkrn(), dkrw(), dpc(), Krn(), Krw(), pressao_capilar(), and rhow.
show_theta()
double const Fluids::show_theta () [inline]
Definition at line 16 of file Fluids.h.
References theta.
Member Data Documentation
mun
double Fluids::mun [private]
Definition at line 34 of file Fluids.h.
Referenced by set_mun(), and show_mun().
muw
double Fluids::muw [private]
Definition at line 34 of file Fluids.h.
Referenced by set_muw(), and show_muw().
pd
double Fluids::pd [private]
Definition at line 34 of file Fluids.h.
Referenced by d2pc(), dpc(), pressao_capilar(), set_pd(), and show_pd().
rhon
double Fluids::rhon [private]
Definition at line 34 of file Fluids.h.
Referenced by set_rhon(), and show_rhon().
rhow
double Fluids::rhow [private]
Definition at line 34 of file Fluids.h.
Referenced by set_rhow(), and show_rhow().
theta
double Fluids::theta [private]
Definition at line 34 of file Fluids.h.
Referenced by d2pc(), dkrn(), dkrw(), dpc(), Krn(), Krw(), pressao_capilar(), set_theta(), and show_theta().
The documentation for this class was generated from the following files:
Fluids.h
Fluids.cpp