DG.cpp File Reference
#include `spectral.h`
Functions
void somavv (int q, const double *ptx, const double *pty, double *ptr)
void soma3v (int q, const double *x1, const double *x2, const double *x3, double *ptr)
void soma4v (int q, const double *x1, const double *x2, const double *x3, const double *x4, double *ptr)
void soma5v (int q, const double *x1, const double *x2, const double *x3, const double *x4, const double *x5, double *ptr)
void subtvv (int q, const double *ptx, const double *pty, double *ptr)
void prodvv (int q, const double *ptx, const double *pty, double *ptr)
void prod3v (int q, const double *ptx, const double *pty, const double *ptz, double *ptr)
void prod4v (int q, const double *x1, const double *x2, const double *x3, const double *x4, double *ptr)
void prod5v (int q, const double *x1, const double *x2, const double *x3, const double *x4, const double *x5, double *ptr)
void prodev (int q, const double fator, const double *ptx, double *ptr)
void prodgg (int q, const double *ptx0, const double *ptx1, const double *pty0, const double *pty1, double *ptr)
void prodgn (int q, const double *ptx0, const double *ptx1, const double *n, double *ptr)
void prodgn (const int ndim, const int qmax, double **grad, const double *n, double *ptr)
void Kgradn (const int ndim, const int qmax, const double *K, double **grad, const double *n, double *ptr)
void Kgradn (int q, const double *K, const double *ptx0, const double *ptx1, const double *n, double *ptr)
void Kgradgrad (int q, const double *K, const double *ptx0, const double *ptx1, const double *pty0, const double *pty1, double *ptr)
void integral (int q, const double *ptw, const double *ptx, double &r)
void soma_vetor (int q, const double *ptx, double &r)
Function Documentation
integral()
void integral (int q, const double * ptw, const double * ptx, double & r)
Definition at line 199 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), and DG_Elem::VolumeIntegrals_UMFPACK().
Kgradgrad()
void Kgradgrad (int q, const double * K, const double * ptx0, const double * ptx1, const double * pty0, const double * pty1, double * ptr)
Definition at line 187 of file DG.cpp.
References prodev(), prodvv(), and somavv().
Kgradn() [1/2]
void Kgradn (const int ndim, const int qmax, const double * K, double ** grad, const double * n, double * ptr)
Definition at line 154 of file DG.cpp.
References aux, ndim, and qmax.
Kgradn() [2/2]
void Kgradn (int q, const double * K, const double * ptx0, const double * ptx1, const double * n, double * ptr)
Definition at line 170 of file DG.cpp.
References aux, prodev(), and somavv().
prod3v()
void prod3v (int q, const double * ptx, const double * pty, const double * ptz, double * ptr)
Definition at line 77 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG().
prod4v()
void prod4v (int q, const double * x1, const double * x2, const double * x3, const double * x4, double * ptr)
Definition at line 88 of file DG.cpp.
prod5v()
void prod5v (int q, const double * x1, const double * x2, const double * x3, const double * x4, const double * x5, double * ptr)
Definition at line 99 of file DG.cpp.
prodev()
void prodev (int q, const double fator, const double * ptx, double * ptr)
Definition at line 112 of file DG.cpp.
Referenced by Kgradgrad(), Kgradn(), prodgn(), and DG_Elem::VolumeIntegrals_IG().
prodgg()
void prodgg (int q, const double * ptx0, const double * ptx1, const double * pty0, const double * pty1, double * ptr)
Definition at line 124 of file DG.cpp.
References prodvv(), and somavv().
prodgn() [1/2]
void prodgn (int q, const double * ptx0, const double * ptx1, const double * n, double * ptr)
Definition at line 134 of file DG.cpp.
References prodev(), and somavv().
prodgn() [2/2]
void prodgn (const int ndim, const int qmax, double ** grad, const double * n, double * ptr)
Definition at line 143 of file DG.cpp.
References ndim, and qmax.
prodvv()
void prodvv (int q, const double * ptx, const double * pty, double * ptr)
Definition at line 67 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG(), Kgradgrad(), prodgg(), and DG_Elem::VolumeIntegrals_IG().
soma3v()
void soma3v (int q, const double * x1, const double * x2, const double * x3, double * ptr)
Definition at line 23 of file DG.cpp.
soma4v()
void soma4v (int q, const double * x1, const double * x2, const double * x3, const double * x4, double * ptr)
Definition at line 34 of file DG.cpp.
soma5v()
void soma5v (int q, const double * x1, const double * x2, const double * x3, const double * x4, const double * x5, double * ptr)
Definition at line 45 of file DG.cpp.
soma_vetor()
void soma_vetor (int q, const double * ptx, double & r)
Definition at line 208 of file DG.cpp.
somavv()
void somavv (int q, const double * ptx, const double * pty, double * ptr)
Definition at line 8 of file DG.cpp.
Referenced by Kgradgrad(), Kgradn(), prodgg(), prodgn(), and DG_Elem::VolumeIntegrals_IG().
subtvv()
void subtvv (int q, const double * ptx, const double * pty, double * ptr)
Definition at line 57 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG().