Differentiation.cpp File Reference
#include `spectral.h`
Functions
void ColDifGLJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
void ColDifGRJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
void ColDifGJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Function Documentation
ColDifGJ()
void ColDifGJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Collocation Differentiation Gauss-Jacobi. Implements material contained in Appendix C of Spectral/hp Element Methods for CFD by G. Karniadakis & S. J. Spencer.
Definition at line 110 of file Differentiation.cpp.
References Jacobi_P(), Jacobi_roots(), and MAXQ.
ColDifGLJ()
void ColDifGLJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Collocation Differentiation Gauss-Lobatto-Jacobi. Implements material contained in Appendix C of Spectral/hp Element Methods for CFD by G. Karniadakis & S. J. Spencer.
Definition at line 20 of file Differentiation.cpp.
References aaux, aux, Jacobi_P(), Jacobi_roots(), and MAXQ.
ColDifGRJ()
void ColDifGRJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Collocation Differentiation Gauss-Radau-Jacobi. Implements material contained in Appendix C of Spectral/hp Element Methods for CFD by G. Karniadakis & S. J. Spencer.
Definition at line 76 of file Differentiation.cpp.
References aaux, aux, Jacobi_P(), Jacobi_roots(), and MAXQ.