Funcoes_c.h File Reference
Functions
void jacobi_poly (int n, double alpha, double beta, double x, double cx[])
void Jacobi_P (int n, double a, double b, double x, double &y, double &dy, double &d2y)
void Jacobi_P (int n, double a, double b, double x, double &y, double &dy)
void Jacobi_P (int n, double a, double b, double x, double &y)
void Jacobi_roots (int m, double alpha, double beta, double x[])
double gamma_log (double x)
double my_gamma (double x)
void Gauss_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
void Gauss_Lobatto_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
double C (int Q2, double alpha, double beta, double xi)
void Gauss_Radau_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
double B (int q, double alpha, double beta, double xi)
double d_epsilon (void)
double Psia (int I, int i, double z)
double Psib (int I, int J, int i, int j, double z)
double Psic (int I, int J, int K, int i, int j, int k, double z)
double DPsia (int I, int i, double z)
double DPsib (int I, int J, int i, int j, double z)
double DPsic (int I, int J, int K, int i, int j, int k, double z)
void ColDifGLJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
void ColDifGRJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
void ColDifGJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
int teste_aresta (int p, int n0, int n1, int &sgn, int &ng, int &NG, int &NL, std::vector< EDGE > &border, int Ng[], int nel, int nlado, const Vertice *vert, const int sinal_normal)
int aresta_gbnum (const int na, const int nb, int &NL, std::vector< ARESTA > &aresta_vector)
int face_gbnum (const int nvf, const int v[], int &NF, std::vector< FACE > &face_vector)
double funcao_contorno (double, double, double)
double funcao (double, double, double)
double g (double, double, double)
double force0 (double, double, double)
double force1 (double, double, double)
void predictor (int N, double *fn3, double *fn2, double *fn1, double *fn, double *yn, double h, double *yp)
int get_linha (FILE *finput, char linha[256])
double p1 (double, double, double)
double p2 (double, double, double)
double fluxo_entrando (double, double, double)
double funcao_pdir (double, double, const int)
double funcao_sdir (double, double)
double sn_inicial (double x, double y, double z)
double pw_inicial (double x, double y, double z)
double norma_max (int N, double V[])
double norma_l2 (int N, double B[])
void ordenar (const int n, int base[], int seq[])
void quad_ordem (const int Av[4], const int Bi[4], int dir[3], int sgn[3], int &v2)
void tetrahedro_faz_face_mask (const int &n_in, int ver_temp[], std::vector< int > &face_mask)
void somavv (int q, const double *ptx, const double *pty, double *ptr)
void soma3v (int q, const double *x1, const double *x2, const double *x3, double *ptr)
void soma4v (int q, const double *x1, const double *x2, const double *x3, const double *x4, double *ptr)
void soma5v (int q, const double *x1, const double *x2, const double *x3, const double *x4, const double *x5, double *ptr)
void subtvv (int q, const double *ptx, const double *pty, double *ptr)
void prodvv (int q, const double *ptx, const double *pty, double *ptr)
void prod3v (int q, const double *ptx, const double *pty, const double *ptz, double *ptr)
void prod4v (int q, const double *x1, const double *x2, const double *x3, const double *x4, double *ptr)
void prod5v (int q, const double *x1, const double *x2, const double *x3, const double *x4, const double *x5, double *ptr)
void prodev (int q, const double fator, const double *ptx, double *ptr)
void prodgg (int q, const double *ptx0, const double *ptx1, const double *pty0, const double *pty1, double *ptr)
void prodgn (int q, const double *ptx0, const double *ptx1, const double *n, double *ptr)
void prodgn (const int ndim, const int q, double **grad, const double *n, double *ptr)
void Kgradn (int q, const double *K, const double *ptx0, const double *ptx1, const double *n, double *ptr)
void Kgradn (const int ndim, const int qmax, const double *K, double **grad, const double *n, double *ptr)
void Kgradgrad (int q, const double *K, const double *ptx0, const double *ptx1, const double *pty0, const double *pty1, double *ptr)
void integral (int q, const double *ptw, const double *ptx, double &r)
void soma_vetor (int q, const double *ptx, double &r)
int Sinal (int i)
int ResolverSistema (const int NumD, const int count, int *Ti, int *Tj, double *Tx, double *B, double *x)
int CH_ResolverSistema (const int NumD, const int count, int *Ti, int *Tj, double *Tx, double *B, double *x)
Function Documentation
aresta_gbnum()
int aresta_gbnum (const int na, const int nb, int & NL, std::vector< ARESTA > & aresta_vector)
Definition at line 407 of file Funcoes_globais.cpp.
References ARESTA::Na, and ARESTA::Nb.
Referenced by PhElem< 2 >::Processar_dados().
B()
double B (int q, double alpha, double beta, double xi)
Definition at line 801 of file ASPFunctions.cpp.
References aux, Jacobi_P(), and my_gamma().
Referenced by DG_Prob::DG_EI_Epetra_Inflow(), DG_Prob::DG_EI_Epetra_Interior(), DG_Prob::DG_EI_Epetra_Outflow(), DG_Prob::DG_initial_conditions(), Quadrilateral::Dirichlet(), Triangle::Dirichlet(), DG_Prob::Eigenvectors(), Gauss_Radau_Jacobi_parameters(), PhElem< 2 >::make_Kcomp_Elast2D(), PhElem< 2 >::projetar_C0(), DG_Elem::show_Volume(), ED_Prob::SolveElast2D_dyn(), PhElem< 2 >::transformacao_direta(), and DG_Elem::VolumeIntegrals().
C()
double C (int Q2, double alpha, double beta, double xi)
Definition at line 637 of file ASPFunctions.cpp.
References aux, Jacobi_P(), and my_gamma().
Referenced by Gauss_Lobatto_Jacobi_parameters(), PhElem< 2 >::make_Kcomp_Elast2D(), and ED_Prob::SolveElast2D_dyn().
CH_ResolverSistema()
int CH_ResolverSistema (const int NumD, const int count, int * Ti, int * Tj, double * Tx, double * B, double * x)
ColDifGJ()
void ColDifGJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Collocation Differentiation Gauss-Jacobi. Implements material contained in Appendix C of Spectral/hp Element Methods for CFD by G. Karniadakis & S. J. Spencer.
Definition at line 110 of file Differentiation.cpp.
References Jacobi_P(), Jacobi_roots(), and MAXQ.
ColDifGLJ()
void ColDifGLJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Collocation Differentiation Gauss-Lobatto-Jacobi. Implements material contained in Appendix C of Spectral/hp Element Methods for CFD by G. Karniadakis & S. J. Spencer.
Definition at line 20 of file Differentiation.cpp.
References aaux, aux, Jacobi_P(), Jacobi_roots(), and MAXQ.
ColDifGRJ()
void ColDifGRJ (int Q, double alpha, double beta, double D[MAXQ][MAXQ])
Collocation Differentiation Gauss-Radau-Jacobi. Implements material contained in Appendix C of Spectral/hp Element Methods for CFD by G. Karniadakis & S. J. Spencer.
Definition at line 76 of file Differentiation.cpp.
References aaux, aux, Jacobi_P(), Jacobi_roots(), and MAXQ.
d_epsilon()
double d_epsilon (void)
Definition at line 816 of file ASPFunctions.cpp.
Referenced by gamma_log().
DPsia()
double DPsia (int I, int i, double z)
Definition at line 30 of file AMPFunctionsA.cpp.
References Jacobi_P().
Referenced by DPsib(), Triangle::elem_traces(), Quadrilateral::elem_traces(), Linear::elem_traces(), Hexahedral::elem_traces(), Hexahedral::eval_GradPhi(), and Quadrilateral::eval_GradPhi().
DPsib()
double DPsib (int I, int J, int i, int j, double z)
Definition at line 71 of file AMPFunctionsA.cpp.
References DPsia(), and Jacobi_P().
Referenced by Triangle::elem_traces().
DPsic()
double DPsic (int I, int J, int K, int i, int j, int k, double z)
face_gbnum()
int face_gbnum (const int nvf, const int v[], int & NF, std::vector< FACE > & face_vector)
Definition at line 428 of file Funcoes_globais.cpp.
References FACE::_nv, FACE::_tipo, and FACE::_vertice.
Referenced by PhElem< 2 >::Processar_dados().
fluxo_entrando()
double fluxo_entrando (double , double , double)
force0()
double force0 (double , double , double)
Referenced by PhElem< 2 >::make_Kcomp_Elast2D().
force1()
double force1 (double , double , double)
funcao()
double funcao (double , double , double)
Definition at line 110 of file Funcoes_globais.cpp.
funcao_contorno()
double funcao_contorno (double , double , double)
funcao_pdir()
double funcao_pdir (double , double , const int)
Definition at line 79 of file Fluids.cpp.
References p_in, and p_out.
Referenced by DG_Prob::Processa_condicoes_contorno().
funcao_sdir()
double funcao_sdir (double , double)
Definition at line 88 of file Fluids.cpp.
References sn_in.
Referenced by DG_Prob::Processa_condicoes_contorno().
g()
double g (double , double , double)
Definition at line 138 of file Funcoes_globais.cpp.
Referenced by Hexahedral::Gradiente(), Triangle::Gradiente(), Linear::Gradiente(), Quadrilateral::Gradiente(), and Tetrahedral::map_face().
gamma_log()
double gamma_log (double x)
Definition at line 348 of file ASPFunctions.cpp.
References d_epsilon(), p1(), and p2().
Referenced by my_gamma().
Gauss_Jacobi_parameters()
void Gauss_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
Definition at line 756 of file ASPFunctions.cpp.
References aaux, aux, Jacobi_P(), Jacobi_roots(), MAXQ, and my_gamma().
Referenced by DG_Prob::DG_EI_flux(), DG_Prob::DG_initial_conditions(), Quadrilateral::elem_traces(), Hexahedral::elem_traces(), Triangle::elem_traces(), Quadrilateral::gauss_parameters_default(), Linear::gauss_parameters_default(), Hexahedral::gauss_parameters_default(), Triangle::gauss_parameters_default(), DG_Prob::Processa_condicoes_contorno(), Triangle::trace(), Hexahedral::trace(), and Quadrilateral::trace().
Gauss_Lobatto_Jacobi_parameters()
void Gauss_Lobatto_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
Definition at line 660 of file ASPFunctions.cpp.
References aaux, aux, C(), Jacobi_P(), Jacobi_roots(), and MAXQ.
Referenced by Quadrilateral::Dirichlet(), Triangle::Dirichlet(), Quadrilateral::gauss_parameters_default(), Linear::gauss_parameters_default(), Hexahedral::gauss_parameters_default(), Tetrahedral::gauss_parameters_default(), and Triangle::gauss_parameters_default().
Gauss_Radau_Jacobi_parameters()
void Gauss_Radau_Jacobi_parameters (int Q, double alpha, double beta, double x[], double w[], double D[MAXQ][MAXQ])
Definition at line 712 of file ASPFunctions.cpp.
References aaux, aux, B(), Jacobi_P(), Jacobi_roots(), and MAXQ.
Referenced by Quadrilateral::gauss_parameters_default(), Linear::gauss_parameters_default(), Hexahedral::gauss_parameters_default(), Triangle::gauss_parameters_default(), and Tetrahedral::gauss_parameters_default().
get_linha()
int get_linha (FILE * finput, char linha[256])
Definition at line 289 of file Funcoes_globais.cpp.
integral()
void integral (int q, const double * ptw, const double * ptx, double & r)
Definition at line 199 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG(), DG_Elem::VolumeIntegrals(), DG_Elem::VolumeIntegrals_IG(), and DG_Elem::VolumeIntegrals_UMFPACK().
Jacobi_P() [1/3]
void Jacobi_P (int n, double a, double b, double x, double & y, double & dy, double & d2y)
Definition at line 140 of file ASPFunctions.cpp.
Referenced by B(), C(), ColDifGJ(), ColDifGLJ(), ColDifGRJ(), DPsia(), DPsib(), Gauss_Jacobi_parameters(), Gauss_Lobatto_Jacobi_parameters(), Gauss_Radau_Jacobi_parameters(), Jacobi_roots(), Psia(), Psib(), and Psic().
Jacobi_P() [2/3]
void Jacobi_P (int n, double a, double b, double x, double & y, double & dy)
Definition at line 230 of file ASPFunctions.cpp.
Jacobi_P() [3/3]
void Jacobi_P (int n, double a, double b, double x, double & y)
Definition at line 185 of file ASPFunctions.cpp.
jacobi_poly()
void jacobi_poly (int n, double alpha, double beta, double x, double cx[])
Definition at line 5 of file ASPFunctions.cpp.
Jacobi_roots()
void Jacobi_roots (int m, double alpha, double beta, double x[])
Definition at line 274 of file ASPFunctions.cpp.
References e, Jacobi_P(), and m.
Referenced by ColDifGJ(), ColDifGLJ(), ColDifGRJ(), Gauss_Jacobi_parameters(), Gauss_Lobatto_Jacobi_parameters(), and Gauss_Radau_Jacobi_parameters().
Kgradgrad()
void Kgradgrad (int q, const double * K, const double * ptx0, const double * ptx1, const double * pty0, const double * pty1, double * ptr)
Definition at line 187 of file DG.cpp.
References prodev(), prodvv(), and somavv().
Kgradn() [1/2]
void Kgradn (int q, const double * K, const double * ptx0, const double * ptx1, const double * n, double * ptr)
Definition at line 170 of file DG.cpp.
References aux, prodev(), and somavv().
Kgradn() [2/2]
void Kgradn (const int ndim, const int qmax, const double * K, double ** grad, const double * n, double * ptr)
Definition at line 154 of file DG.cpp.
References aux, ndim, and qmax.
my_gamma()
double my_gamma (double x)
Definition at line 303 of file ASPFunctions.cpp.
References gamma_log().
Referenced by B(), C(), and Gauss_Jacobi_parameters().
norma_l2()
double norma_l2 (int N, double B[])
Definition at line 96 of file Funcoes_globais.cpp.
norma_max()
double norma_max (int N, double V[])
Definition at line 84 of file Funcoes_globais.cpp.
References aux, and aux1.
ordenar()
void ordenar (const int n, int base[], int seq[])
Definition at line 64 of file Funcoes_globais.cpp.
Referenced by tetrahedro_faz_face_mask().
p1()
double p1 (double , double , double)
Referenced by Quadrilateral::Dirichlet(), Tetrahedral::Dirichlet(), Triangle::Dirichlet(), gamma_log(), Linear::make_local_matrices(), Tetrahedral::make_local_matrices(), Hexahedral::make_local_matrices(), Tetrahedral::mass(), Hexahedral::mass(), and Linear::mass().
p2()
double p2 (double , double , double)
Referenced by gamma_log(), Linear::make_local_matrices(), Tetrahedral::make_local_matrices(), Hexahedral::make_local_matrices(), Linear::mass(), Tetrahedral::mass(), and Hexahedral::mass().
predictor()
void predictor (int N, double * fn3, double * fn2, double * fn1, double * fn, double * yn, double h, double * yp)
prod3v()
void prod3v (int q, const double * ptx, const double * pty, const double * ptz, double * ptr)
Definition at line 77 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG().
prod4v()
void prod4v (int q, const double * x1, const double * x2, const double * x3, const double * x4, double * ptr)
Definition at line 88 of file DG.cpp.
prod5v()
void prod5v (int q, const double * x1, const double * x2, const double * x3, const double * x4, const double * x5, double * ptr)
Definition at line 99 of file DG.cpp.
prodev()
void prodev (int q, const double fator, const double * ptx, double * ptr)
Definition at line 112 of file DG.cpp.
Referenced by Kgradgrad(), Kgradn(), prodgn(), and DG_Elem::VolumeIntegrals_IG().
prodgg()
void prodgg (int q, const double * ptx0, const double * ptx1, const double * pty0, const double * pty1, double * ptr)
Definition at line 124 of file DG.cpp.
References prodvv(), and somavv().
prodgn() [1/2]
void prodgn (int q, const double * ptx0, const double * ptx1, const double * n, double * ptr)
Definition at line 134 of file DG.cpp.
References prodev(), and somavv().
prodgn() [2/2]
void prodgn (const int ndim, const int q, double ** grad, const double * n, double * ptr)
Definition at line 143 of file DG.cpp.
References ndim, and qmax.
prodvv()
void prodvv (int q, const double * ptx, const double * pty, double * ptr)
Definition at line 67 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG(), Kgradgrad(), prodgg(), and DG_Elem::VolumeIntegrals_IG().
Psia()
double Psia (int I, int i, double z)
Definition at line 8 of file AMPFunctionsA.cpp.
References Jacobi_P().
Referenced by Hexahedral::computeAtPoints(), Linear::computeAtPoints(), Tetrahedral::computeAtPoints(), Triangle::computeAtPoints(), Quadrilateral::computeAtPoints(), Hexahedral::computeVertice(), Linear::computeVertice(), Tetrahedral::computeVertice(), Triangle::computeVertice(), Quadrilateral::computeVertice(), Triangle::Dirichlet(), Quadrilateral::Dirichlet(), Linear::elem_traces(), Hexahedral::elem_traces(), Triangle::elem_traces(), Quadrilateral::elem_traces(), Hexahedral::eval_GradPhi(), Quadrilateral::eval_GradPhi(), Linear::evalGQ(), Tetrahedral::evalGQ(), Triangle::evalGQ(), Quadrilateral::evalGQ(), Hexahedral::evalGQ(), Linear::make_local_matrices(), Tetrahedral::make_local_matrices(), Quadrilateral::make_local_matrices(), Hexahedral::make_local_matrices(), Triangle::make_local_matrices(), Hexahedral::mass(), Triangle::mass(), Quadrilateral::mass(), Linear::mass(), Tetrahedral::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Psib(), Psic(), Triangle::set(), Quadrilateral::set(), Linear::set(), Hexahedral::set(), Triangle::vector_of_integral_of_f_Phi_dv(), Quadrilateral::vector_of_integral_of_f_Phi_dv(), Linear::vector_of_integral_of_f_Phi_dv(), Hexahedral::vector_of_integral_of_f_Phi_dv(), and Tetrahedral::vector_of_integral_of_f_Phi_dv().
Psib()
double Psib (int I, int J, int i, int j, double z)
Definition at line 51 of file AMPFunctionsA.cpp.
References Jacobi_P(), and Psia().
Referenced by Tetrahedral::computeAtPoints(), Triangle::computeAtPoints(), Tetrahedral::computeVertice(), Triangle::computeVertice(), Triangle::elem_traces(), Tetrahedral::evalGQ(), Triangle::evalGQ(), Tetrahedral::make_local_matrices(), Triangle::make_local_matrices(), Tetrahedral::mass(), Triangle::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), Psic(), Triangle::set(), Tetrahedral::vector_of_integral_of_f_Phi_dv(), and Triangle::vector_of_integral_of_f_Phi_dv().
Psic()
double Psic (int I, int J, int K, int i, int j, int k, double z)
Definition at line 93 of file AMPFunctionsA.cpp.
References Jacobi_P(), Psia(), and Psib().
Referenced by Tetrahedral::computeAtPoints(), Tetrahedral::computeVertice(), Tetrahedral::evalGQ(), Tetrahedral::make_local_matrices(), Tetrahedral::mass(), Tetrahedral::printtoarray(), Tetrahedral::printtofile(), and Tetrahedral::vector_of_integral_of_f_Phi_dv().
pw_inicial()
double pw_inicial (double x, double y, double z)
Definition at line 100 of file Fluids.cpp.
References pw_ini.
quad_ordem()
void quad_ordem (const int Av[4], const int Bi[4], int dir[3], int sgn[3], int & v2)
Definition at line 3 of file Funcoes_globais.cpp.
Referenced by PhElem< 2 >::gbnmap_faces(), and Hexahedral_face_modal_connectivity().
ResolverSistema()
int ResolverSistema (const int NumD, const int count, int * Ti, int * Tj, double * Tx, double * B, double * x)
Definition at line 464 of file Funcoes_globais.cpp.
Referenced by DG_Prob::DG_initial_conditions().
Sinal()
int Sinal (int i)
Definition at line 104 of file Funcoes_globais.cpp.
Referenced by DG_Prob::DG_EI_IG(), and DG_Prob::DG_EI_Interior().
sn_inicial()
double sn_inicial (double x, double y, double z)
Definition at line 94 of file Fluids.cpp.
References sn_ini.
Referenced by DG_Prob::DG_initial_conditions().
soma3v()
void soma3v (int q, const double * x1, const double * x2, const double * x3, double * ptr)
Definition at line 23 of file DG.cpp.
soma4v()
void soma4v (int q, const double * x1, const double * x2, const double * x3, const double * x4, double * ptr)
Definition at line 34 of file DG.cpp.
soma5v()
void soma5v (int q, const double * x1, const double * x2, const double * x3, const double * x4, const double * x5, double * ptr)
Definition at line 45 of file DG.cpp.
soma_vetor()
void soma_vetor (int q, const double * ptx, double & r)
Definition at line 208 of file DG.cpp.
somavv()
void somavv (int q, const double * ptx, const double * pty, double * ptr)
Definition at line 8 of file DG.cpp.
Referenced by Kgradgrad(), Kgradn(), prodgg(), prodgn(), and DG_Elem::VolumeIntegrals_IG().
subtvv()
void subtvv (int q, const double * ptx, const double * pty, double * ptr)
Definition at line 57 of file DG.cpp.
Referenced by DG_Prob::DG_EI_IG().
teste_aresta()
int teste_aresta (int p, int n0, int n1, int & sgn, int & ng, int & NG, int & NL, std::vector< EDGE > & border, int Ng[], int nel, int nlado, const Vertice * vert, const int sinal_normal)
Definition at line 317 of file Funcoes_globais.cpp.
References EDGE::comprimento, EDGE::elemento, MAXNG, MAXNL, n0, EDGE::Na, EDGE::Nb, EDGE::normal, EDGE::num_elem, EDGE::num_local, EDGE::sinal, EDGE::tipo, Vertice::x, Vertice::y, and Vertice::z.
tetrahedro_faz_face_mask()
void tetrahedro_faz_face_mask (const int & n_in, int ver_temp[], std::vector< int > & face_mask)
Definition at line 199 of file Funcoes_globais.cpp.
References m, and ordenar().
Referenced by GeProb< MyElem, 2, 2 >::Ler_e_Processar_malha().