Funcoes_globais.cpp File Reference
#include `spectral.h`
Functions
void quad_ordem (const int Av[4], const int Bi[4], int dir[3], int sgn[3], int &v2)
void ordenar (const int n, int A[], int seq[])
double norma_max (int N, double V[])
double norma_l2 (int N, double B[])
int Sinal (int i)
double funcao (double x, double y, double z)
double g (double x, double y, double z)
void tetrahedro_faz_face_mask (const int &n_in, int ver_temp[], std::vector< int > &face_mask)
void Hexahedral_face_modal_connectivity (int Av[4], int Bi[4], int P[], int mode_mask[], int sgn_mask[])
int get_linha (FILE *finput, char linha[256])
int teste_aresta (int p, int n0, int n1, int &sign, int &ng, int &NG, int &NL, std::vector< EDGE > &border, int Ng[], int nel, int naresta, const Vertice *vert, const int sinal_normal)
int aresta_gbnum (const int na, const int nb, int &NL, std::vector< ARESTA > &aresta_vector)
int face_gbnum (const int nvf, const int v[], int &NF, std::vector< FACE > &face_vector)
int ResolverSistema (const int NumD, const int count, int *Ti, int *Tj, double *Tx, double *B, double *x)
void ZerarMatrizVetor (Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
Function Documentation
aresta_gbnum()
int aresta_gbnum (const int na, const int nb, int & NL, std::vector< ARESTA > & aresta_vector)
Definition at line 407 of file Funcoes_globais.cpp.
References ARESTA::Na, and ARESTA::Nb.
Referenced by PhElem< 2 >::Processar_dados().
face_gbnum()
int face_gbnum (const int nvf, const int v[], int & NF, std::vector< FACE > & face_vector)
Definition at line 428 of file Funcoes_globais.cpp.
References FACE::_nv, FACE::_tipo, and FACE::_vertice.
Referenced by PhElem< 2 >::Processar_dados().
funcao()
double funcao (double x, double y, double z)
Definition at line 110 of file Funcoes_globais.cpp.
g()
double g (double x, double y, double z)
Definition at line 138 of file Funcoes_globais.cpp.
Referenced by Hexahedral::Gradiente(), Triangle::Gradiente(), Linear::Gradiente(), Quadrilateral::Gradiente(), and Tetrahedral::map_face().
get_linha()
int get_linha (FILE * finput, char linha[256])
Definition at line 289 of file Funcoes_globais.cpp.
Hexahedral_face_modal_connectivity()
void Hexahedral_face_modal_connectivity (int Av[4], int Bi[4], int P[], int mode_mask[], int sgn_mask[])
Definition at line 230 of file Funcoes_globais.cpp.
References aux1, aux2, n0, and quad_ordem().
norma_l2()
double norma_l2 (int N, double B[])
Definition at line 96 of file Funcoes_globais.cpp.
norma_max()
double norma_max (int N, double V[])
Definition at line 84 of file Funcoes_globais.cpp.
References aux, and aux1.
ordenar()
void ordenar (const int n, int A[], int seq[])
Definition at line 64 of file Funcoes_globais.cpp.
Referenced by tetrahedro_faz_face_mask().
quad_ordem()
void quad_ordem (const int Av[4], const int Bi[4], int dir[3], int sgn[3], int & v2)
Definition at line 3 of file Funcoes_globais.cpp.
Referenced by PhElem< 2 >::gbnmap_faces(), and Hexahedral_face_modal_connectivity().
ResolverSistema()
int ResolverSistema (const int NumD, const int count, int * Ti, int * Tj, double * Tx, double * B, double * x)
Definition at line 464 of file Funcoes_globais.cpp.
Referenced by DG_Prob::DG_initial_conditions().
Sinal()
int Sinal (int i)
Definition at line 104 of file Funcoes_globais.cpp.
Referenced by DG_Prob::DG_EI_IG(), and DG_Prob::DG_EI_Interior().
teste_aresta()
int teste_aresta (int p, int n0, int n1, int & sign, int & ng, int & NG, int & NL, std::vector< EDGE > & border, int Ng[], int nel, int naresta, const Vertice * vert, const int sinal_normal)
Definition at line 317 of file Funcoes_globais.cpp.
References EDGE::comprimento, EDGE::elemento, MAXNG, MAXNL, n0, EDGE::Na, EDGE::Nb, EDGE::normal, EDGE::num_elem, EDGE::num_local, EDGE::sinal, EDGE::tipo, Vertice::x, Vertice::y, and Vertice::z.
tetrahedro_faz_face_mask()
void tetrahedro_faz_face_mask (const int & n_in, int ver_temp[], std::vector< int > & face_mask)
Definition at line 199 of file Funcoes_globais.cpp.
References m, and ordenar().
Referenced by GeProb< MyElem, 2, 2 >::Ler_e_Processar_malha().
ZerarMatrizVetor()
void ZerarMatrizVetor (Teuchos::RCP< Epetra_FECrsMatrix > A, Teuchos::RCP< Epetra_FEVector > RHS)
Definition at line 501 of file Funcoes_globais.cpp.