spectral.h File Reference
#include `MyOptions.h`
#include `MyTrilinos.h`
#include <cstdlib>
#include <iostream>
#include <iomanip>
#include <cmath>
#include <ctime>
#include <cstring>
#include <stdio.h>
#include <algorithm>
#include <vector>
#include <cstddef>
#include `boost/multi_array.hpp`
#include `include.h`
#include `newmat.h`
#include `newmatio.h`
#include <umfpack.h>
#include `Geo.h`
#include `Funcoes_c.h`
#include `Tstruct.h`
#include `Particao.h`
#include `Stdel.h`
#include `Linear.h`
#include `Triangle.h`
#include `Quadrilateral.h`
#include `Tetrahedral.h`
#include `Hexahedral.h`
Classes
struct Field_struct
class Mode
struct ARESTA
struct FACET
struct EDGE
struct FACE
Functions
int indice (int ns, int var, int i)
int npos (int ntot, int i, int j)
int indice_interior (int nnparc[], int iE, int var, int i)
Variables
const int ElemType [6][3]
Function Documentation
indice()
int indice (int ns, int var, int i) [inline]
Definition at line 46 of file spectral.h.
Referenced by DG_Prob::DG_EI_Inflow(), DG_Prob::DG_EI_Outflow(), DG_Elem::VolumeIntegrals(), and DG_Elem::VolumeIntegrals_UMFPACK().
indice_interior()
int indice_interior (int nnparc[], int iE, int var, int i) [inline]
Definition at line 50 of file spectral.h.
Referenced by DG_Prob::DG_EI_Interior().
npos()
int npos (int ntot, int i, int j) [inline]
Definition at line 48 of file spectral.h.
Referenced by DG_Prob::DG_EI_Inflow(), DG_Prob::DG_EI_Interior(), DG_Prob::DG_EI_Outflow(), DG_Elem::VolumeIntegrals(), and DG_Elem::VolumeIntegrals_UMFPACK().
Variable Documentation
ElemType
ElemType
Initial value:
={
  {1,0,0},
  {2,1,0},
  {3,3,1},
  {4,4,1},
  {4,6,4},
  {8,12,6}
}
Valores usados pelo gmsh. Variavel global contendo: {numv, ne, nf}
Parameters
ElemType[][0] = numv = numero de vertices
ElemType[][1] = ne = numero de edges
ElemType[][2] = nf = numero de faces
ElemType[0][] Ponto tipo=0;
ElemType[1][] Linear tipo=1;
ElemType[2][] Triangular tipo=2;
ElemType[3][] Quadrangular tipo=3;
ElemType[4][] Tetraedrico tipo=4;
ElemType[5][] Hexaedrico tipo=5;
Definition at line 57 of file spectral.h.
Referenced by GeProb< MyElem, 2, 2 >::Ler_e_Processar_malha().